### PR TITLE
Update all modules to new NF DSL2 syntax

### PR DESCRIPTION
**Pull request by drpatelh**

### CODE REVIEW

**Comment by drpatelh** [comment]
Got loads of merge conflicts 🤦🏽 even though we stopped merging things...

```
CONFLICT (modify/delete): tests/modules/cnvkit/test.yml deleted in 45985ff6f01c6e2e229b665ba45b159bd925513d and modified in HEAD. Version HEAD of tests/modules/cnvkit/test.yml left in tree.
CONFLICT (modify/delete): tests/modules/cnvkit/main.nf deleted in 45985ff6f01c6e2e229b665ba45b159bd925513d and modified in HEAD. Version HEAD of tests/modules/cnvkit/main.nf left in tree.
CONFLICT (content): Merge conflict in modules/cnvkit/batch/main.nf
CONFLICT (rename/delete): modules/cnvkit/functions.nf deleted in HEAD and renamed to modules/bakta/functions.nf in 45985ff6f01c6e2e229b665ba45b159bd925513d. Version 45985ff6f01c6e2e229b665ba45b159bd925513d of modules/bakta/functions.nf left in tree.
CONFLICT (content): Merge conflict in modules/ultra/pipeline/main.nf
CONFLICT (content): Merge conflict in modules/gunzip/main.nf
```

And I done a quick search for `functions.nf` on my fork and I got this 😱 

```
$ find ./ -type f -name functions.nf
./peddy/functions.nf
./phyloflash/functions.nf
./ectyper/functions.nf
```

Will update now.

**Comment by drpatelh** [comment]
Ok. This is ready for review now!! I had to manually update a few modules due to merge conflicts. @grst be great if you can do one final run of your repo wide tests to collect the failing modules please and update the issue?

**Review by grst — APPROVED** [review]
bulk test is running. 
Didn't look at the module level-changes, but the other modifications LGTM!

**Review by JoseEspinosa — APPROVED** [review]
Same as @grst !
Time to become DSL2 v2.0 🤓 🚀

**Pull request merged**
