### PR TITLE
Adding new modules: xz/compress and xz/decompress

### PR DESCRIPTION
**Pull request by leoisl**
This PR adds xz/compress and xz/decompress modules, for compressing and decompressing `.xz` archives (see https://linux.die.net/man/1/xz, https://tukaani.org/xz/).

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by lrauschning** [comment]
The code looks good to me!
I find it a bit hard to see the point of the `compress` module – as nextflow will keep the output of intermediary steps, running the module on a file will just store the compressed and the uncompressed version of the file, ultimately taking more rather than less space.
There might be some usecases where that is desired for whatever reason, not sure this makes sense to have as an nf-core module though. But on the other hand, it probably won't hurt to have this either.

**Review by lrauschning — COMMENTED** [review]
Saw that multithreading supported by xz was missing (edit: and added it), other than that the code looks good.
The decompression module I think is ready for merging, for the compression module see my comment.

**Comment by leoisl** [comment]
Understood, thanks for the comprehensive explanation and previous experience!

Well, this is my very first new `nf-core` module, so I am more than happy to let the decision of keeping or removing `xz/compress` to you or other more experienced people. Just let me know the decision, as if `xz/compress` is removed from this PR, I will then upload a `.xz` file to https://github.com/nf-core/test-datasets/ so that I can then reference it in the `xz/decompress` nf-test.

**Comment by leoisl** [comment]
Makes sense @muffato ! I think we should then keep `xz/compress`

**Comment by leoisl** [comment]
Hey @lrauschning , I forced `nf-test` to use a single core when testing `xz/compress` and thus re-enabled snapshot for the compressed archive (see [this commit](https://github.com/nf-core/modules/pull/4526/commits/b7a6f5c3c87c9741cf5ebb5314733818fe97790f)). Does it look ok to you?

**Comment by leoisl** [comment]
Just added multithreading for `xz/decompress`, I think this is ready for a re-review!

**Review by lrauschning — APPROVED** [review]
Looks good to me! Multi-threaded decompression is also nice to have when it works, good catch.
Approving this, as there seems to be some interest in a compression module.

**Comment by leoisl** [comment]
Ok, thanks for the quick and thorough review @lrauschning , this module looks much better now.
I am wondering if we need another approval or another step, or if I can simply merge.

**Pull request merged**
