### PR TITLE
umitools/dedup nf-test tests

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by pinin4fjords — COMMENTED** [review]
You're losing a lot of things that were previously snapshotted from the other module outputs- can we snapshot the others (e.g. tsv_edit_distance?)?

**Comment by maxulysse** [comment]
> You're losing a lot of things that were previously snapshotted from the other module outputs- can we snapshot the others (e.g. tsv_edit_distance?)?

Done, I totally missed that in the pytests.
Thanks @pinin4fjords

**Review by pinin4fjords — APPROVED** [review]
Approving, @maxulysse tells me things are passing locally despite the rate limit issues here

**Comment by maxulysse** [comment]
> Approving, @maxulysse tells me things are passing locally despite the rate limit issues here

And you trust him

**Comment by pinin4fjords** [comment]
> And you trust him

Yes and no- I mostly at'd you so I could blame you later ;-)

**Pull request merged**
