### PR TITLE
Strip out meta from bracken to allow more flexibility for pipeline de…

### PR DESCRIPTION
**Pull request by jfy133**
…vs (as per guidelines)

x-ref: https://github.com/nf-core/taxprofiler/issues/168

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by Midnighter** [comment]
My idea was to add these as input channels then. Rather than removing them completely and only using `ext.args`. It's quite useful to run Bracken, for example, on family, genus, and species level. Plus you may have samples with different read lengths and still want to process them all in one pipeline run.

**Comment by jfy133** [comment]
But the pipeline developer can still insert these via `args` no? That's exactly what we already do with taxprofiler with other tools. They don't need to be input channels

**Comment by jfy133** [comment]
> I don't see how you can vary a parameter via `args`, e.g., how can I set for Bracken `-l F`, `-l G`, or `-l S` for the same sample in the same pipeline run?

Still in the meta! But you don't make any assumptions on the names. You duplicate the element in the channel, and modify the meta.

**Comment by Midnighter** [comment]
Okay, fair enough. Most of these changes should be implemented on the `nf-core/modules` first, though, and then we update the module here on the pipeline?

**Comment by jfy133** [comment]
> Okay, fair enough. Most of these changes should be implemented on the `nf-core/modules` first, though, and then we update the module here on the pipeline?

This is in the modules repo ;)

**Pull request merged**
