### PR TITLE
Update DeepARG

### PR DESCRIPTION
**Pull request by jasmezz**
**Two updates:**
1. Version bump 1.0.2 to 1.0.4
2. In order to accept a user-supplied database folder where sometimes the folder depth varies (depending on where the user downloaded it), I added a code line that searches for a specific folder and adapts the database path accordingly. This has been done similar in the modules [bwa/align](https://github.com/nf-core/modules/blob/master/modules/nf-core/bwa/aln/main.nf), [bowtie2/align](https://github.com/nf-core/modules/blob/master/modules/nf-core/bowtie2/align/main.nf), and discussed in [this PR](https://github.com/nf-core/funcscan/pull/320#discussion_r1389421759).

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by jfy133** [comment]
Is this a duplicate of; https://github.com/nf-core/modules/pull/4321 ??

**Comment by jasmezz** [comment]
Yes! :grimacing: Sorry, let's use the other one.

**Comment by muffato** [comment]
I talked to @jasmezz this morning on Slack and we decided to use this PR here rather than my original one (which I've now closed).

I've ported over here a couple of changes from my PR:

- the path of an output file has changed (this may explain why the tests were failing)
- new URLs for deeparg

**Comment by muffato** [comment]
```
  ValueError: Unable to create the compiledir directory '/home/runner/.theano/compiledir_Linux-6.2--azure-x86_64-with-debian-12.2--2.7.15-64'. Check the permissions.
```

This is due to Nextflow 23.10 now using the `--no-home` option of Singularity. The home directory of the user is not mounted in the container anymore. All software that used to rely on being able to cache stuff under `$HOME` start failing. It happened in https://github.com/nf-core/ampliseq/issues/654 too. There, the fix was to define some environment variables https://github.com/nf-core/ampliseq/pull/655/files#diff-87370ce9267c776d95c9efdc8f5b460da721535160dcc0e3fb943457465f8843 to tell the tool to use the current directory (e.g. `work/59/c0b52d5ba5b9a1ad4552571cbf40f2/`) to store stuff. Maybe Theano has a similar option ?

**Comment by jfy133** [comment]
I don't have time to check this out unforttunately :)(

**Comment by jfy133** [comment]
https://stackoverflow.com/questions/34346839/change-base-compiledir-to-save-compiled-files-in-another-directory#34380488

Here we go I hope!

**Comment by muffato** [comment]
`downloaddata` fixed ! I just need to port the fix onto `predict`

**Comment by muffato** [comment]
@jfy133 . `nf-core lint` is now failing due to the transition to nf-test but it used to pass. `pytest` tests work

**Review by SPPearce — APPROVED** [review]
Looks good to me.
Linting currently forces nf-test, but there is discussion on the nf-core slack to swap back to making it a warning not a fail now, but there will be a point nf-test becomes required.

**Comment by muffato** [comment]
💪🏼 yeah !

**Pull request merged**
