### PR TITLE
Add emacs temporary files to .gitignore

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by Emiller88** [comment]
I think this would be better in users global .gitignore.

@heuermh Are you using nextflow-mode though?

**Comment by heuermh** [comment]
> @heuermh Are you using nextflow-mode though?

Don't see such a thing on melpa, sounds useful 😉

**Comment by Emiller88** [comment]
Ah sorry, I was lazy when I first made it and use straight to pull in the repo, and just use my local repo so I can hack on it. https://github.com/Emiller88/nextflow-mode

**Comment by Emiller88** [comment]
Gonna close this, I still think it belongs in your global git config if anything. I would recommend adding it to your [global gitignore](https://www.atlassian.com/git/tutorials/saving-changes/gitignore#global-git-ignore-rules).

Bonus points your could probably turn off lock-files with `(setq create-lockfiles nil)`. Feel free to message me if you ever want to talk about anything emacs related!

**Pull request closed without merging**
