### PR TITLE
remove "--outdir ." from fastq_screen bash command

### LINKED ISSUE #6246: fastqscreen_fastqscreen outdir not writable
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

I get an error that the output directory is not readable. Everything works as intended when the outdir is not part of the fastqscreen bash command as stdout is uses as outdir by default.

### Command used and terminal output

_No response_

### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by FranBonath**
- When specifying the outdir in the bash command, it doesn't have write access to the dir. Since in the absence of a specified outdir the stdout is used, it is ok to omit the outdir specification entirely.
- Add a new optional output for fastqscreen/fastqscreen that outputs fastq files for no genome hits.
- updated the output description
- @SPPearce pinned a perl package gdgraph and added a fastq test that was required

## PR checklist

Closes #6246 

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by SPPearce** [comment]
I don't suppose you could take a look at #5750 and #6075 while you are modifying the module?

**Comment by FranBonath** [comment]
Sure, can have a look. #6075 might be due to the same reason.

**Comment by SPPearce** [comment]
Yeah, the conda recipe seems to have lost one dependencies.
One option might be make the png file optional as a quick fix.

**Comment by FranBonath** [comment]
@SPPearce is it ok to deal with #5750 in this PR or is it better practice to separate issues?

**Comment by SPPearce** [comment]
> @SPPearce is it ok to deal with #5750 in this PR or is it better practice to separate issues?

Feel free to do it in this PR, that is fine.

**Comment by FranBonath** [comment]
"adding optional fastqscreen output: fastq of nohits" fixes issue #5750

**Comment by FranBonath** [comment]
I converted this to draft because I seem to still be a bit away from this being ready to merge.

**Comment by SPPearce** [comment]
I added a perl package that it suggested it required

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
