### PR TITLE
samtools markdup module

### PR DESCRIPTION
**Pull request by priyanka-surana**
Samtools markdup module

## PR checklist

Closes #XXX 

- [x ] This comment contains a description of changes (with reason).
- [ x] If you've fixed a bug or added code that should be tested, add tests!
- [x ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x ] Remove all TODO statements.
- [ x] Emit the `versions.yml` file.
- [ x] Follow the naming conventions.
- [ x] Follow the parameters requirements.
- [ x] Follow the input/output options guidelines.
- [ x] Add a resource `label`
- [ x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by nvnieuwk — CHANGES_REQUESTED** [review]
Looks good! Can you just add a test with a CRAM file?

**Comment by priyanka-surana** [comment]
1. The current `samtools fixmate` and `samtools sort` modules only output `bam` format. No option for changing the output extension. https://github.com/nf-core/modules/blob/master/modules/samtools/sort/main.nf. 

2. How do I set options in `nextflow.config` for one workflow entry point but not the other?

**Comment by nvnieuwk** [comment]
1. Oh too bad, is it a restriction in the modules or in `samtools`?
2. You can specify this using the full workflow name after `withName:` like in this example: https://github.com/nf-core/modules/blob/41dfa13929d2c178855159a69d2e2958c52be155/tests/modules/gatk4/collectreadcounts/nextflow.config#L5-L16

**Comment by priyanka-surana** [comment]
1. The modules, I think they can be possibly updated
2. Thank you.

**Comment by nvnieuwk** [comment]
Okay, let's leave the test for now then :) We can still update this module later when those modules are updated

**Review by nvnieuwk — APPROVED** [review]

**Pull request merged**
