### PR TITLE
Add alleleCounter module

### PR DESCRIPTION
**Pull request by fullama**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `<SOFTWARE>.version.txt` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by MaxUlysse** [comment]
@fullama Can you look at the merge conflicts in `tests/config/pytest_software.yml`

**Comment by fullama** [comment]
..im very confused.. i dont see any conflicts anymore.. this was what i brought up in slack about `nf-core modules create` resorting the  `tests/config/pytest_software.yml` file

**Comment by MaxUlysse** [comment]
> ..im very confused.. i dont see any conflicts anymore.. this was what i brought up in slack about `nf-core modules create` resorting the `tests/config/pytest_software.yml` file

Not sure what happened there, can I get some help from @nf-core/core to solve our issue here?

**Comment by grst** [comment]
```bash
git rebase upstream/master
```
did the trick for me (but I can't force-push it as I don't have permissions to write to @fullama's master branch). 

See also 
 * https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
 * https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by grst** [comment]
Other than the merge conficts, this LGTM, too!

**Comment by fullama** [comment]
thanks!

**Comment by grst** [comment]
Something is still not right, as the diff now shows files unrelated to this PR. 
My best guess is that the rebase didn't complete and you might need to run `git rebase --continue`.

**Comment by fullama** [comment]
..yeah kinda ballooned hasnt it :D i did the rebase and `git rebase --continue` as you mentioned.. at this stage it might be easier to just start again with a new pull request?

**Comment by fullama** [comment]
..sometimes i delude myself and think i understand git.. :( ..seems to have worked :D 👍

**Comment by fullama** [comment]
sorry 🤦

**Review by grst — APPROVED** [review]
LGTM now!

**Comment by MaxUlysse** [comment]
> ..thanks for dragging it over the line.. sweat_smile ..should i merge it then or is that something for ye?

Go, merge, you earned it

**Pull request merged**
