### PR TITLE
correct president stub

### PR DESCRIPTION
**Pull request by paulwolk**
I just fixed the path for the output files in the stub section. Nothing big, but important.

### CODE REVIEW

**Review by nvnieuwk — COMMENTED** [review]
Can you change `output` to the `$prefix` instead? This allows bigger flexibility in the module

**Comment by SPPearce** [comment]
Is there a reason to put the output into a subfolder, rather than just leave it in the top level?

**Comment by paulwolk** [comment]
> Can you change `output` to the `$prefix` instead? This allows bigger flexibility in the module

@nvnieuwk I use the prefix just for the file prefix, the user of the module doesn't see anything of the output directory. Is it necessary? I would change it to ${prefix}/${prefix}report.tsv in that case. 


> Is there a reason to put the output into a subfolder, rather than just leave it in the top level?

@SPPearce I don't want the input fasta (based in root) clash with the output fasta (based in output), which it would do with path("*.fasta*") instead of path("output/*.fasta*"), right?

**Comment by SPPearce** [comment]
Also do you really want the valid and invalid fasta files to go into the same output channel?

**Comment by paulwolk** [comment]
> Also do you really want the valid and invalid fasta files to go into the same output channel?

This is something I would actually happily change. I read some conventions that files of the same filetype should go into one channel, but I would also prefer different channels. So, if that is in line with the conventions, I would do it!

**Comment by nvnieuwk** [comment]
> @nvnieuwk I use the prefix just for the file prefix, the user of the module doesn't see anything of the output directory. Is it necessary? I would change it to ${prefix}/${prefix}report.tsv in that case.

This will emit a folder called `output` in the output directory which will be overwritten for each process so it's possible this causes some weird issues later on :)

**Comment by SPPearce** [comment]
> > Can you change `output` to the `$prefix` instead? This allows bigger flexibility in the module
> 
> @nvnieuwk I use the prefix just for the file prefix, the user of the module doesn't see anything of the output directory. Is it necessary? I would change it to ${prefix}/${prefix}report.tsv in that case.
> 
> > Is there a reason to put the output into a subfolder, rather than just leave it in the top level?
> 
> @SPPearce I don't want the input fasta (based in root) clash with the output fasta (based in output), which it would do with path("*.fasta*") instead of path("output/*.fasta*"), right?

You typically fix that by including a disambiguation check to see if they would clash before the module runs, but that is only going to happen if the input file includes `valid` or `invalid` at the end.

**Comment by SPPearce** [comment]
> > Also do you really want the valid and invalid fasta files to go into the same output channel?
> 
> This is something I would actually happily change. I read some conventions that files of the same filetype should go into one channel, but I would also prefer different channels. So, if that is in line with the conventions, I would do it!

Definitely fine to put the different files into different output channels.
Give me a minute and I'll push an updated version

**Comment by SPPearce** [comment]
Ok, turned into a bit longer than a minute.

- Added meta to the reference fasta
- Swapped to outputting into the working directory rather than a subfolder
- Added a default prefix to the meta.id as standard for most modules
- Compressed the output files in the stub if you have compress set
- Updated the tests to just check the snapshot for the fasta files as they should be stable (it might be good to check that there is only one file in each; that can be seen in the snapshot but isn't being checked that stays that way).
- Changed the channels to have valid and invalid separately.

I ended up putting the underscore on the default prefix which was a bit annoying, it didn't seem to set it otherwise.

**Comment by SPPearce** [comment]
Oh, the meta will need updating with the new channel names

**Review by nvnieuwk — APPROVED** [review]
LGTM!

**Comment by SPPearce** [comment]
Note that the tool says: 
`2024-07-02 10:01:49,883 - president - INFO - Using the prefix: test__* to store results.`
and then completely ignores the second underscore.
I have moved the underscore into the command itself because it makes more sense to me to force the underscore.

**Comment by paulwolk** [comment]
Thank you! The only issue I see now is that if you don't want a prefix, there is still the underscore in front of the name. Is there a way to avoid this? Or is the prefix always mandatory?

**Comment by SPPearce** [comment]
> Thank you! The only issue I see now is that if you don't want a prefix, there is still the underscore in front of the name. Is there a way to avoid this? Or is the prefix always mandatory?

You mean that if you just want the files to be called valid.fasta and invalid.fasta? I guess that is true. 
It could go back into the definition of the prefix if you think that is preferable.

**Comment by SPPearce** [comment]
> > Thank you! The only issue I see now is that if you don't want a prefix, there is still the underscore in front of the name. Is there a way to avoid this? Or is the prefix always mandatory?
> 
> You mean that if you just want the files to be called valid.fasta and invalid.fasta? I guess that is true. It could go back into the definition of the prefix if you think that is preferable.

Is this the kind of module that you'd only run once in a workflow? It looks to me like you'd run it repeatedly, at which point a prefix is a good idea to make them distinct if you want to publish the output.

**Comment by paulwolk** [comment]
> > > Thank you! The only issue I see now is that if you don't want a prefix, there is still the underscore in front of the name. Is there a way to avoid this? Or is the prefix always mandatory?
> > 
> > 
> > You mean that if you just want the files to be called valid.fasta and invalid.fasta? I guess that is true. It could go back into the definition of the prefix if you think that is preferable.
> 
> Is this the kind of module that you'd only run once in a workflow? It looks to me like you'd run it repeatedly, at which point a prefix is a good idea to make them distinct if you want to publish the output.

Both is possible. The pipeline I use it in executes it only one time with a bulk fasta, but of course, you can process multiple fasta with it. Having a mandatory prefix is not a problem, but making it optional would make it more flexible.

**Comment by paulwolk** [comment]
You know what? I think it's fine. A prefix doesn't hurt. Thank you for your work, @SPPearce !! 😃

**Pull request merged**
