### PR TITLE
Limit gatk4 heap size

### PR DESCRIPTION
**Pull request by matthdsm**
Limit gatk4 heap mem to 80% of allotted memory to account for overhead usage

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by maxulysse** [comment]
why 80%?

**Comment by maxulysse** [comment]
ok, so for your own infra then?

**Comment by matthdsm** [comment]
So it seems a float value doesn't work and neither does `ceil`. Suggestions are welcome.

**Comment by pontus** [comment]
80% is a good rule of thumb (at least for not very small runs). The current "pass the entire memory size as heap" is definitely wrong and is quiet likely to lead to unnecessary OOM kills (where resources are really adequate).

**Comment by pontus** [comment]
If one wants to stick with Gigabytes, `(task.memory.giga*0.8).intValue()` should work, but I have a bit of a preference for switching to Megabytes instead, so I'd suggest `(task.memory.mega*0.8).intValue()` (and replacing `"-Xmx${avail_mem}g"` with `"-Xmx${avail_mem}M"` ).

**Comment by matthdsm** [comment]
Thanks for the suggestion @pontus, I've applied it.

**Comment by matthdsm** [comment]
image

**Review by pontus — APPROVED** [review]

**Comment by pontus** [comment]
I can confidently say that passing the memory limit as max heap (-Xmx) is wrong. 

As for the actual value to use, the optimal value will be workload (i.e. application and sample) dependent, but I'd go with 80% if there are no indications of other values that would be better.

If this would be used for very small (say with a memory limit of a few hundred megabytes), it might be that additional tuning should be applied, but I don't think any pipeline does this.

**Review by maxulysse — APPROVED** [review]

**Comment by matthdsm** [comment]
Thanks @pontus and @maxulysse !

**Pull request merged**
