### PR TITLE
[bug]  pin bioperl version in Prokka module

### PR DESCRIPTION
**Pull request by rpetit3**
The latest version of Bioperl is causing some issues with Prokka. (See related issue: https://github.com/tseemann/prokka/issues/598)

```
  Bio::SearchIO: hmmer3 cannot be found
  Exception
  ------------- EXCEPTION -------------
  MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/5.32/site_perl /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/site_perl /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/5.32/vendor_perl /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/vendor_perl /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/5.32/core_perl /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/core_perl .) at /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

  STACK Bio::Root::Root::_load_module /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/site_perl/Bio/Root/Root.pm:522
  STACK (eval) /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/site_perl/Bio/SearchIO.pm:620
  STACK Bio::SearchIO::_load_format_module /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/site_perl/Bio/SearchIO.pm:619
  STACK Bio::SearchIO::new /opt/bactopia/envs/bioconda--prokka-1.14.6/lib/perl5/site_perl/Bio/SearchIO.pm:217
  STACK toplevel /opt/bactopia/envs/bioconda--prokka-1.14.6/bin/prokka:1113
  -------------------------------------


  For more information about the SearchIO system please see the SearchIO docs.
  This includes ways of checking for formats at compile time, not run time
  Can't call method "next_result" on an undefined value at /opt/bactopia/envs/bioconda--prokka-1.14.6/bin/prokka line 1114.
```

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by jfy133** [comment]
@rpetit3 how does the bug affect the singularity/docker containers?

**Comment by rpetit3** [comment]
I got this fixed on the bioconda side, so will just need to change the docker and singularity build number 

https://github.com/bioconda/bioconda-recipes/pull/33411

**Comment by rpetit3** [comment]
Slightly annoying difference between conda and mamba

conda is getting `prokka 1.14.6 pl5321hdfd78af_2` (causes bioperl v1.7.8 which does not work with Prokka)
mamba is getting `prokka 1.14.6 pl5262hdfd78af_3` (fix with bioperl pinned to v1.7.2)

I'm going to wait some time to see if it conda starts picking up the latest build, otherwise bioperl will need to be pinned

**Comment by rpetit3** [comment]
Great, just waiting on singularity image availability

**Comment by ramprasadn** [comment]
singularity image is available now 😄

**Review by ramprasadn — APPROVED** [review]

**Pull request merged**
