### PR TITLE
Bump stranger

### PR DESCRIPTION
**Pull request by fellen31**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Comment by fellen31** [comment]
Looks like the conda tests might be trying to get the noarch version.. any idea why? 

```
Traceback (most recent call last):
  File "/workspace/modules/.nf-test/tests/61aead1164d980e20363cc163f9629f9/work/conda/environment-feb9aab4bcbf8a3bfbe81e5dc905d400/bin/stranger", line
 7, in <module>
    from stranger.__main__ import base_command
  File "/workspace/modules/.nf-test/tests/61aead1164d980e20363cc163f9629f9/work/conda/environment-feb9aab4bcbf8a3bfbe81e5dc905d400/lib/python3.13/site
-packages/stranger/__main__.py", line 14, in <module>
    from stranger.cli import cli as base_command
  File "/workspace/modules/.nf-test/tests/61aead1164d980e20363cc163f9629f9/work/conda/environment-feb9aab4bcbf8a3bfbe81e5dc905d400/lib/python3.13/site
-packages/stranger/cli.py", line 11, in <module>
    from stranger.resources import repeats_json_path
  File "/workspace/modules/.nf-test/tests/61aead1164d980e20363cc163f9629f9/work/conda/environment-feb9aab4bcbf8a3bfbe81e5dc905d400/lib/python3.13/site
-packages/stranger/resources/__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/workspace/modules/.nf-test/tests/61aead1164d980e20363cc163f9629f9/work/conda/environment-feb9aab4bcbf8a3bfbe81e5dc905d400/bin/stranger", line 7, in <module>
    from stranger.__main__ import base_command
  File "/workspace/modules/.nf-test/tests/61aead1164d980e20363cc163f9629f9/work/conda/environment-feb9aab4bcbf8a3bfbe81e5dc905d400/lib/python3.13/site-packages/stranger/__main__.py", line 14, in <module>
    from stranger.cli import cli as base_command
  File "/workspace/modules/.nf-test/tests/61aead1164d980e20363cc163f9629f9/work/conda/environment-feb9aab4bcbf8a3bfbe81e5dc905d400/lib/python3.13/site-packages/stranger/cli.py", line 11, in <module>
    from stranger.resources import repeats_json_path
  File "/workspace/modules/.nf-test/tests/61aead1164d980e20363cc163f9629f9/work/conda/environment-feb9aab4bcbf8a3bfbe81e5dc905d400/lib/python3.13/site-packages/stranger/resources/__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by mashehu** [comment]
nope, sorry, not familiar with this tool. can you have a look at the conda recipe?

**Comment by fellen31** [comment]
Yeah, might have to add setuptools...

**Comment by fellen31** [comment]
Updated the recipe, now works as expected.

**Pull request merged**
