### PR TITLE
Version bumped BUSCO, moved to BUSCO_BUSCO, started implementing nf-test

### LINKED ISSUE #5540: nf-test for BUSCO and move to BUSCO/BUSCO for BUSCO/PLOT
### Is your feature request related to a problem? Please describe

nf-test for BUSCO and move to BUSCO/BUSCO for BUSCO/PLOT

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GallVp**
## PR checklist

Closes #5540  

- [x] Version bumped BUSCO, moved to BUSCO_BUSCO, started implementing nf-test
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by GallVp** [comment]
Hi @mahesh-panchal 

I have started migrating BUSCO to nf-test and wanted to touch base with you before proceeding with all the tests. For now I have only written a test for `busco_genome_single_fasta`:

https://github.com/nf-core/modules/blob/4b0be25a65a1c9b0489f75b01b1c4e4d719ac515/modules/nf-core/busco/busco/tests/main.nf.test#L13C16-L13C41

Let me know if the assertions are adequate or should we include more. There are many assertions on files inside the `busco-` directory which I have not included. I have also kept the old test.yml file for comparison: https://github.com/nf-core/modules/blob/4b0be25a65a1c9b0489f75b01b1c4e4d719ac515/modules/nf-core/busco/busco/tests/old_test.yml

**Comment by GallVp** [comment]
No worries. Thank you @adamrtalbot

**Review by mahesh-panchal — COMMENTED** [review]
Oh wow. Thank you for this. I was dreading this. I know this is going to take a significant amount of time. 

The tests look good ( without testing it all ). I like the additional empty channel checks.

**Comment by GallVp** [comment]
I am glad you like it @mahesh-panchal 

I'll continue working on the remaining tests and then open it for review.

I actually need it for a sub-workflow which will perform BUSCO on a genome (fasta) and the annotation (gff, fasta -> gffread -> faa) and plot the results. I need this sub-workflow for two pipelines. Rather than creating a local module, I thought maybe I can work on the nf-core/busco.

Thank you!

**Review by nvnieuwk — APPROVED** [review]

**Pull request merged**
