### PR TITLE
Removed -1 in CPU size specification for samtools in BWA module

### PR DESCRIPTION
**Pull request by lukbut**
## PR checklist

Closes https://github.com/nf-core/nf-co.re/issues/1053

Removes the -1 in the CPU size specification for the BWA module for samtools.

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by muffato** [comment]
I'm OK with it, but I want someone else to take a look. I've pinged them on Slack

**Comment by nvnieuwk** [comment]
what about situations where you only use one CPU? You should maybe add a small check for that first

**Comment by lukbut** [comment]
> what about situations where you only use one CPU? You should maybe add a small check for that first

@nvnieuwk Hmm I don't think that would be a problem now, after removing the `-1`? I think it was a problem previously as the resultant number of CPUs would result in 0. Now the number of CPUs would result to 1.

**Review by matthdsm — APPROVED** [review]

**Comment by nvnieuwk** [comment]
> > what about situations where you only use one CPU? You should maybe add a small check for that first
> 
> @nvnieuwk Hmm I don't think that would be a problem now, after removing the `-1`? I think it was a problem previously as the resultant number of CPUs would result in 0. Now the number of CPUs would result to 1.

My bad, I looked at the wrong line 😁

**Pull request merged**
