### PR TITLE
Add hifiasm module

### PR DESCRIPTION
**Pull request by drpatelh**
Replacement for https://github.com/nf-core/modules/pull/574

### CODE REVIEW

**Comment by drpatelh** [comment]
Ready for review @sidorov-si . I have tweaked a few more things but otherwise looks good.

**Comment by sidorov-si** [comment]
Oh, thank you very much Harshil! I'll certainly ask people in the `modules` channel on how they manage the branches! Sorry for the inconveniences!

**Comment by drpatelh** [comment]
No worries. I have sent you an invite to the nf-core org. Fancy giving me an approval here if the changes look good to you?

**Review by sidorov-si — APPROVED** [review]
Looks good!

**Pull request merged**
