### PR TITLE
Bump MultiQC to v1.13a (dev)

### PR DESCRIPTION
**Pull request by apeltzer**
This bumps MultiQC to v1.13a, the dev version of MultiQC that should fix issues for smrnaseq and also some other pipelines where DupRadar (I think rnaseq? @drpatelh FYI) was used and the HTML report contained duplicated sections. 

Can be used until there is a new proper V1.13 release as @ewels suggested 🥳 

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by ewels** [comment]
Oh dear. Did your Conda release break MultiQC for everyone @apeltzer? 😱

**Comment by apeltzer** [comment]
I will fix this now, after baby sleeps. No idea what is the problem there but can overwrite build number after bugfixing ...

**Comment by ewels** [comment]
Yeah I'm a bit worried that this is something bigger / upstream..

**Comment by apeltzer** [comment]
https://github.com/bioconda/bioconda-recipes/pull/35553 fixes this, will wait until recipes are there, then fix it and update this PR to get it to modules again - thanks for the help @ewels !

**Review by JoseEspinosa — APPROVED** [review]
Awesome @apeltzer! 🚀

**Pull request merged**
