### PR TITLE
Happy

### PR DESCRIPTION
**Pull request by msantorsola**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by kubranarci — APPROVED** [review]
LGTM

**Comment by georgiakes** [comment]
Hellooo. 
Can you maybe explain those changes? 
It seems that now the module cannot use the -R argument to pass a bed file and it can only use -f.  Is there a reason for that?

**Comment by kubranarci** [comment]
> Hellooo. Can you maybe explain those changes? It seems that now the module cannot use the -R argument to pass a bed file and it can only use -f. Is there a reason for that?

Hello, I am checking the documentation now, there seems to be a discrepancy for the input files. Looks quite interesting. 

https://github.com/Illumina/hap.py it seems like -f is being used for high confidence files (no problem this is fine), yet When I check the tool documentation from 3.14 it seems like -R still exists to define regions, and -f seems to be implemented for confidence beds only. I think we should of keep -R as well for regional files while implemented new -f only for confidence regions. The confusion is probably happened as -R used to be used as confidence file input.

**Comment by georgiakes** [comment]
Ok. Should I open a PR to get the -R argument back to the module?

**Comment by kubranarci** [comment]
I think it will be nice! thanks for noticing. We would need to update variantbenchmarking pipeline as well..

**Pull request merged**
