### PR TITLE
Update KrakenUniq: Add SE/PE to suffixes as cannot control by typical ext.prefix

### PR DESCRIPTION
**Pull request by jfy133**
Due to the nature of the construction of the module (for efficiency loading the database then aligning all samples in one process in the same process), we found that as we cannot control the suffix in the normal way via `ext.args`, we often get file-name collisions or overwrites at a pipeline results level when the leading prefix is the same between a single-end and a paired-end library (/end longest sentence of the week).

This PR hardcodes `.se` and `.pe` to file output suffxes to ensure they do not overwrite each other on publishing by providing a unique name.

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by Midnighter** [comment]
I was wondering if this is not an artificial problem? Wouldn't under normal circumstances the run accession always be different if there was a paired-end and a single-end sequencing run of the same sample?

**Comment by Midnighter** [comment]
Additional thoughts:

* You have not configured the language server with Harshil-alignment? 😱 
* I haven't seen any other modules or pipelines adding a distinction for the filenames based on PE or SE. I don't think this part is special to KrakenUniq and would be a problem for every module, no?

**Comment by jfy133** [comment]
> I was wondering if this is not an artificial problem? Wouldn't under normal circumstances the run accession always be different if there was a paired-end and a single-end sequencing run of the same sample?

Yes it somewhat is, but I don't see a way around it. In the pipeline schema for taxprofiler, we can't unique sample IDs if they don't use run accessions because we can't conditionally check the uniquness based on the presnce of another column.

Regardless, the tests are failing so it needs to be fixed :sweat_smile: 

I just realised though I think I could actually add the `.se` `.pe` prefix in modules.conf, now I've looked through youre new code... I will try that first...

> Additional thoughts:
> 
>     * You have not configured the language server with Harshil-alignment? 😱
> 
>     * I haven't seen any other modules or pipelines adding a distinction for the filenames based on PE or SE. I don't think this part is special to KrakenUniq and would be a problem for every module, no?

- I forgot to turn back on the format-on-save since they fixed 
- No, becuase normally it's easy to distinguish between single- and paried- end in a run, but as we were trying to _infer_ a prefix I thought it workign work, but see my point above.

**Comment by jfy133** [comment]
Had a huddle with @Midnighter - actually we can use the same logic as the typical nf-core `ext.prefix` - so we don't have to hardcode -the diffference is actually jkust that the the prefix comes from a n input channel rather than `ext.`, so I can close this.

If it comes up again, we can have a follow up PR to updateth the `meta.yaml` to give explicit guidance on this

**Pull request closed without merging**
