### PR TITLE
reduce memory for meryl count to avoid crash

### PR DESCRIPTION
**Pull request by MartinPippel**
Avoid that meryl count crashes due to memory issues. It seems that meryl uses the complete buffer provided via `memory=SIZE` for the kmer counts, but meryl itself uses some memory too. When using meryl count within singularity containers and slurm,  then usually slurm is killing meryl due to that overhead. 

Solution, reduce the meryl memory kmer buffer `task.memory` by 10%. This is potentially a bit to much as usually the memory overhead was around 2-4Gb, but it solved all my issues on 3 three different compute clusters (Uppmax rackham, PDC dardel, and nac).

### CODE REVIEW

**Review by mahesh-panchal — APPROVED** [review]
This is fine, but need to get the tests working.

**Comment by SPPearce** [comment]
Is the same issue happening with MERFIN here?

**Comment by mahesh-panchal** [comment]
No, it's also things like version strings are different between meryl conda ( doesn't have one ) and meryl singularity ( 1.4.1 ).
I'm not sure what else is different atm.

**Comment by SPPearce** [comment]
MERFIN_HIST is also failing, so might be as well as the other issues:
https://github.com/nf-core/modules/actions/runs/12006625811/job/33465567907?pr=7074#step:4:413

**Comment by mahesh-panchal** [comment]
When #6921 is merged, this can be closed.

**Pull request closed without merging**
