### PR TITLE
Update seqkit to 2.8.1

### PR DESCRIPTION
**Pull request by heuermh**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by thanhleviet — APPROVED** [review]

**Review by mashehu — CHANGES_REQUESTED** [review]
Environment yaml and snapshot needs to be updated as well

**Comment by heuermh** [comment]
> Environment yaml and snapshot needs to be updated as well

Updated `environment.yml`, what is snapshot?

**Review by mashehu — APPROVED** [review]
Ah sorry, thought this was with nf-test. Then nevermind. But maybe you could update all seqkit modules? So they are in sync.

**Comment by heuermh** [comment]
> But maybe you could update all seqkit modules? So they are in sync.

I tried this [earlier](https://github.com/nf-core/modules/pull/3925) and there were test failures due to bad checksums.  I'm only maintainer on these two seqkit commands.

**Comment by mashehu** [comment]
Okay. Would be great if you could open an issue with the failing tests/missing update, so somebody else could pick it up.

**Comment by heuermh** [comment]
> Would be great if you could open an issue with the failing tests/missing update, so somebody else could pick it up.

Thanks for the suggestion!  See
https://github.com/nf-core/modules/issues/5473

**Pull request merged**
