### PR TITLE
Fix for nested directories in tar archive

### PR DESCRIPTION
**Pull request by matthdsm**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by matthdsm** [comment]
Hi @jfy133 

I took another look at your modifications and added a small fix for my issue with the flowcell tar. Turns out you were trying to check for a single directory in the top of the tar, but your command also found all nested directories, causing the module to use the fallback.

This should fix that by checking if there's more than one _unique_ top directory

**Review by jfy133 — APPROVED** [review]

**Comment by matthdsm** [comment]
Thanks for the quick ✔️

**Comment by jfy133** [comment]
Ah, sorry after the fact: if the tar contains multiple top level directories, it should go to the fallback right? The output directory of the module should contain each of those top level directories, no? You may not want to strip that? Or maybe I misunderstand

**Comment by jfy133** [comment]
Ok cool, thanks for clarifying!

**Pull request merged**
