### PR TITLE
new module bbmap/clumpify

### PR DESCRIPTION
**Pull request by tamuanand**
## PR checklist
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.

### CODE REVIEW

**Comment by tamuanand** [comment]
@drpatelh and @mahesh-panchal - This is my first attempt at creating something within nf-core/modules. 
- Tying this PR to this slack message - https://nfcore.slack.com/archives/CJRH30T6V/p1661383088266169

**Comment by mahesh-panchal** [comment]
I was going to point you to the creating a new module guide, but I see it's out of date: https://nf-co.re/docs/contributing/tutorials/dsl2_modules_tutorial

What I usually do though is to open my fork of nf-core/modules on Gitpod.
Then:
1. `git checkout -b my_new_module`: Which creates a new git branch for your module. 
2. `nf-core modules create tool/subtool`: So in this case `nf-core modules create bbmap/clumpify`. This creates the necessary files you need to modify.
3. `open modules/bbmap/clumpify/m* tests/modules/bbmap/clumpify/*`: Which opens the five files you need to edit in the editor. 
4. Edit the `main.nf` and the `meta.yml`
5. Write a test, and select a relevant test data set from `open tests/config/test_data.config`: See the other modules for examples how to use this map. 
6. Run the test with `nf-core modules create-test-yml bbmap/clumpify -f -p`. This will highlight any errors, and if you need to add configuration to the `nextflow.config` open in your editor. 
7. Once the `test.yml` has been written, go through it, fixing any TODO's. 
8. Then try `nf-core modules lint bbmap/clumpify` and fix any linting issues.
9. Finally `nf-core modules test bbmap/clumpify` with both docker and conda/mamba.
10. Git add and commit your changes as you're going along, and then finally push the Gitpod repo to your fork of the repository with `git push` ( follow instructions if branch doesn't exist on remote). 
11. Normally this would be the time to make a pull request to nf-core/modules, but since you have it open, just modify anything as necessary. 

Nice start btw.

**Comment by tamuanand** [comment]
@mahesh-panchal 
- I am short on bandwidth for next 3-4 weeks 
- does what I have suffice for minor tweaks by say someone as experienced as you are with nf-core modules

**Comment by tamuanand** [comment]
Console output from  `nf-core modules lint bbmap/clumpify`
```
gitpod /workspace/modules (bbmap_clumpify) $ nf-core modules create-test-yml bbmap/clumpify -f -p

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.4.1 - https://nf-co.re


INFO     Looking for test workflow entry points: 'tests/modules/bbmap/clumpify/main.nf'                                                                                       test_yml_builder.py:123
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
INFO     Building test meta for entry point 'test_bbmap_clumpify_single_end'                                                                                                  test_yml_builder.py:157
INFO     Setting env var '$PROFILE' to an empty string as not set.                                                                                                            test_yml_builder.py:301
         Tests will run with Docker by default. To use Singularity set 'export PROFILE=singularity' in your shell before running this command.                                                       
INFO     Running 'bbmap/clumpify' test with command:                                                                                                                          test_yml_builder.py:325
         nextflow run ./tests/modules/bbmap/clumpify -entry test_bbmap_clumpify_single_end -c ./tests/config/nextflow.config  -c                                                                     
         ./tests/modules/bbmap/clumpify/nextflow.config --outdir /tmp/tmpkb21vian -work-dir /tmp/tmpjkl6fxr5                                                                                         
Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
INFO     Repeating test ...                                                                                                                                                   test_yml_builder.py:328
Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
INFO     Test workflow finished!                                                                                                                                              test_yml_builder.py:342
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
INFO     Building test meta for entry point 'test_bbmap_clumpify_paired_end'                                                                                                  test_yml_builder.py:157
INFO     Running 'bbmap/clumpify' test with command:                                                                                                                          test_yml_builder.py:325
         nextflow run ./tests/modules/bbmap/clumpify -entry test_bbmap_clumpify_paired_end -c ./tests/config/nextflow.config  -c                                                                     
         ./tests/modules/bbmap/clumpify/nextflow.config --outdir /tmp/tmpvmt0_t8f -work-dir /tmp/tmppk1v9bnd                                                                                         
Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
INFO     Repeating test ...                                                                                                                                                   test_yml_builder.py:328
Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
INFO     Test workflow finished!                                                                                                                                              test_yml_builder.py:342
INFO     Writing to 'tests/modules/bbmap/clumpify/test.yml'
```
Console output from  `nf-core modules lint bbmap/clumpify`

```
gitpod /workspace/modules (bbmap_clumpify) $ nf-core modules lint bbmap/clumpify

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.4.1 - https://nf-co.re


INFO     Linting modules repo: '.'                                                                                                                                                    __init__.py:159
INFO     Linting module: 'bbmap/clumpify'                                                                                                                                             __init__.py:163

╭──────────────────────╮
│ LINT RESULTS SUMMARY │
├──────────────────────┤
│ [✔]  22 Tests Passed │
│ [!]   0 Test Warning │
│ [✗]   0 Test Failed  │
╰──────────────────────╯
```

Console output from `nf-core modules test bbmap/clumpify` using `docker profile`

```
gitpod /workspace/modules (bbmap_clumpify) $ nf-core modules test bbmap/clumpify

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.4.1 - https://nf-co.re


INFO     Press enter to use default values (shown in brackets) or type your own responses                                                                                           module_test.py:61
? Choose software profile Docker
INFO     Setting environment variable '$PROFILE' to 'docker'                                                                                                                       module_test.py:115
────────────────────────────────────────────────────────────────────────────────────────── bbmap/clumpify ───────────────────────────────────────────────────────────────────────────────────────────
INFO     Running pytest for module 'bbmap/clumpify'                                                                                                                                module_test.py:142
======================================================================================== test session starts ========================================================================================
platform linux -- Python 3.9.7, pytest-7.1.2, pluggy-1.0.0
rootdir: /workspace/modules, configfile: pytest.ini
plugins: workflow-1.6.0
collecting ... 
collected 993 items                                                                                                                                                                                 

bbmap clumpify test_bbmap_clumpify_single_end:
        command:   nextflow run ./tests/modules/bbmap/clumpify -entry test_bbmap_clumpify_single_end -c ./tests/config/nextflow.config  -c ./tests/modules/bbmap/clumpify/nextflow.config
        directory: /tmp/pytest_workflow_p09vxapw/bbmap_clumpify_test_bbmap_clumpify_single_end
        stdout:    /tmp/pytest_workflow_p09vxapw/bbmap_clumpify_test_bbmap_clumpify_single_end/log.out
        stderr:    /tmp/pytest_workflow_p09vxapw/bbmap_clumpify_test_bbmap_clumpify_single_end/log.err
'bbmap clumpify test_bbmap_clumpify_single_end' done.

bbmap clumpify test_bbmap_clumpify_paired_end:
        command:   nextflow run ./tests/modules/bbmap/clumpify -entry test_bbmap_clumpify_paired_end -c ./tests/config/nextflow.config  -c ./tests/modules/bbmap/clumpify/nextflow.config
        directory: /tmp/pytest_workflow_p09vxapw/bbmap_clumpify_test_bbmap_clumpify_paired_end
        stdout:    /tmp/pytest_workflow_p09vxapw/bbmap_clumpify_test_bbmap_clumpify_paired_end/log.out
        stderr:    /tmp/pytest_workflow_p09vxapw/bbmap_clumpify_test_bbmap_clumpify_paired_end/log.err
'bbmap clumpify test_bbmap_clumpify_paired_end' done.

tests/test_versions_yml.py ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss..ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 16%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 35%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 54%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 73%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 92%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss                                                                                                                          [ 99%]
tests/modules/bbmap/clumpify/test.yml .......                                                                                                                                                 [100%] Keeping temporary directories and logs. Use '--kwd' or '--keep-workflow-wd' to disable this behaviour.


========================================================================================= warnings summary ==========================================================================================
../../opt/conda/lib/python3.9/site-packages/pytest_workflow/plugin.py:122: 589 warnings
  /opt/conda/lib/python3.9/site-packages/pytest_workflow/plugin.py:122: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return YamlFile.from_parent(parent, fspath=path)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================================== 9 passed, 984 skipped, 589 warnings in 23.59s ===========================================================================
```

Console output from `nf-core modules test bbmap/clumpify` using `conda profile`

```
gitpod /workspace/modules (bbmap_clumpify) $ nf-core modules test bbmap/clumpify

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.4.1 - https://nf-co.re


INFO     Press enter to use default values (shown in brackets) or type your own responses                                                                                           module_test.py:61
? Choose software profile Conda
INFO     Setting environment variable '$PROFILE' to 'conda'                                                                                                                        module_test.py:115
────────────────────────────────────────────────────────────────────────────────────────── bbmap/clumpify ───────────────────────────────────────────────────────────────────────────────────────────
INFO     Running pytest for module 'bbmap/clumpify'                                                                                                                                module_test.py:142
======================================================================================== test session starts ========================================================================================
platform linux -- Python 3.9.7, pytest-7.1.2, pluggy-1.0.0
rootdir: /workspace/modules, configfile: pytest.ini
plugins: workflow-1.6.0
collecting ... 
collected 993 items                                                                                                                                                                                 

bbmap clumpify test_bbmap_clumpify_single_end:
        command:   nextflow run ./tests/modules/bbmap/clumpify -entry test_bbmap_clumpify_single_end -c ./tests/config/nextflow.config  -c ./tests/modules/bbmap/clumpify/nextflow.config
        directory: /tmp/pytest_workflow_syynic_f/bbmap_clumpify_test_bbmap_clumpify_single_end
        stdout:    /tmp/pytest_workflow_syynic_f/bbmap_clumpify_test_bbmap_clumpify_single_end/log.out
        stderr:    /tmp/pytest_workflow_syynic_f/bbmap_clumpify_test_bbmap_clumpify_single_end/log.err
'bbmap clumpify test_bbmap_clumpify_single_end' done.

bbmap clumpify test_bbmap_clumpify_paired_end:
        command:   nextflow run ./tests/modules/bbmap/clumpify -entry test_bbmap_clumpify_paired_end -c ./tests/config/nextflow.config  -c ./tests/modules/bbmap/clumpify/nextflow.config
        directory: /tmp/pytest_workflow_syynic_f/bbmap_clumpify_test_bbmap_clumpify_paired_end
        stdout:    /tmp/pytest_workflow_syynic_f/bbmap_clumpify_test_bbmap_clumpify_paired_end/log.out
        stderr:    /tmp/pytest_workflow_syynic_f/bbmap_clumpify_test_bbmap_clumpify_paired_end/log.err
'bbmap clumpify test_bbmap_clumpify_paired_end' done.

tests/test_versions_yml.py ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss..ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 16%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 35%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 54%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 73%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 92%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss                                                                                                                          [ 99%]
tests/modules/bbmap/clumpify/test.yml .......                                                                                                                                                 [100%] Keeping temporary directories and logs. Use '--kwd' or '--keep-workflow-wd' to disable this behaviour.


========================================================================================= warnings summary ==========================================================================================
../../opt/conda/lib/python3.9/site-packages/pytest_workflow/plugin.py:122: 589 warnings
  /opt/conda/lib/python3.9/site-packages/pytest_workflow/plugin.py:122: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return YamlFile.from_parent(parent, fspath=path)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== 9 passed, 984 skipped, 589 warnings in 80.22s (0:01:20) ======================================================================
```
Console output from `nf-core modules test bbmap/clumpify` using `singularity profile`

```
gitpod /workspace/modules (bbmap_clumpify) $ nf-core modules test bbmap/clumpify
                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.4.1 - https://nf-co.re


INFO     Press enter to use default values (shown in brackets) or type your own responses                                                                                           module_test.py:61
? Choose software profile Singularity
INFO     Setting environment variable '$PROFILE' to 'singularity'                                                                                                                  module_test.py:115
CRITICAL Command 'singularity' not found - is it installed?      
```

**Comment by tamuanand** [comment]
@mahesh-panchal 
- I chose to include all gitpod console output in above comment 
- this will benefit any newcomers like me wanting to contribute to nf-core/modules

Hope it is OK

**Pull request closed without merging**
