### PR TITLE
Move annotsv containers to seqera containers

### PR DESCRIPTION
**Pull request by nvnieuwk**
The old `biocontainers` were having some permission errors that were bugging me for a long time. It seems the permissions do get set correctly by migrating to seqera containers

### CODE REVIEW

**Review by JoseEspinosa — APPROVED** [review]
LGTM! 🚀

**Comment by nvnieuwk** [comment]
> Is the `oras` protocol just working when singularity is used?

It's only used for singularity in this case, but I'm not sure what it does in case of docker (but I guess it will fail since this is pointing to a singularity container)

**Comment by nvnieuwk** [comment]
(currently fixing the tests and updating the other AnnotSV module)

**Comment by mahesh-panchal** [comment]
I think you can use that protocol for both docker and singularity

**Comment by nvnieuwk** [comment]
I'll give it a go locally :p

**Comment by nvnieuwk** [comment]
```
│   Command error:                                                                                                                                                        │
│     docker: invalid reference format.                                                                                                                                   │
│     See 'docker run --help'. 
```

**Comment by mahesh-panchal** [comment]
Same, Oh well. It seems I misunderstood oras.

**Comment by nvnieuwk** [comment]
Everyone okay with me merging this or should I wait for more reviews?

**Comment by nvnieuwk** [comment]
Okay I'll merge this, we can still revert it if something comes up (I'm the only using this module as far as I know so it should be fine)

**Pull request merged**
