### PR TITLE
Update vcf2maf and add stub tests

### PR DESCRIPTION
**Pull request by famosab**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by famosab** [comment]
I am preparing a newer version of the VEP cache test-data to enable proper testing (in reasonable amounts of time).

**Comment by famosab** [comment]
Will work when https://github.com/nf-core/test-datasets/pull/1435 is merged.

**Review by LouisLeNezet — APPROVED** [review]
Great job for this update.
Why did you have to change to a seqera container ?

**Comment by famosab** [comment]
@LouisLeNezet for some reason your approval is not enough for me to merge???

I switched because I updated the vep package and mulled containers are easier with wave :)

**Comment by LouisLeNezet** [comment]
Yeah to merge you also need all the test to pass.
The runners sometimes fail, so you might need to rerun the failing test to make it pass.

**Review by LouisLeNezet — APPROVED** [review]

**Pull request merged**
