### PR TITLE
added stub command and tests

### LINKED ISSUE #6026: [FEATURE] add stub and tests to lofreq/filter
### Is your feature request related to a problem? Please describe

`lofreq/filter` has no stub execution and no tests. This is problematic e.g. for workflows that are automatically tested with stub-tests.

### Describe the solution you'd like

Let's add a stub command and some basic nf-tests.

### PR DESCRIPTION
**Pull request by Krannich479**
## PR checklist

This PR adds stub execution and nf-tests to `lofreq/filter`.
Closes #6026 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [x] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by nvnieuwk — APPROVED** [review]
LGTM

**Review by vagkaratzas — COMMENTED** [review]
Remember to delete old pytests

**Review by vagkaratzas — CHANGES_REQUESTED** [review]
Remember to delete old pytests and it should be ok!

**Review by vagkaratzas — APPROVED** [review]
Perfect!

**Pull request merged**
