### PR TITLE
Remove tags in tests and tag.yml

### LINKED ISSUE #6001: Remove tags.yml files if we are sure we no longer need them

### PR DESCRIPTION
**Pull request by chriswyatt1**
## PR checklist

Closes #6001 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by nvnieuwk** [comment]
I think we should keep the tags in the test file. This will make testing in pipelines a lot easier

**Comment by chriswyatt1** [comment]
Ah ok, yes, if they are needed then we shouldn't default remove them from all the modules

**Comment by edmundmiller** [comment]
I think we should revisit the tags in the modules. With the new "only test what's changed" and dependencies in nf-test I'm not sure the amount of tags is necessary. 

Not sure what to do differently but it's just overkill.

**Comment by nvnieuwk** [comment]
Yeah that's mostly fine in modules but it does help in pipelines where you want to test a specific part of your pipeline. The tags are mostly automated by tools anyway so it's no extra work for developers.

**Comment by jfy133** [comment]
I feel the tags are still useful for doing one off tests while developping, but the `modules` and `modules_nf-core` oones are not that useful.

So I vote to remove those two and keep just the ones that are specific to that module (e.g. that module, and any upstream modules used during teh testing)

**Comment by jfy133** [comment]
> I think we should revisit the tags in the modules. With the new "only test what's changed" and dependencies in nf-test I'm not sure the amount of tags is necessary.

The only test what's changed is fine for just testing on GHA (I would presume?) Not locally, or?

**Comment by maxulysse** [comment]
I think it's overkill to have tags too, so for all removal

**Comment by jfy133** [comment]
wait I'm confused, is the purpose of this to have literally 0 tags at all?

**Comment by mirpedrol** [comment]
Hi! We have some issues in tools to update the pipeline template so that we don't need tags in modules, see https://github.com/nf-core/tools/issues/2855 and https://github.com/nf-core/tools/issues/2854.
So it looks OK to remove them.

To test only one module, you can use the path, so there's no need to use a tag.

**Pull request closed without merging**
