### PR TITLE
update GATK's annotateintervals and filterintervals, and CNVkit's batch with extra meta fields

### PR DESCRIPTION
**Pull request by ramprasadn**
## PR checklist

This PR adds extra meta fields to the following modules,

1. gatk4/annotateintervals
2. gatk4/filterintervals
3. cnvkit/batch

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by mahesh-panchal — COMMENTED** [review]
What is the purpose of all these extra meta's? They're not referenced anywhere in the code afterwards.

**Review by maxulysse — APPROVED** [review]
LGTM

**Comment by ramprasadn** [comment]
IIRC, there were a couple of arguments for adding extra-metas.

1. In metagenomic pipelines where folks used multiple references, it was desirable to be able to store information about each reference in a meta field. 
2. Since almost all output channels contain a meta, we often found ourselves in situations where we had to remove it before passing it as an input to another module. Adding extra meta fields allows us to avoid such manipulations in the pipelines.

**Comment by mahesh-panchal** [comment]
Is there a slack link to the conversation ( or just ping me in slack )? I think I need more background to understand this.

**Pull request merged**
