### PR TITLE
Wave with Dockerfiles

### PR DESCRIPTION
**Pull request by edmundmiller**
For @matthdsm on #4935

Branched off from #4080

### CODE REVIEW

**Comment by matthdsm** [comment]
Which part of this is for me exactly?

**Comment by edmundmiller** [comment]
Just in hopes of making the GATK custom images easier to generate!

**Comment by matthdsm** [comment]
No apologies needed! I just wasn't following what what happening exactly 😛 
Nice work on the wave stuff!

**Comment by edmundmiller** [comment]
@maxulysse This was from the maintainer meeting on Friday. https://github.com/nf-core/modules/commit/116adce113b45050bdf437405147e7b7feeac02f

Idk if that's what you were thinking about too, but it was at least what was in my head. 🙃

**Comment by matthdsm** [comment]
That's exactly what the Broad does. Does it work??

**Comment by matthdsm** [comment]
Apparently not 😞 
```
Requirement 'gatkPythonPackageArchive.zip' looks like a filename, but the file does not exist
Processing ./gatkPythonPackageArchive.zip\nERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/gatkPythonPackageArchive.zip
```

**Comment by edmundmiller** [comment]
I think we'd have to get the path right, and even then I'm not sure if it'll play nicely with the conda install

**Comment by edmundmiller** [comment]
I stand corrected. https://simonwillison.net/2022/Apr/24/pip-install-github/

**Comment by edmundmiller** [comment]
So it worked... but it broke wave...

**Comment by edmundmiller** [comment]
This should be ready to go! Dockerfiles would need reworking, but it's there to be used now 🤷🏻‍♂️

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
