### PR TITLE
Update json for meta yml

### PR DESCRIPTION
**Pull request by mirpedrol**
Applying the same change from https://github.com/nf-core/modules/pull/5837 to the `master` branch. This is needed for the nf-core/tools tests to pass.

### CODE REVIEW

**Review by nvnieuwk — APPROVED** [review]
LGTM!

**Comment by mirpedrol** [comment]
@nf-core-bot fix linting

**Comment by mirpedrol** [comment]
😞 pre-commit is using this JSON schema so it's failing because modules are not updated

**Comment by mirpedrol** [comment]
Closing this now, we should be ready to merge `batch_update_staging` to `master` to solve the errors once subworkflows are updated

**Pull request closed without merging**
