### PR TITLE
feat: add sourmash sketch

### LINKED ISSUE #1211: new module: sourmash

### PR DESCRIPTION
**Pull request by Midnighter**
## PR checklist

Add a new module for creating sourmash sketches.

Closes #1211

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Review by JoseEspinosa — APPROVED** [review]
Nice! I just add a small comment.
Singularity tests are not working although I tried outside of GitHub and it does, any ideas why is failing?

**Comment by JoseEspinosa** [comment]
Merged master, maybe this time singularity test work...

**Comment by JoseEspinosa** [comment]
💥

**Comment by Midnighter** [comment]
Thank you for the review! Regarding [your comment](https://github.com/nf-core/modules/pull/1287#discussion_r806645432), I have no idea what the correct approach is but I see that the `versions.yml` is included in other module tests, for example, in https://github.com/nf-core/modules/blob/12b0bc5aa9b116d9459311083a46de8f8aa98c90/tests/modules/bamtools/convert/test.yml#L23-L24.

**Comment by JoseEspinosa** [comment]
Fair enough, I check others and didn't, I will include it from now on.

**Pull request merged**
