### PR TITLE
add FCS adaptor

### PR DESCRIPTION
**Pull request by d4straub**
Adds NCBI's FCS adaptor, a contamination screening software for genome assemblies.

## PR checklist

Closes https://github.com/nf-core/modules/issues/1951

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by SPPearce — APPROVED** [review]
Looks good to me.

**Comment by d4straub** [comment]
@SPPearce Thanks a lot, but while the module is working with singularity, docker is failing. I'll need to sort that imho.

**Review by SPPearce — CHANGES_REQUESTED** [review]
Docker and Conda not currently working

**Comment by SPPearce** [comment]
> @SPPearce Thanks a lot, but while the module is working with singularity, docker is failing. I'll need to sort that imho.

Yes, that needs to be fixed, didn't notice that. I have seen that on another PR today, singularity working fine by docker and conda not.

**Comment by d4straub** [comment]
@SPPearce Execution with docker is now successful (the docker container was faulty), conda wont work, because the maintainers of the tool do not add it to (bio)conda (yet?).

**Review by SPPearce — APPROVED** [review]

**Comment by SPPearce** [comment]
Thanks @d4straub !

**Pull request merged**
