### PR TITLE
bamsormadup: add extra test case, fix single file input

### PR DESCRIPTION
**Pull request by matthdsm**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by mahesh-panchal — APPROVED** [review]
LGTM

**Comment by mahesh-panchal** [comment]
Anything that can be done about the conda error?
```
 Command error:
   bamcat: symbol lookup error: /home/runner/pytest_workflow_fr61jt_0/biobambam_bamsormadup_test_biobambam_bamsormadup_multi_input/work/conda/env-292b443781b65a014f1c66fe7171f63e/bin/../lib/libmaus2.so.2: undefined symbol: _ZTIN6snappy4SinkE
   bamsormadup: symbol lookup error: /home/runner/pytest_workflow_fr61jt_0/biobambam_bamsormadup_test_biobambam_bamsormadup_multi_input/work/conda/env-292b443781b65a014f1c66fe7171f63e/bin/../lib/libmaus2.so.2: undefined symbol: _ZTIN6snappy4SinkE
```

**Review by nvnieuwk — APPROVED** [review]

**Comment by matthdsm** [comment]
I've no idea actually. We've encountered this issue before. It seems to have something to do with a missing library or something. 
Weird thing is, I've personally never had any issue with it, so I think it might even be distro related

**Comment by matthdsm** [comment]
I've got the same version locally, installed by conda, which seems to work fine

**Pull request merged**
