### PR TITLE
Refactor all tests to use pytest-workflow

### PR DESCRIPTION
**Pull request by Emiller88**
A continuation of #80

### CODE REVIEW

**Comment by Emiller88** [comment]
I think this is ready to review. Few things:

- This doesn't cover #83.

**Comment by drpatelh** [comment]
> I need input on the nextflow test workflow names, currently just doing test_software_command. I'm thinking we could do without the software portion, and then maybe follow the command with some better descriptions for bad inputs etc.

I think `software_command` is fine no? You mean in the `-entry` section of the `command` right? Be good to keep both just in case different tools have the same command. Or am I missing something else?

> I need input on a standard test name format for the basic tests ex: - name: Run fastqc paired-end test workflow or Run fastqc paired-end since it's always a test workflow.

Be great to keep this as generic as possible. But I guess some customisation will be required because different modules will require different tests. If `fastqc` is mentioned somewhere else in the name of the Action then just "Test paired-end" would be fine?

**Comment by Emiller88** [comment]
> I think `software_command` is fine no? You mean in the `-entry` section of the `command` right? Be good to keep both just in case different tools have the same command. Or am I missing something else?

I mean `workflow software_command {` When the test gets ran it prefixes the `- run:` title before it so the `test_software_command` may not have to be so verbose, but I think I like the verbose now that I've slept on it. 

> Be great to keep this as generic as possible. But I guess some customisation will be required because different modules will require different tests. If `fastqc` is mentioned somewhere else in the name of the Action then just "Test paired-end" would be fine?

Yeah, exactly I plan on added a few tests that I stumbled upon writing them, like feeding two reads in and specifying that it's single end is true also, that should throw an error. Just to cover possible regressions. So the run section might say `Run fastqc single-end but pass it two reads` and it's sibling `Run fastqc paired-end but pass it one read`

**Comment by Emiller88** [comment]
@drpatelh @ewels I'm not sure why the CI isn't triggering, can either of you try to kick it off manually for me? I think it may have to do with the subdirectory under workflows not being something they support. I tried to move the fastqc file out to see if it would trigger but it didn't work :upside_down_face:

**Comment by grst** [comment]
Try to quote the paths that contain a wildcard: 

>  If you start a pattern with *, [, or !, you must enclose the pattern in quotes.

(https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)

It also seems that subdirectories in `.github/workflows` are not supported: 
 * https://github.community/t/feature-request-allow-workflow-configuration-in-sub-folders/16776
 * https://stackoverflow.com/questions/62288443/where-should-you-put-the-git-hub-workflow-directory-for-actions-in-a-full-stack

**Review by grst — APPROVED** [review]

**Comment by Emiller88** [comment]
See I thought the same thing when I saw that, but those are talking about separate `.github` dirs not just subdirectories in the`.github/workflows` directory. 

I also don't see an issue with the wildcards because they end in it, which is fine according to the docs.

**Comment by Emiller88** [comment]
Alright I think that solved the CI issues. Sad we can't have more organization. :(

I still need to make issues for modules that haven't been tested and possible e2e tests. But other than that these should be ready to merge.

Created #88 to follow up on what versions(and if multiple) should be supported for CI.

**Comment by drpatelh** [comment]
Thanks @Emiller88! Are the tests supposed to be failing here?

**Comment by Emiller88** [comment]
They are not! It's not giving me a reason that they failed it just had an "internal error" I kicked them off again and lets see if they work this time around.

**Review by drpatelh — APPROVED** [review]
Thanks alot @Emiller88 ! This is definitely a good start 😎 🎉

**Pull request merged**
