### PR TITLE
Optional output from the VEP-moduel

### LINKED ISSUE #1774: [FEATURE] Optional output from VEP in vcf-, json- or tab-format
### Is your feature request related to a problem? Please describe

As part of the Sarek-project, we would like the VEP-module `ENSEMBLVEP` (`modules/ensemblvep/main.nf`) could be configured to output either a vcf-file, a json-file or a tab-file, c.f. https://github.com/nf-core/sarek/issues/575

### Describe the solution you'd like

The output-file-format is controlled through `task.ext.args` while the output-file-extension is set by `task.ext.args2`. This approach was developed with @maxulysse and @FriederikeHanssen, here: https://github.com/nf-core/sarek/pull/582

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asp8200**
Making the output from the VEP-moduel (ENSEMBLVEP) optionally vcf, json or tab.  Request by user in issue #1774.

Closes #1774 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by nvnieuwk** [comment]
I don't think working with `args2` is the best way to solve this problem, I would suggest making an extra optional input field that defines the output file type (but maybe wait until @maxulysse gives some feedback)

**Comment by lassefolkersen** [comment]
@nvnieuwk the VEP-arguments for file type are `-vcf`, `-json`, `-tab` - defaulting to vcf. So that is currently passed through the `-args`. So it's not `-args2` that handles the actual type. Just the ending.

**Comment by nvnieuwk** [comment]
> 

Yeah but it does seem a bit redundant to that you have to specify the type and the ending on two different locations. `args2` is also mainly used to add arguments for a second tool (can't really find the docs for this right now, sorry). So I think it would be best to add an extra input field called `output_file_type` or something like that with three options: "vcf", "json", or "tab". You can then use this value to fill in the argument (e.g `--${output_file_type}`) and the file extension as `${prefix}.ann.${output_file_type}`. Also this is just a suggestion from me, I think this would be better though, since you only have to specify it once and the user needs to specify it, instead of figuring out how to do it in a config file. :)

**Comment by nvnieuwk** [comment]
> > > 
> > 
> > 
> > Yeah but it does seem a bit redundant that you have to specify the type and the ending on two different locations. `args2` is also mainly used to add arguments for a second tool (can't really find the docs for this right now, sorry). So I think it would be best to add an extra input field called `output_file_type` or something like that with three options: "vcf", "json", or "tab". You can then use this value to fill in the argument (e.g `--${output_file_type}`) and the file extension as `${prefix}.ann.${output_file_type}`. Also this is just a suggestion from me, I think this would be better though, since you only have to specify it once and the user needs to specify it, instead of figuring out how to do it in a config file. :)
> 
> @nvnieuwk : Thanks for your feedback. I basically started out solving this issue in much the same way as you are proposing. However, @maxulysse and, to some degree @FriederikeHanssen, advised me to opt for the solution presented in this draft-PR. I don't have any strong opinions on this - both solutions could work for what I'm trying to do in Sarek ([nf-core/sarek#582](https://github.com/nf-core/sarek/pull/582)). @maxulysse stated that he was happy with the current solution ([nf-core/sarek#582 (comment)](https://github.com/nf-core/sarek/pull/582#issuecomment-1153829628)). I suggest that we wait for input from @maxulysse or @FriederikeHanssen. Cheers

Allright, that's fine by me then :p.

**Comment by FriederikeHanssen** [comment]
> > > > 
> > > 
> > > 
> > > Yeah but it does seem a bit redundant that you have to specify the type and the ending on two different locations. `args2` is also mainly used to add arguments for a second tool (can't really find the docs for this right now, sorry). So I think it would be best to add an extra input field called `output_file_type` or something like that with three options: "vcf", "json", or "tab". You can then use this value to fill in the argument (e.g `--${output_file_type}`) and the file extension as `${prefix}.ann.${output_file_type}`. Also this is just a suggestion from me, I think this would be better though, since you only have to specify it once and the user needs to specify it, instead of figuring out how to do it in a config file. :)
> > 
> > 
> > @nvnieuwk : Thanks for your feedback. I basically started out solving this issue in much the same way as you are proposing. However, @maxulysse and, to some degree @FriederikeHanssen, advised me to opt for the solution presented in this draft-PR. I don't have any strong opinions on this - both solutions could work for what I'm trying to do in Sarek ([nf-core/sarek#582](https://github.com/nf-core/sarek/pull/582)). @maxulysse stated that he was happy with the current solution ([nf-core/sarek#582 (comment)](https://github.com/nf-core/sarek/pull/582#issuecomment-1153829628)). I suggest that we wait for input from @maxulysse or @FriederikeHanssen. Cheers
> 
> Allright, that's fine by me then :p.

Hi @nvnieuwk ! Good points raised. I think this is one of those modules were either solution has some draw backs. I was proposing a solution that would not pass the type as `input` but through the config, in order for pipeline usage to be more adaptable by the user. For example the pipeline generates vcfs, but someone really wants json they can overwrite this in the `modules.config` (which is more or less the paradigm for all modules, only hand over files & meta via input, everything is set by configs). The other problem is, that `prefix` alone is not enough here. It would work fine for the vcf/json/tab output, but the `html` file then has a weird naming scheme. However, you are right that `args2` is usually used for a second tool. Ideally I would want to see `suffix` there, it is the most descriptive of whats going on IMO, but it was sort of retired a while ago, so I was not sure if we can revive it for this one module

**Comment by nvnieuwk** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Yeah but it does seem a bit redundant that you have to specify the type and the ending on two different locations. `args2` is also mainly used to add arguments for a second tool (can't really find the docs for this right now, sorry). So I think it would be best to add an extra input field called `output_file_type` or something like that with three options: "vcf", "json", or "tab". You can then use this value to fill in the argument (e.g `--${output_file_type}`) and the file extension as `${prefix}.ann.${output_file_type}`. Also this is just a suggestion from me, I think this would be better though, since you only have to specify it once and the user needs to specify it, instead of figuring out how to do it in a config file. :)
> > > 
> > > 
> > > @nvnieuwk : Thanks for your feedback. I basically started out solving this issue in much the same way as you are proposing. However, @maxulysse and, to some degree @FriederikeHanssen, advised me to opt for the solution presented in this draft-PR. I don't have any strong opinions on this - both solutions could work for what I'm trying to do in Sarek ([nf-core/sarek#582](https://github.com/nf-core/sarek/pull/582)). @maxulysse stated that he was happy with the current solution ([nf-core/sarek#582 (comment)](https://github.com/nf-core/sarek/pull/582#issuecomment-1153829628)). I suggest that we wait for input from @maxulysse or @FriederikeHanssen. Cheers
> > 
> > 
> > Allright, that's fine by me then :p.
> 
> Hi @nvnieuwk ! Good points raised. I think this is one of those modules were either solution has some draw backs. I was proposing a solution that would not pass the type as `input` but through the config, in order for pipeline usage to be more adaptable by the user. For example the pipeline generates vcfs, but someone really wants json they can overwrite this in the `modules.config` (which is more or less the paradigm for all modules, only hand over files & meta via input, everything is set by configs). The other problem is, that `prefix` alone is not enough here. It would work fine for the vcf/json/tab output, but the `html` file then has a weird naming scheme. However, you are right that `args2` is usually used for a second tool. Ideally I would want to see `suffix` there, it is the most descriptive of whats going on IMO, but it was sort of retired a while ago, so I was not sure if we can revive it for this one module

Yeah I see what you mean! It's a bit of a tricky situation indeed. `suffix` seems like the best solution to this problem indeed IMO. The solution proposed by @asp8200 is maybe a good middle ground for this problem then. Seems like there is no real golden solution for this.

**Review by nvnieuwk — APPROVED** [review]
LGTM!

**Review by nvnieuwk — APPROVED** [review]

**Pull request merged**
