### PR TITLE
Remove AMRFinderPlus DB update on each invocation

### PR DESCRIPTION
**Pull request by oschwengers**
I removed the AMRFinderPlus DB update from the Bakta `main.nf` which seems to be invoked on each execution of Bakta. AMRFinderPlus db should be downloaded and installed automatically and transparently during the Bakta DB download via `bakta_db download` -> https://github.com/oschwengers/bakta/blob/d6443639958750c3bece5822e84978271d1a4dc7/bakta/db.py#L247

Maybe I'm missing something, but if not, this would be a waste of bandwidth and significantly increase wall clock run times.

### CODE REVIEW

**Comment by jfy133** [comment]
I think it was @jasmezz who added this in because the module wasn't working without it IIRC ?

**Comment by jasmezz** [comment]
Yes, the amrfinder update line comes from [here](https://github.com/nf-core/modules/pull/5048) (see also the original bug report in the PR description).
In short: The user had bakta crashing using conda without the amrfinder update line, which I could reproduce. So I wanted to add it for conda-only executions to save resources for non-conda usage. For some reason, bakta started to crash then for the singularity/docker containers as well without the line. Thus, I added it for all.
And now in your PR it seems to work again without the line! I am really confused about this flakiness.
Did you test your changes for conda as well locally?

**Comment by oschwengers** [comment]
This is really interesting/odd. For Bakta we often see issues with AMRFinderPlus that we cannot reproduce or don't know what is causing these.

No, I haven't tested it locally. I just recognized this line and wanted to throw in my 0.02$ as a tool developer that, in principle, this should work w/o this extra invocation of `amrfinder_update`.

**Comment by jasmezz** [comment]
That's alright, thank you! I'd prefer to approve your PR of course. I am investigating the issue locally with conda. Stay tuned, this might take a while.

**Comment by jasmezz** [comment]
I cannot find any errors with removing the line on any of conda/singularity/docker. So let's go ahead with this PR. :+1: 
I did not really find the source from the earlier reported issue which lead to including the line in the first place. Hopefully I get better clues if it ever happens again (which will of course not happen!).

**Review by jasmezz — APPROVED** [review]

**Comment by jasmezz** [comment]
Go ahead and merge @oschwengers :rocket: I need the module asap, so will need to do merge myself if you won't ;)

**Comment by oschwengers** [comment]
Thanks a lot @jasmezz! I'd love to merge this but, unfortunately, I do not have write permissions.

**Pull request merged**
