### PR TITLE
Migrate Space Ranger modules to nf-test

### PR DESCRIPTION
**Pull request by fasterius**
This PR migrates the Space Ranger modules to nf-test from pytest. Modules included are `spaceranger/mkgtf`, `spaceranger/mkref` and `spaceranger/count`.

Feedback regarding assertions is very welcome! In fact, I need help with the `spaceranger/mkref` module's assertions, as I couldn't get it working with the directory it outputs - currently it only asserts success and a snapshot of `versions.yml`, so more are obviously needed.

(Some commits are cherry-picked from #4675 to pass linting.)

### CODE REVIEW

**Comment by grst** [comment]
You can specify subfolders like this:
https://github.com/nf-core/modules/pull/4701/commits/44f27d67df1bdd14296628f3f5dd5515fd0e61ee#diff-37d2e0f021ec9624785aa7f401dedc3713269ba115411a89e26c80a2e3d64f30R32

Does that help? The tests currently seem to fail because `genomeParameters.txt` in the star subfolder doesn't have a stable checksum.

**Comment by fasterius** [comment]
Okay, awesome! How does one extend that to work with finding and excluding files in those subdirectories? Setting it as a path and using `findAll` doesn't seem to work, but I'm probably missing something. 

Sorry, I forgot to mention that it's the `genomeParamater.txt` file that yields unstable checksums.

**Comment by fasterius** [comment]
Ooh wait I think I got it, checking locally.

**Comment by grst** [comment]
I also couldn't resist. 
This seems to work: https://github.com/nf-core/modules/pull/4701/commits/63abb17a50ab529c89542eb3a756ec142c5c02e1

But there are probably other solutions as well.

**Comment by maxulysse** [comment]
> I also couldn't resist. This seems to work: [63abb17](https://github.com/nf-core/modules/commit/63abb17a50ab529c89542eb3a756ec142c5c02e1)
> 
> But there are probably other solutions as well.

I love that

**Comment by grst** [comment]
> So a combination of @grst and the Slack solutions turned out like so: [3420d20](https://github.com/nf-core/modules/commit/3420d2094ba13c601f71ff7e9bb661cae7667acf).

that's even better! Nice!

**Comment by fasterius** [comment]
I think is ready for review and hopefully merging now!

**Review by grst — APPROVED** [review]
LGTM! Thanks @fasterius!

**Pull request merged**
