### PR TITLE
Preserve STDERR

### PR DESCRIPTION
**Pull request by sminot**
I ran into an error which was very hard to debug because I couldn't see the contents of STDERR.

This should preserve STDERR in the logs without altering the set of files which are written out.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by pontus — COMMENTED** [review]
Baring any typos that I've missed, this looks valid and should work. This construct was available in bash 3.2 (base requirement for nextflow) as well it seems.

Whatever it's generally understandable enough to be a good change, I don't have any opinion of.

**Comment by mahesh-panchal** [comment]
This is a really useful change. We should add this to the docs as part of guidance when writing modules.

**Comment by Emiller88** [comment]
Also, I think these failures should be fine if we make an issue to follow up on them, I'd rather not have more scope in this PR for issues that aren't because of it.

**Comment by maxulysse** [comment]
Fixed the linting failures and the nf-test failures, so now I'm ok to merge since only pytests are failing

**Comment by maxulysse** [comment]
@sminot I hope you don't mind I chimed in on your PR

**Comment by sminot** [comment]
Thank you for taking it across the finish line, @maxulysse !

**Comment by maxulysse** [comment]
It was a pressure to collaborate, we should do that more often

**Pull request merged**
