### PR TITLE
fix: wrong stub output files

### PR DESCRIPTION
**Pull request by matq007**
## PR checklist

StarSolo module was generating incorrect test files. The `stub` now matches the `output` wildcards.

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Comment by SPPearce** [comment]
Hi @matq007,
Are you able to address #5863 while you are updating this module?
And this module could also do with swapping to nf-test rather than the pytest as well.

**Review by apeltzer — APPROVED** [review]

**Comment by matq007** [comment]
> Hi @matq007, Are you able to address #5863 while you are updating this module? And this module could also do with swapping to nf-test rather than the pytest as well.

Sure, I can fix the whitelist. Can you point me to a direction about the `nf-test`? I am not familiar with it.

**Comment by mashehu** [comment]
> > Hi @matq007, Are you able to address #5863 while you are updating this module? And this module could also do with swapping to nf-test rather than the pytest as well.
> 
> Sure, I can fix the whitelist. Can you point me to a direction about the `nf-test`? I am not familiar with it.

https://nf-co.re/docs/tutorials/tests_and_test_data/nf-test_writing_tests but `nf-core modules create --migrate-pytest` should get you already a long way

**Comment by matq007** [comment]
```
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── nf-test output ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                                                                                                                                           │
│ 🚀 nf-test 0.9.0                                                                                                                                                                                                                                                                                          │
│ https://www.nf-test.com                                                                                                                                                                                                                                                                                   │
│ (c) 2021 - 2024 Lukas Forer and Sebastian Schoenherr                                                                                                                                                                                                                                                      │
│                                                                                                                                                                                                                                                                                                           │
│ Load .nf-test/plugins/nft-bam/0.3.0/nft-bam-0.3.0.jar                                                                                                                                                                                                                                                     │
│ Warning: Module /Users/fdb589/GitHub/matq007/modules/modules/nf-core/ltrretriever/ltrretriever/tests/main.nf.test: Dependency '/Users/fdb589/GitHub/matq007/modules/modules/nf-core/ltrretriever/ltrretriever/tests/../../../gunzip/main' not found.                                                      │
│ Warning: Module /Users/fdb589/GitHub/matq007/modules/modules/nf-core/ltrfinder/tests/main.nf.test: Dependency '/Users/fdb589/GitHub/matq007/modules/modules/nf-core/ltrfinder/tests/../../gunzip/main' not found.                                                                                         │
│                                                                                                                                                                                                                                                                                                           │
│ Test Process STAR_STARSOLO                                                                                                                                                                                                                                                                                │
│                                                                                                                                                                                                                                                                                                           │
│   Test [6c67d245] 'homo_sapiens - CB_UMI_Simple' PASSED (17.699s)                                                                                                                                                                                                                                         │
│   Test [d209817d] 'homo_sapiens - CB_UMI_Simple - stub' PASSED (5.373s)                                                                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                                                                           │
│                                                                                                                                                                                                                                                                                                           │
│ SUCCESS: Executed 2 tests in 23.166s                                                                                                                                                                                                                                                                      │
│                                                                                                                                                                                                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
INFO     All tests passed!
```

Ok, the stuff is working for me locally, soo can we merge?

**Comment by SPPearce** [comment]
Hmm,
I'm not quite sure what is going on.
Opening on gitpod, we get a very consistent md5sum of `84d031c3083ae44cfa1984733b4875b7`, with the content of the file:

> Number of Reads,10000
> Reads With Valid Barcodes,1
> Sequencing Saturation,0.111111
> Q30 Bases in CB+UMI,-nan
> Q30 Bases in RNA read,0.951199
> Reads Mapped to Genome: Unique+Multiple,0.0089
> Reads Mapped to Genome: Unique,0.0047
> Reads Mapped to Gene: Unique+Multiple Gene,NoMulti
> Reads Mapped to Gene: Unique Gene,0.0009
> Estimated Number of Cells,8
> Unique Reads in Cells Mapped to Gene,9
> Fraction of Unique Reads in Cells,1
> Mean Reads per Cell,1
> Median Reads per Cell,1
> UMIs in Cells,8
> Mean UMI per Cell,1
> Median UMI per Cell,1
> Mean Gene per Cell,1
> Median Gene per Cell,1
> Total Gene Detected,2

But you seem to be getting a different md5sum that is consistent for you? No obvious reason that this file would vary, no timestamps or file paths.
I've just pushed this md5sum, will see what the tests do, but would be interested to see what is different.

**Comment by SPPearce** [comment]
So that seems consistent on here/gitpod, what does the Summary.csv file look like for you locally?

**Comment by matq007** [comment]
> So that seems consistent on here/gitpod, what does the Summary.csv file look like for you locally?

For me the summary is "Summary.csv:md5,8b43bfcfcfdfb48d0cd70e78429d0311"

**Comment by matq007** [comment]
I have two hashes `6c67d245768281b8b832913e3b7505e` and `d209817de1f4e6d6dc9b1887c94db9fc`

**Pull request merged**
