### PR TITLE
add adam/markduplicates

### PR DESCRIPTION
**Pull request by heuermh**
WIP, currently failing Docker tests due to issues with `-u $(id -u):$(id -g)` specified in `docker.runOptions`

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] 
- [ ] Emit the `<SOFTWARE>.version.txt` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by heuermh** [comment]
Rebased to re-run CI tests; may still fail due to #315

**Comment by heuermh** [comment]
Now that all the tests pass here, what should we do about `-u $(id -u):$(id -g)` specified in `docker.runOptions`?  This pull request includes a commit to remove it.

I'll try to roll back this and some other intermediate changes to see if they are strictly necessary.

**Comment by heuermh** [comment]
Switched to using `docker.userEmulation` as in #525

**Comment by matthdsm** [comment]
Hi there!

We've noticed there hasn't been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we'll close your PR in about 2 weeks

Cheers
the nf-core maintainers

**Pull request closed without merging**
