### PR TITLE
Pbtk bam2fastq

### PR DESCRIPTION
**Pull request by mbeavitt**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

This module replaces the deprecated bam2fastx toolkit version of bam2fastq. It converts PacBio BAM files into fastq.gz.

### CODE REVIEW

**Review by mahesh-panchal — COMMENTED** [review]
Please update your version of nf-core tools. This is using an older format. Tests are now written using pytest, and the conda directive points to an environment.yml.

**Comment by mbeavitt** [comment]
Oh no!

Sorry for that oversight.
Will do!

**Comment by SPPearce** [comment]
Do you plan on finishing this off @mbeavitt ? If you run `nf-core modules create pbtk/bam2fastq --migrate-pytest` it will generate the skeleton of the nf-test files for you to swap to. Should be straightforward in this case. 
I would suggest that you also depreciate bam2fastx in the same PR, the method we have for that is [now detailed here](https://nf-co.re/docs/contributing/modules#deprecating-a-module).

**Comment by SPPearce** [comment]
Bump for @mbeavitt

**Comment by mbeavitt** [comment]
Apologies, this slipped my mind. I'll try and get back to it.

**Comment by GallVp** [comment]
Hi @mbeavitt , @SPPearce , @mahesh-panchal 

I have continued this work on https://github.com/nf-core/modules/pull/5816 by adding nf-test

**Comment by mahesh-panchal** [comment]
Nice work. And thank you for including Michael as commit co-author too.

**Comment by SPPearce** [comment]
Completed in #5816

**Pull request closed without merging**
