### PR TITLE
2551 add possibility for pon creation to cnvkitbatch

### LINKED ISSUE #2551: Add possibility for pon creation to `cnvkit/batch`
### Is your feature request related to a problem? Please describe

`cnvkit batch` also allows for the generation of a panel of normals (pon) which is currently not possible to create. I would like this functionalty added.

### Describe the solution you'd like

Adding a boolean to enable pon generation and combine the files from the input channel into a string.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marrip**
## PR checklist

Introduce a bool `panel_of_normals` to enable the generation of a panel of normals with cnvkit.

Closes #2551 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] Follow the naming conventions.
- [x] Follow the input/output options guidelines.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by maxulysse** [comment]
@nf-core-bot fix linting :pray:

**Comment by maxulysse** [comment]
I'll need to check out the code locally and try to reproduce the issue, but I think we're close

**Comment by marrip** [comment]
@maxulysse any news on cnvkit?

**Review by nvnieuwk — COMMENTED** [review]
You can just add this through the configuration file in your pipeline. This doesn't add any new files. You can access all variables from inside the configuration. (I see @maxulysse has no problem with it so I must be overlooking something probably :grin: )

**Pull request closed without merging**
