### PR TITLE
Change proteus

### PR DESCRIPTION
**Pull request by WackerO**
After some discussion with a colleague of mine, I changed the proteus module to only accept 1 normalization function per run to make it easier to integrate into pipelines. Also, the input channels have been reduced to 1 channel and the tag updated to ensure the module is run the correct number of times (once per contrast). Some params have been renamed.

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by jonasscheid — CHANGES_REQUESTED** [review]
Add MIT license to the R script, else LGTM

**Comment by WackerO** [comment]
@jonasscheid it is already present in the R script :)
https://github.com/nf-core/modules/pull/3898/files#diff-d30d2bf48eb8d801e435480a7202ab468f4e5c770a9ec3c87b7471bbb5a0ff9eL1

**Comment by jonasscheid** [comment]
Oh sorry, somehow GitHub did not show this on review mode!

**Review by jonasscheid — APPROVED** [review]

**Comment by WackerO** [comment]
Thanks very much for the review!

**Pull request merged**
