### PR TITLE
Update mOTUs modules version

### PR DESCRIPTION
**Pull request by jfy133**
- Updates mOTUs to 3.0.3
- Also now has a single reporting system with `--version` so we can use this across all modules 

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by Midnighter — APPROVED** [review]
Changes look good to me. I'm not sure why the tests are failing. That should be solved, of course.

**Review by nvnieuwk — APPROVED** [review]
LGTM

**Review by nvnieuwk — CHANGES_REQUESTED** [review]
Something seems wrong with the versions

**Comment by jfy133** [comment]
Fixed it now (mOTUs bioconda packaing is tricksy :roll_eyes: ), conda is due to slight variability but I think we can ignore

**Review by nvnieuwk — APPROVED** [review]
LGTM!!!

**Comment by jfy133** [comment]
Further flakiness of conda, I'm going to merge anyway (as the atabase downloading takes such a long tme)

**Pull request merged**
