### PR TITLE
Unpin nft-bam

### PR DESCRIPTION
**Pull request by nvnieuwk**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]
Unpinning scares me, but I'll allow it for now as you're just testing

**Comment by nvnieuwk** [comment]
> Unpinning scares me, but I'll allow it for now as you're just testing

Yeah I'll repin it in the future, but this is a quick and dirty fix to the CI issues :)

**Comment by nvnieuwk** [comment]
Not sure what's going on with editorconfig though

**Comment by nvnieuwk** [comment]
Well seems like unpinning isn't even supported :grin: 

```
Error: Syntax errors in nf-test config file: java.lang.RuntimeException: Please specify a version. Latest is not yet supported.
```

**Comment by nvnieuwk** [comment]
Closing this as it's never going to work, let's just wait until they merge https://github.com/askimed/nf-test-plugins/pull/4 in

**Pull request closed without merging**
