### PR TITLE
Fix fail on CAT_FASTQ receiving single file

### LINKED ISSUE #1670: [BUG] `CAT_FASTQ` fails when passed a single file
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

The module `CAT_FASTQ` will fail due to either no script block or no output when passed a sample channel with a single file.

This looks to be because there is no fallback in the script blocks to handle these single-file cases, so an empty script is executed, combined with the weirdness that comes from file paths being iterable in Groovy :angry:.

### Command used and terminal output

```console
$ printf "repository_type: pipeline" > .nf-core.yml
$ mkdir modules
$ wget -q https://github.com/nf-core/test-datasets/raw/modules/data/genomics/sarscov2/illumina/fastq/test_1.fastq.gz
$ wget -q https://github.com/nf-core/test-datasets/raw/modules/data/genomics/sarscov2/illumina/fastq/test_2.fastq.gz
$ wget -q https://github.com/nf-core/test-datasets/raw/modules/data/genomics/sarscov2/nanopore/fastq/test.fastq.gz
$ cat <<-NFSCRIPT > main.nf
#!/usr/bin/env nextflow
include { CAT_FASTQ } from './modules/nf-core/modules/cat/fastq/main'
workflow se {
    Channel
        .fromPath('test.fastq.gz')
        .map{ [[id: 'se-test', single_end: true], it] }
        .set{ ch_reads }
    CAT_FASTQ(ch_reads)
}

workflow pe {
    Channel
        .fromFilePairs('test_{1,2}.fastq.gz')
        .map{ [[id: 'pe-test', single_end: false], it[1]] }
        .set{ ch_reads }
     CAT_FASTQ(ch_reads)
}
NFSCRIPT
$ nf-core modules install cat/fastq
                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.4.1 - https://nf-co.re


INFO     Creating missing 'module.json' file.                                                                        modules_command.py:107
INFO     Installing 'cat/fastq'                                                                                              install.py:126
INFO     Downloaded 2 files to ./modules/nf-core/modules/cat/fastq                                                   modules_command.py:273
INFO     Include statement: include { CAT_FASTQ } from '../modules/nf-core/modules/cat/fastq/main’                           install.py:135
$ nextflow run -entry se main.nf
N E X T F L O W  ~  version 22.04.0
Launching `main.nf` [evil_wescoff] DSL2 - revision: 2e58c8ab93
WARN: Access to undefined parameter `enable_conda` -- Initialise it to a default value eg. `params.enable_conda = some_value`
executor >  local (1)
[fd/0dca34] process > se:CAT_FASTQ (se-test) [100%] 1 of 1, failed: 1 ✘
Error executing process > 'se:CAT_FASTQ (se-test)'

Caused by:
  Process `se:CAT_FASTQ (se-test)` terminated with an error exit status (1)

Command executed:

  cat input1 test.fastq.gz > se-test.merged.fastq.gz
  
  cat <<-END_VERSIONS > versions.yml
  "se:CAT_FASTQ":
      cat: $(echo $(cat --version 2>&1) | sed 's/^.*coreutils) //; s/ .*$//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  cat: input1: Is a directory
  cat: test.fastq.gz: No such file or directory

Work dir:
  /home/tchristensen/src/cat-cat-mwe/work/fd/0dca34857e9dfe027924a9f865bcdd

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
$ nextflow run -entry pe main.nf
N E X T F L O W  ~  version 22.04.0
Launching `main.nf` [jovial_mccarthy] DSL2 - revision: 2e58c8ab93
WARN: Access to undefined parameter `enable_conda` -- Initialise it to a default value eg. `params.enable_conda = some_value`
executor >  local (1)
[ea/b337ea] process > pe:CAT_FASTQ (pe-test) [100%] 1 of 1, failed: 1 ✘
Error executing process > 'pe:CAT_FASTQ (pe-test)'

Caused by:
  Process `pe:CAT_FASTQ (pe-test)` terminated with an error exit status (127)

Command executed:

  null

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: null: command not found

Work dir:
  /home/tchristensen/src/cat-cat-mwe/work/ea/b337ea8e28272adcef62a03deace97

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Relevant files

[CAT_FASTQ-mwe.zip](https://github.com/nf-core/modules/files/8703608/CAT_FASTQ-mwe.zip)

### System information

Nextflow version: 21.04.0
Hardware: Desktop
Executor: local
Container engine: none
OS: Fedora 35

### PR DESCRIPTION
**Pull request by MillironX**
## PR checklist

Closes #1670 

Fixes the bug where CAT_FASTQ would fail upon receiving a single file or single pair of files.

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [na] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [na] If necessary, include test data in your PR.
- [na] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [na] Add a resource `label`
- [na] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by drpatelh** [comment]
Thanks @MillironX ! This module was intentionally not supposed to handle single FastQ files. The channels should be filtered beforehand like [here](https://github.com/nf-core/rnaseq/blob/e0dfce9af5c2299bcc2b8a74b6559ce055965455/workflows/rnaseq.nf#L203) to save running an additional containerised process. What am I missing?

**Comment by Emiller88** [comment]
It might be an easier out of the box to handle single or paired to play devil's advocate.

@MillironX could we maybe add a check that it's not single end, or check there's more than one file, and fail otherwise? Then we could link to the pattern in the error message.

**Comment by drpatelh** [comment]
> It might be an easier out of the box to handle single or paired to play devil's advocate.

The module does this already by relying on `meta.single_end` value?

**Comment by MillironX** [comment]
> This module was intentionally not supposed to handle single FastQ files ...  to save running an additional containerised process

Ok, @drpatelh, I can see the reasoning there, but I think we at least need a better solution than creating a script block of `null`, which is what happens currently. My preferred method would be to process the reads, but complain about it with a warning, e.g.

```nextflow
log.warn """\
    CAT_FASTQ is intended for multiple files and consumes unnecessary resources when
    called for single files/single pairs. Please use a channel filter operator to remove single
    files before calling the process.
    See https://github.com/nf-core/rnaseq/blob/3.7/workflows/rnaseq.nf#L203 for an
    example."""
```

I think that's what @Emiller88 was referring to?

**Comment by drpatelh** [comment]
Yes, makes sense. It would be great to exit if:

`meta.single_end == true and 1 file is supplied` or `meta.single_end == false and 2 files are supplied`.

An exit sounds better here rather than a warn no given that this could break the pipeline downstream? 

Thanks @MillironX !

**Comment by Emiller88** [comment]
> I think that's what @Emiller88 was referring to?

Yep exactly!

Trying to prevent this

> The module does this already by relying on meta.single_end value?

And then we repeat the explanation, and we answer this question over and over again because we think it should be common knowledge. Now it'll be common knowledge!

> An exit sounds better here rather than a warn no given that this could break the pipeline downstream?

Yeah, I was expecting it to exit as well.

**Comment by MillironX** [comment]
I am closing this PR. I have not found a consistent way to find single files and fail them gracefully thanks to Groovy files being iterable.

**Pull request closed without merging**
