### PR TITLE
Update comments with new style

### LINKED ISSUE #493: Update comment style on functions.nf and test main.nf
The style of the comments has been updated on the `rnaseq` and the `viralrecon` DSL2 pipelines  after adding the `EditorConfig` `Actions` see [here](https://github.com/nf-core/rnaseq/pull/629) and [here](https://github.com/nf-core/viralrecon/pull/188), respectively. On this way all the `.{nf,groovy,conf}` files have the comment style shown below:

```bash
//
// My awesome comment here
//
```

Also, `nf-core modules create` command will be updated to be consistent with the comment style above, see [here](https://github.com/nf-core/tools/issues/1076).
All the current comments on `functions.nf` need to be updated and the `main.nf` of each module test should be updated accordingly.

### PR DESCRIPTION
**Pull request by JoseEspinosa**
As explained on this issue #493 comment style has been updated.

## PR checklist

Closes #493 

- [x] This comment contains a description of changes (with reason).

### CODE REVIEW

**Comment by JoseEspinosa** [comment]
I detected that three modules did not have the functions updated to the latest version:

* `gatk4/intervallisttools`
* `kallistobustools/count`
* `stringtie/merge`

Is there any reason not to update the functions.nf on these modules @drpatelh ?

**Comment by drpatelh** [comment]
Nope. I saw that too. I am still wondering why you have `188` files changed and I only have `175` in my PR https://github.com/nf-core/modules/pull/496

**Comment by drpatelh** [comment]
Ah, you updated the test files too!

**Review by drpatelh — APPROVED** [review]
LGTM!

**Pull request merged**
