### PR TITLE
Cellranger arc module

### PR DESCRIPTION
**Pull request by heylf**
## PR checklist

Closes #XXX 

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by heylf** [comment]
Current version of the cellranger-arc modules. It is missing some test data. Furthermore, I will check currently the correct naming conventions.

**Comment by heylf** [comment]
Modules need the test data which is here: https://github.com/nf-core/test-datasets/pull/895

**Comment by heylf** [comment]
Still also discussion regarding docker images

**Comment by Joaodemeirelles** [comment]
@heylf , any reason why you closed it? How did you thought on working with the container?

**Comment by heylf** [comment]
@Joaodemeirelles sorry I did back then a mistake with my repo. New PR is here: https://github.com/nf-core/modules/pull/3576. I will push for the modules in the next days.

**Pull request closed without merging**
