### PR TITLE
feat: add parabricks/deepvariant

### PR DESCRIPTION
**Pull request by bsiranosian**
## PR checklist

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [X] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by sateeshperi** [comment]
is excluding conda from GHA the best way forward for this module ? any idea what's the issue with conda failing ?

**Comment by bsiranosian** [comment]
@sateeshperi these tools are only available as a container.

**Comment by sateeshperi** [comment]
oh i see...no worries then....can i request you to kindly explore creating nf-test for this module...as we are migrating away from pytest
https://nf-co.re/docs/contributing/modules#migrating-from-pytest-to-nf-test

**Comment by maxulysse** [comment]
> oh i see...no worries then....can i request you to kindly explore creating nf-test for this module...as we are migrating away from pytest https://nf-co.re/docs/contributing/modules#migrating-from-pytest-to-nf-test

We can't have nf-tests yet as accelerator is not working currently with nf-test

**Pull request merged**
