### PR TITLE
add subworkflow: fastq_align

### LINKED ISSUE #2161: new subworkflow gatk4/mapping

### PR DESCRIPTION
**Pull request by matthdsm**
Closes #2161

ping @maxulysse 

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by Emiller88** [comment]
This is interesting. 
Two options we could go here:
1. subworkflow for each individual aligner (`ailgn_bowtie`, `align_star`, etc.)
2. This unified subworkflow. @maxulysse pointed out we might name these (`fastq_align_dna` and `fastq_align_rna`).

I think the question to answer is, "In what case should a user reach for a subworkflow, over just importing the module themselves."

**Comment by matthdsm** [comment]
I don't see much value in having a subwf for a single aligner, as that just amounts to calling the module. User could have some custom functions etc in their subwf, but since we're going for lowest common denominator here, we can't assume anything and have to keep thing barebone

**Comment by matthdsm** [comment]
A "unified" workflow, whatever the name is/will be is a plus for pipeline developers who want to add in extra flexibility without having to do extra work

**Comment by matthdsm** [comment]
> A "unified" workflow, whatever the name is/will be is a plus for pipeline developers who want to add in extra flexibility without having to do extra work

This wil also avoid code duplication across the interwebs, cfr what Maxime has in Sarek and what we have in our preprocessing workflow

**Comment by maxulysse** [comment]
I love the idea of using a case switch

**Comment by matthdsm** [comment]
> I love the idea of using a case switch
Courtesy of Github Copilot 😅

**Comment by matthdsm** [comment]
Feel free add a review and/or hit merge when you're done discussing!

**Review by Emiller88 — APPROVED** [review]
> I don't see much value in having a subwf for a single aligner, as that just amounts to calling the module. User could have some custom functions etc in their subwf, but since we're going for lowest common denominator here, we can't assume anything and have to keep thing barebone

I think we've landed on that there's benefit to both for now. 

The "atomic" subworkflows are useful for common tasks(`fastqc_umitools_trimgalore` and `align_star` that has the two samtools workflows following it). 

There's also a lot of benefit in workflows like this one that just handle all the possible options out of the box. 

I think we'll get a better feel for what the requirements of a subworkflow are as we start adding more subworkflows. We just need to be keep discussing and asking whether they make sense for overall maintainability for now!

**Comment by matthdsm** [comment]
So we're good to merge?

**Comment by Emiller88** [comment]
Yep!

**Comment by maxulysse** [comment]
I'll try adding that in Sarek as soon as I'm done with my current PR

**Pull request merged**
