### PR TITLE
bump samtools

### PR DESCRIPTION
**Pull request by matthdsm**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by matthdsm** [comment]
I know...
Nothing a little for-loop can't handle!

**Comment by matthdsm** [comment]
conda!! 😠

**Comment by famosab** [comment]
It is only the pytest ones that are failing, right? Maybe just move the tests to nf-test.

**Comment by SPPearce** [comment]
> It is only the pytest ones that are failing, right? Maybe just move the tests to nf-test. (samtools/markdup, samtools/reheader) Edit: and the one for bam_stats_samtools (subworkflow)

They both look pretty simple to swap to nf-test, I'll try and fit it in later if nobody has done before then. Although I don't know why markdup is currently using samtools collate first, that seems unnecessary.

**Review by sateeshperi — APPROVED** [review]

**Pull request merged**
