### PR TITLE
Adding stubs to frequently used modules

### LINKED ISSUE #3553: [FEATURE] Adding Stubs to 22 modules
### Is your feature request related to a problem? Please describe

I'm trying to run testing on our pipeline but a number of modules do not have stub sections.

### Describe the solution you'd like

Addition of stubs.

### Describe alternatives you've considered

_No response_

### Additional context

I've added stubs to 22 of the modules we use.

### PR DESCRIPTION
**Pull request by DLBPointon**
## PR checklist

Closes #3553 

- [X] This comment contains a description of changes (with reason).
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.

I've added stubs to 22 modules, as they were causing an issue during local testing of my pipelines.

### CODE REVIEW

**Comment by DLBPointon** [comment]
I have now realised it was a mistake to make so many changes at the same time, apologies!

**Comment by SPPearce** [comment]
The vast majority of the fails are the linting test, checking the keywords used to describe the modules and the input/output file types. As you are using these modules yourself, you presumably know what they do so you are ideal to add some more keywords to describe them.
There are a few modules where conda is failing but docker/singularity are passing, sometimes this is due to conda having different file paths than docker/singularity. But the `cooler` modules it appears to be an issue more generally.

**Comment by DLBPointon** [comment]
Confirmed that conda is making different files when comparing conda to container. I don't know why.

**Comment by muffato** [comment]
> Confirmed that conda is making different files when comparing conda to container. I don't know why.

What file types are concerned ? That's typical (if not systematic !) for BAM files and can usually be safely ignored as the `samtools view` version of those BAM is usually identical.

**Comment by DLBPointon** [comment]
> > Confirmed that conda is making different files when comparing conda to container. I don't know why.
> 
> What file types are concerned ? That's typical (if not systematic !) for BAM files and can usually be safely ignored as the `samtools view` version of those BAM is usually identical.

I didn't know that, why does that happen are they storing information on how they were made?

The files at hand are:
PreText -> BAM, CRAM and BED all being converted into pretext file
Cooler -> cool file for merge and zoomify, bed files for cload

**Comment by muffato** [comment]
Thanks for your latest commits, @DLBPointon . You already addressed most of the test failures. I looked into the remaining ones.

1. I've pushed a small change in `samtools/markdup/meta.yml` to fix the linting error (it appears nf-core mandates 3 keywords per tool).

2. The Cooler errors are caused by a breaking API change introduced in Pandas 2.0: https://stackoverflow.com/questions/76234312/importerror-cannot-import-name-is-categorical-from-pandas-api-types
Cooler have fixed that in version 0.9.0 (cf https://github.com/open2c/cooler/commit/b3262bce9f7c2d6b9d64cadf6976cbde6532d8ff) but the nf-core module still uses 0.8.11. I can see two solutions:
   - bump all the cooler modules to use the latest version (0.9.2). I don't know how much Cooler has changed and if it'll break some nf-core modules / tests.
   - pin the version of pandas to pre-2.0 like this (in all Cooler modules)

     ```diff
     --- a/modules/nf-core/cooler/cload/main.nf
     +++ b/modules/nf-core/cooler/cload/main.nf
     @@ -2,7 +2,7 @@ process COOLER_CLOAD {
          tag "$meta.id"
          label 'process_high'
 
     -    conda "bioconda::cooler=0.8.11"
     +    conda "bioconda::cooler=0.8.11 'conda-forge::pandas<2'"
          container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
              'https://depot.galaxyproject.org/singularity/cooler:0.8.11--pyh3252c3a_0' :
              'biocontainers/cooler:0.8.11--pyh3252c3a_0' }"
     ```

3. The pretextmap error is caused by pretextmap 0.1.9 having been recompiled on bioconda and now outputting something different binary-wise (I can't tell if the files are functionally equivalent). But if I pin the build number to the build used when the tests were written and the mulled container built, the tests pass locally.

     ```diff
     --- a/modules/nf-core/pretextmap/main.nf
     +++ b/modules/nf-core/pretextmap/main.nf
     @@ -3,7 +3,7 @@ process PRETEXTMAP {
          tag "$meta.id"
          label 'process_single'
 
     -    conda "bioconda::pretextmap=0.1.9 bioconda::samtools=1.16.1"
     +    conda "bioconda::pretextmap=0.1.9=h9f5acd7_1 bioconda::samtools=1.16.1"
          container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
              'https://depot.galaxyproject.org/singularity/mulled-v2-f3591ce8609c7b3b33e5715333200aa5c163aa61:c6242a6c1a522137de7a9e9ff90779ede11cf5c5-0':
              'biocontainers/mulled-v2-f3591ce8609c7b3b33e5715333200aa5c163aa61:c6242a6c1a522137de7a9e9ff90779ede11cf5c5-0' }"
     ```
     So two options here too:
     - someone checks the output files created by the latest Conda build of pretextmap 0.1.9 and confirms the files are OK.
     - pin the build number
 
I'll let you decide how to proceed with 2 and 3.

**Comment by DLBPointon** [comment]
Thanks for investigating @muffato.

> 2. The Cooler errors are caused by a breaking API change introduced in Pandas 2.0: https://stackoverflow.com/questions/76234312/importerror-cannot-import-name-is-categorical-from-pandas-api-types
>    Cooler have fixed that in version 0.9.0 (cf [open2c/cooler@b3262bc](https://github.com/open2c/cooler/commit/b3262bce9f7c2d6b9d64cadf6976cbde6532d8ff)) but the nf-core module still uses 0.8.11. I can see two solutions:
>    
>    * bump all the cooler modules to use the latest version (0.9.2). I don't know how much Cooler has changed and if it'll break some nf-core modules / tests.
>    * pin the version of pandas to pre-2.0 like this (in all Cooler modules)
>

I'll bump it up and test it today, the API change is actually linked to some occasional failed runs we've seen so should make things more consistent for us.

> 3. The pretextmap error is caused by pretextmap 0.1.9 having been recompiled on bioconda and now outputting something different binary-wise (I can't tell if the files are functionally equivalent). But if I pin the build number to the build used when the tests were written and the mulled container built, the tests pass locally.
>      
>    So two options here too:
>    
>    * someone checks the output files created by the latest Conda build of pretextmap 0.1.9 and confirms the files are OK.
>    * pin the build number
> 
> I'll let you decide how to proceed with 2 and 3.

I'll have a look at the maps, and get one of the curators to have a look too. If there is a difference i'll pin the version.

**Comment by DLBPointon** [comment]
Pretext test data results in no contact map, I have a nematode dataset I can use though

**Comment by DLBPointon** [comment]
Huzzah!

**Review by muffato — APPROVED** [review]

**Pull request merged**
