### PR TITLE
use underscores in anchors and references

### PR DESCRIPTION
**Pull request by rpetit3**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

The current implementation of `pytest_modules.yml` isn't valid YAML according to `pyyaml` (others are ok with it). This PR attempts to make it valid so play nicely with `nf-core/tools`, specifically the `modules create` command

### CODE REVIEW

**Comment by rpetit3** [comment]
@Emiller88 what's the recommended way to trigger a subworkflow run?

**Comment by Emiller88** [comment]
I'd just make a dummy change in the one you want to test and then it should kick them off!

**Comment by rpetit3** [comment]
Haha that's what I thought, did it for the GATK subworkflow.

**Review by grst — APPROVED** [review]
I guess that should be alright.

**Review by drpatelh — APPROVED** [review]
LGTM! Thanks @rpetit3

**Pull request merged**
