### PR TITLE
Update main.nf

### PR DESCRIPTION
**Pull request by amizeranschi**
Should fix https://github.com/nf-core/funcscan/issues/426

### CODE REVIEW

**Review by mahesh-panchal — COMMENTED** [review]
This particular change is fine, but please get the tests to work by updating the test snapshots.

```
nf-core modules test rgi/main --profile <docker/singularity/conda> --update
```

**Comment by jasmezz** [comment]
I updated the snapshot and tests are succeeding locally. :heavy_check_mark: 

Why they don't here on GHA: because the `untar` module (as part of the main.nf.test file) uses ubuntu version 22.04. A previous module version used 20.04 with which all tests succeeded back then and still do now if I change the version back to 20.04 locally. This problem was reported and discussed already in June (see Slack convo [here](https://nfcore.slack.com/archives/CE6SDBX2A/p1721383758877249)), but not fixed yet, apparently.
Would you @mahesh-panchal be fine with merging this PR incl. failing tests when I assure that tests are fine locally? I attached screenshots in the Slack convo. This PR does not interfere with any of this anyway, it just wants to fix a typo in a variable :grimacing:

**Review by mahesh-panchal — DISMISSED** [review]
Linking related https://github.com/nf-core/modules/issues/5971 and https://github.com/nf-core/modules/issues/5968. 
@maxulysse What's the plan on implementing this unified container?

**Comment by maxulysse** [comment]
is `quay.io/nf-core/coreutils_grep_gzip_lbzip2_pruned:10736d98b4d693d8` working as expecting (ie containing the missing lib)?

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
