### PR TITLE
fix tiny bug in gawk module

### PR DESCRIPTION
**Pull request by MariekeVromman**
adds missing brackets

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Review by nvnieuwk — APPROVED** [review]
LGTM if tests pass :rocket:

**Comment by MariekeVromman** [comment]
linting is failing due to the license

```
The meta.yml of the module gawk is not valid: 
Licence must be an array of one or more entries, e.g. ["MIT"]
Check the entry for tools.
The current value is ['GPL v3'].
```

@mashehu , @nvnieuwk , how do I know which values are allowed here? I tried looking in the docs but did not immediately find it. According to this [site](https://www.gnu.org/software/gawk/manual/gawk.html), gawk falls under the GNU license, but I don't know if 'GNU' is ok for this field. Or maybe 'GLP' without the version...?

**Comment by nvnieuwk** [comment]
You should change the `licence: "['GPL v3']"` to `licence: ['GPL v3']`. That's an artifact from the older tools versions that has been removed (@mashehu can probably go into more detail on the why)

**Comment by MariekeVromman** [comment]
Sooo, the tests were all passing, and I added the PR to the merge queue, but then the docker test started failing (looks like it can not pull the image?).
I don't really know how to go forward now 😅
@nvnieuwk , @mashehu , could you point me to the next steps? Thanks a lot!

**Comment by mashehu** [comment]
You unfortunately hit one of the wonky API call limits, or as @apeltzer put it on #nf-core-memes:
image

The Solution: rerun the failed job and hope that your API call gets through 🤞🏻

**Comment by MariekeVromman** [comment]
thanks a lot!

**Pull request merged**
