### PR TITLE
New subworkflow: Bam dedup stats samtools umicollapse

### LINKED ISSUE #5184: new subworkflow: umicollapse dedup, index BAM file and run samtools stats, flagstat and idxstats
### Is there an existing subworkflow for this?

- [X] I have searched for the existing subworkflow

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this subworkflow, I added myself to the `Assignees` to facilitate tracking who is working on the subworkflow

### PR DESCRIPTION
**Pull request by MatthiasZepper**
This PR proposes the addition of the `bam_dedup_stats_samtools_umicollapse` subworkflow. It is closely modelled after the [`bam_dedup_stats_samtools_umitools`](https://nf-co.re/subworkflows/bam_dedup_stats_samtools_umitools) and essentially copies most if its code - minus one input channel, plus one additional output channel. 

It is meant as an alternative/drop-in replacement of the former to use the more performant tool `umicollapse` instead of `umi-tools`. 

Regarding the tests I am unfortunately in a Catch22 situation: nf-tests do not run on my local machine and also not on Gitpod. They seem to work on the Github runner, but I can't update the snapshot to reflect the latest changes.

## PR checklist

Closes #5184

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
 (**_Only on the Github runners, it neither works on Gitpod nor on my local machine. So best to double check!!_**)
  - For subworkflows:
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by SPPearce** [comment]
I think this should be called `bam_dedup_umicollapse`

**Comment by SPPearce** [comment]
The code looks fine, but I disagree with the name. I also disagree with the name of [bam_dedup_stats_samtools_umitools](https://nf-co.re/subworkflows/bam_dedup_stats_samtools_umitools) , neither of them should have samtools in the name.

**Comment by MatthiasZepper** [comment]
> The code looks fine, but I disagree with the name. I also disagree with the name of [bam_dedup_stats_samtools_umitools](https://nf-co.re/subworkflows/bam_dedup_stats_samtools_umitools) , neither of them should have samtools in the name.

I have no hard opinion on the name and indeed chose it in analogy to the existing [bam_dedup_stats_samtools_umitools](https://nf-co.re/subworkflows/bam_dedup_stats_samtools_umitools), to which it should be essentially a drop-in replacement. I guess the samtools part of the name is mainly contained due to the indexing step?

**Comment by SPPearce** [comment]
Yeah, I assumed you'd just copied the name format from the other subworkflow.

**Review by SPPearce — APPROVED** [review]
Still think the name wants changing, but the code is fine ;)

**Pull request merged**
