### PR TITLE
Update Unicycler Version

### PR DESCRIPTION
**Pull request by DSchreyer**
I updated the unicycler version as it incorporates new functionalities.

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by SPPearce** [comment]
I deleted the tests for ampliconarchitect, but you seem to have lost the version bump for unicycler you were trying to add.

**Comment by DSchreyer** [comment]
> 

@SPPearce did you manage to fix the errors or is there something I can do ? I tried to update the unicycler but let it rest after I could not figure out what is wrong.

**Comment by SPPearce** [comment]
In your [initial commit](https://github.com/nf-core/modules/pull/1699/commits/8b47a3b1dd6137a7198da372a22e1c05a0beb43e), you modified the modules/unicycler/main.nf file. But then in a later commit you overwrote the file by a [new module skeleton](https://github.com/nf-core/modules/pull/1699/commits/66d7f26e47a932ab111a6d92fb4511cb6922de33#diff-7a10f364c0d3e39236d7181e7007cfc6077c29b1df42e05b322bf8faa3554d4d). You reverted that later, back to the original file, not the modified one.

So at the moment this PR doesn't actually contain the update you were trying to apply.

**Comment by matthdsm** [comment]
Hi there!

We've noticed there hasn't been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we'll close your PR in about 2 weeks

Cheers
the nf-core maintainers

**Comment by DSchreyer** [comment]
Hi,
Sorry  I will close the PR myself. I don’t plan to update it in the near future. If so, I open a new PR

From: Matthias De Smet ***@***.***>
Date: Tuesday, 7 March 2023 at 08:50
To: nf-core/modules ***@***.***>
Cc: Daniel Schreyer (PGR) ***@***.***>, Author ***@***.***>
Subject: Re: [nf-core/modules] Update Unicycler Version (PR #1699)

Hi there!

We've noticed there hasn't been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we'll close your PR in about 2 weeks

Cheers
the nf-core maintainers

**Comment by matthdsm** [comment]
Thank you for the quick reply!

**Pull request closed without merging**
