### PR TITLE
add amrfinderplus module

### PR DESCRIPTION
**Pull request by rpetit3**
## PR checklist

Closes https://github.com/nf-core/modules/issues/1155 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by rpetit3** [comment]
@drpatelh How would you recommend handling "no input".  The update module here doesn't require an input, which causes the lint to fail

**Comment by drpatelh** [comment]
Although, it's an edge case I think the only solution really is to downgrade this to a warning instead of an error. Fancy creating a PR to nf-core/tools for this?

**Comment by rpetit3** [comment]
Looks like the lint is just failing on the meta.yml file. Rather than altering tools for this rare case, what are your thoughts on adding a 'non-input' like this to the meta.yml?

```
input:
  - input_not_required:
      type: null
      description: This module does not have an input
```

**Comment by drpatelh** [comment]
> Looks like the lint is just failing on the meta.yml file. 

I did think I fixed this in the main script if `input` isn't there. It might have been for one of your other modules where you just had `input:`. Can't remember now 🤔 We should really fix it and a warning for `meta.yml` too. Hopefully, shouldn't be tricky. Be great if you can fix and if not push an issue to tools.

**Review by drpatelh — APPROVED** [review]
🚀

**Comment by rpetit3** [comment]
There was definitely another module I added that did the same, I'll look into tools and if I can't submit a PR, I'll raise an issue like you suggested

**Comment by drpatelh** [comment]
Fixed it here: https://github.com/nf-core/tools/pull/1374

**Comment by rpetit3** [comment]
Awesome! Thank you

**Pull request merged**
