### PR TITLE
Feat/bbmap_bbsplit nf-test

### LINKED ISSUE #4130: bbmap/bbsplit

### PR DESCRIPTION
**Pull request by Joon-Klaps**
## PR checklist

Closes #4130 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by sateeshperi** [comment]
@Joon-Klaps where is the snapshot for this test ?

**Review by sateeshperi — CHANGES_REQUESTED** [review]
need snapshot

**Comment by sateeshperi** [comment]
@Joon-Klaps we need this module for rnaseq...could you finish this when you get a chance plz.....thanks

**Comment by Joon-Klaps** [comment]
> @Joon-Klaps we need this module for rnaseq...could you finish this when you get a chance plz...also rm pytests..thanks

Snapshot is missing because the nf-test doesnt yet support alias, so it doesnt run sucessfully. Made an issue for this https://github.com/askimed/nf-test/issues/139. 
Would you have an idea to write the nf-tes without an alias?

**Comment by sateeshperi** [comment]
Thanks @Joon-Klaps 
can't think of a work around....looks like it is a feature that nf-test has to support

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
couple of tags missing, but we're getting there, finally <3

Thank you so much @Joon-Klaps

**Comment by Joon-Klaps** [comment]
@sateeshperi notice me senpai!

**Review by maxulysse — APPROVED** [review]

**Review by sateeshperi — APPROVED** [review]

**Pull request merged**
