### PR TITLE
Cardinality of MALT_BUILD

### PR DESCRIPTION
**Pull request by chriswyatt1**
Contributes to #2154

cardinality was wrong for the `MALT_BUILD` test (needs 5 inputs), have changed this to what I feel is the default (see below), and run nf-core modules test, and there are no failed jobs.

See line 27 of `main.nf`:
 
`MALT_BUILD ( fastas, seq_type, UNZIP_MALT.out.unzipped_archive.map{ it[1] } )`

changed to:

`MALT_BUILD ( fastas, seq_type, UNZIP_MALT.out.unzipped_archive.map{ it[1] } , "ref" , "taxonomy" )`

### CODE REVIEW

**Comment by SPPearce** [comment]
@nf-core-bot fix linting

**Comment by JoseEspinosa** [comment]
@nf-core-bot fix linting

**Comment by jfy133** [comment]
Given these are both modules I'll add, I will take the liberty to fix them on @chriswyatt1 's branch

**Review by nvnieuwk — DISMISSED** [review]

**Comment by nvnieuwk** [comment]
Tests are failing :fearful:

**Comment by jfy133** [comment]
Yes.. happening locally for me too... trying to debug...

**Comment by jfy133** [comment]
🙄

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://software-ab.cs.uni-tuebingen.de/download/megan6/nucl_acc2tax-Jul2019.abin.zip">here</a>.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at software-ab.informatik.uni-tuebingen.de Port 443</address>
</body></html>
```

**Review by nvnieuwk — APPROVED** [review]

**Comment by jfy133** [comment]
Thanks @chriswyatt1 @SPPearce @JoseEspinosa @nvnieuwk !

**Pull request merged**
