### PR TITLE
Update snapaligner: merge modes into one

### PR DESCRIPTION
**Pull request by matthdsm**
Currently `snapaligner` has different modules for `paired` and `single` since they are different subcommands.
This PR merges them into one, selected the subcommand based on `meta.single_end`.

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by sateeshperi** [comment]
do you think this will break any pipelines that use the module in its current version? @matthdsm

**Comment by sateeshperi** [comment]
but I agree with you that it does makes the code cleaner downstream! :smile:

**Review by sateeshperi — APPROVED** [review]
well lgtm!

**Comment by matthdsm** [comment]
Thank you very much!

**Pull request merged**
