### PR TITLE
Provide BAI when running rseqc/tin

### PR DESCRIPTION
**Pull request by drpatelh**

### CODE REVIEW

**Comment by mahesh-panchal** [comment]
xls missing from meta yml

**Comment by drpatelh** [comment]
Should be there.

**Comment by JoseEspinosa** [comment]
> Should be there.

I also spotted the same in my review :yum:

**Comment by drpatelh** [comment]
Ahhh, `meta.yml`!

**Comment by JoseEspinosa** [comment]
> Ahhh, `meta.yml`!

Know you would love this one :smile:

**Comment by drpatelh** [comment]
Ok. Done. You guys are too good for your own good.

**Review by JoseEspinosa — APPROVED** [review]
Once tests finish ready to go! :rocket:

**Pull request merged**
