### PR TITLE
fix(bases2fastq): Remove stray ls

### PR DESCRIPTION
**Pull request by Emiller88**

### CODE REVIEW

**Review by FriederikeHanssen — COMMENTED** [review]
looks good, but why do the singularity checksums not match?

**Comment by Emiller88** [comment]
IDK, it's using the docker container, so it should be the same. It could be because the RunManifest.json gets rewritten with any overrides and maybe the singularity image uses different line endings?

**Review by matthdsm — APPROVED** [review]
LGTM, pending the CI 😛

**Review by JoseEspinosa — COMMENTED** [review]
It has been reported as one of the failing modules after the restructuring (#2154)
So it would be great if you could update the list once the tests pass :smiley:

**Pull request merged**
