### PR TITLE
[FEATURE] update trimmomatic to emit summary output 

### PR DESCRIPTION
**Pull request by Joon-Klaps**
## PR checklist

Adding the summary output file of trimmomatic to easily access the number of dropped reads. 

Closes https://github.com/nf-core/modules/issues/2746

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!

- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [X] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by Joon-Klaps** [comment]
I don't get it why conda is having trouble installing trimmomatic even though no code was changed here and gitpod testing completes all tests successfully.  Can anyone help me understand this? 

The error that get's thrown and causes the workflow to fail:
`UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (ruamel.yaml):`

**Comment by Joon-Klaps** [comment]
PR https://github.com/nf-core/modules/pull/2740 solved the previously mentioned installation problems of the conda environment within the pytest-workflow.

**Review by nvnieuwk — APPROVED** [review]
LGTM!

**Review by Emiller88 — APPROVED** [review]
Looks good to me! We need to PR some changes from viralintegration as well, https://github.com/nf-core/viralintegration/commit/1fcf88ab7d677fad6badc2e316d4f6e9406af84f because multiqc apparently takes the stderr? We should add an example of that to the tests as well.

**Comment by Joon-Klaps** [comment]
@nf-core-bot fix linting

**Comment by Joon-Klaps** [comment]
@Emiller88 the changes that were done in trimmomatic at https://github.com/nf-core/viralintegration/commit/1fcf88ab7d677fad6badc2e316d4f6e9406af84f have also been implemented here and a test was included.

**Comment by Emiller88** [comment]
@Joon-Klaps, I was just mentioning it, I probably should have clarified, let's do that in a follow-up. Can you remove all the commits after https://github.com/nf-core/modules/pull/2748/commits/ca68b296bac23b9ae2981fdebae70bcaa3d6fdc7 ? Since adding our hacks definitely lowered your code quality.

**Comment by Joon-Klaps** [comment]
@Emiller88 I see, whoops... Sorry for the misunderstanding.

**Pull request merged**
