### PR TITLE
Added support for `task.ext.args`

### PR DESCRIPTION
**Pull request by muffato**
Hello,

bedToBigBed has several command-line options, but none are not available through the existing module. This PR adds support for `task.ext.args` so that those options become available.

By the way, this means that the BED file can be any number of columns as the `-type` and `-as` can now be used. Should the module be renamed to `bedToBigBed` (i.e. removing `12`) ?

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by drpatelh** [comment]
Thanks! Yes, makes sense to rename it to `bedtobigbed` to reflect the CLI command. Can't remember why I called it that now 🤔

**Comment by muffato** [comment]
I've renamed the module

**Comment by muffato** [comment]
I've renamed the module

**Review by drpatelh — APPROVED** [review]
Awesome! Thanks 👌🏽

**Comment by muffato** [comment]
Thanks for the quick review

**Pull request merged**
