### PR TITLE
remove cpu restrictions for piped commands

### PR DESCRIPTION
**Pull request by ramprasadn**
In case of modules with piped commands, currently, we are splitting the number of cpus assigned for that process equally between the two softwares. This is good idea in general, but when we have a combination of aligner and samtools (for converting the resulting output to bam), I think it is very inefficient to assign half the number of cpus to samtools when the rate limiting step here is the alignment.

These are the affected modules.
-  bowtie/align
-  bowtie2/align
-  bwa/mem
-  bwamem2/mem
-  bwameth/align

Based on the comments and discussion in the nf-core slack channel [here](https://nfcore.slack.com/archives/CJRH30T6V/p1632822976224200), [here](https://nfcore.slack.com/archives/CJRH30T6V/p1632822291214200), and [here](https://nfcore.slack.com/archives/CJRH30T6V/p1632822851221500), I am getting rid of these restrictions in this PR. The rationale being that these manual restrictions hurt most users, and almost all schedulers in use today should be able to handle resource allocation efficiently on their own. 

Should anyone face any issues due to changes in this PR there are other workarounds (like, taskset) that they can adopt to fix those issues. 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Review by drpatelh — COMMENTED** [review]
Thanks @ramprasadn ! LGTM 🎉  Let's wait for @pontus to confirm .

**Review by grst — APPROVED** [review]
This solution I can live with even on a "broken scheduler" ;)

**Review by pontus — APPROVED** [review]
Looks good. I'm a bit unsure if it's best to give a number of threads like this or let the tools figure things out, but this is better than what we have and I don't think there's a real noticable difference between the two "good cases" anyway.

**Comment by ramprasadn** [comment]
Excellent! In that case, I will merge this PR to master.

**Pull request merged**
