### PR TITLE
Updating Readme

### PR DESCRIPTION
**Pull request by varunshamanna**
## PR checklist

Closes #XXX 

-  This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by varunshamanna** [comment]
I have Updated the Readme for each command and aligned the lines equally.

**Review by Emiller88 — APPROVED** [review]
Great work! I think we're going to cut 2.4 pretty soon though, so we shouldn't close #1400 yet.

**Comment by muffato** [comment]
@varunshamanna . Would you be able to update the README for the latest version (2.5.1) of nf-core tools ?

**Comment by varunshamanna** [comment]
Hi,

I can do it in the coming week. I am pretty occupied this week.

Hope it's ok.

Wishes & Regards,

Varun Shamanna
Senior Bioinformatician,
Central Research Laboratory,
KIMS, Bangalore

**Comment by muffato** [comment]
Absolutely fine :+1: . Thank you very much !

**Comment by matthdsm** [comment]
Hi there!

We've noticed there hasn't been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we'll close your PR in about 2 weeks

Cheers
the nf-core maintainers

**Pull request closed without merging**
