### PR TITLE
feat: add stats parameter support to FilterMutectCalls

### PR DESCRIPTION
**Pull request by lmtani**
Here we add a way to use stats file. It's already defined in the process inputs, but it was not being used.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by maxulysse** [comment]
I think you need to add it there too:
```
    tuple val(meta), path(vcf), path(vcf_tbi), path(stats), path(orientationbias), path(segmentation), path(table), val(estimate)
```

**Comment by lmtani** [comment]
@maxulysse : is it possible that the test was failing even before my PR? I removed my changes and leaved only a "echo" line there and it is still failing.

**Comment by lmtani** [comment]
Seems like the following subworkflows:

- `GATK_TUMOR_NORMAL_SOMATIC_VARIANT_CALLING`
- `GATK_TUMOR_ONLY_SOMATIC_VARIANT_CALLING`

Are using wrong number of channels as input for (at least) these tasks:

- `GATK4_MUTECT2`
- `GATK4_GETPILEUPSUMMARIES`

Here is an example. Calling the process:

https://github.com/nf-core/modules/blob/174170689d08dc614316d90f15a73a3b0ba94521/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf#L39

And the respective process definition:

https://github.com/nf-core/modules/blob/c8e35eb2055c099720a75538d1b8adb3fb5a464c/modules/nf-core/gatk4/mutect2/main.nf#L10-L18

Causing, during the tests:

```sh
stdout: N E X T F L O W  ~  version 22.10.6
Launching `./tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf` [romantic_kilby] DSL2 - revision: 447ebfec2f
Process `test_gatk_tumor_only_somatic_variant_calling:GATK_TUMOR_ONLY_SOMATIC_VARIANT_CALLING:MUTECT2` declares 8 input channels but 12 were specified

 -- Check script 'tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/../../../../subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf' at line: 35 or see '.nextflow.log' file for more details
```

**Comment by maxulysse** [comment]
I'll try the test locally then.
Can you create stub this modules?

**Comment by maxulysse** [comment]
ok, so 3 tests are running when this module is updated:

* tests/modules/nf-core/gatk4/filtermutectcalls/test.yml :white_check_mark: 
* tests/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/test.yml :x:
* tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/test.yml :x:

So as long as the first one is still working, I'm ok for any changes here.
The subworkflows are due for an update, so don't worry about them

**Comment by maxulysse** [comment]
I still think you need to add stats as an input

**Comment by lmtani** [comment]
I don't know if I understand what you are suggesting. 

_Stats_ already is an input for the _GATK4_FILTERMUTECTCALLS_ process:

https://github.com/nf-core/modules/blob/6d236e2633cd4d064178b299dc79b9781921769f/modules/nf-core/gatk4/filtermutectcalls/main.nf#L11

And there are tests using it as input:

https://github.com/nf-core/modules/blob/5e34754d42cd2d5d248ca8673c0a53cdf5624905/tests/modules/nf-core/gatk4/filtermutectcalls/main.nf#L29-L38

With this _nf-core/test-dataset_ file: https://github.com/nf-core/test-datasets/blob/modules/data/genomics/homo_sapiens/illumina/gatk/paired_mutect2_calls/test_test2_paired_mutect2_calls.vcf.gz.stats

I also noted that this field is described in the module _meta.yaml_ file. Could you point me where to add it?

**Review by matthdsm — APPROVED** [review]

**Comment by lmtani** [comment]
I'm clearing up my pending tasks. I'm closing this PR as it seems to have been inactive for a while. For my pipeline, I ended up using a custom task. Thanks for the guidance.

**Pull request closed without merging**
