### PR TITLE
more generic name because of multiple extension

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by maxulysse** [comment]
> woops too fast, probably needs updates to the meta yml?

no, meta was not updated actually.

But might have been too fast indeed, I was hoping to raise more discussion about it

**Comment by FriederikeHanssen** [comment]
> But might have been too fast indeed, I was hoping to raise more discussion about it

Can leave it open for a bit

**Comment by maxulysse** [comment]
@matthdsm what's your take?

**Comment by matthdsm** [comment]
Also, I haven't tested this, but does `samtools stats` handle unaligned bams?

**Comment by FriederikeHanssen** [comment]
https://github.com/nf-core/modules/issues/1450 leaving this here since there is an ongoing discussion on this for a while now

**Comment by maxulysse** [comment]
I forgot that discussion.
Anyhow, since the meta.yml was not updated, I propose to use this PR, to revert to previous syntax, and then fix the names once we agreed on a better naming convention.

**Comment by matthdsm** [comment]
> Anyhow, since the meta.yml was not updated, I propose to use this PR, to revert to previous syntax, and then fix the names once we agreed on a better naming convention.

Agreed, the input naming doesn't really matter that much, as long as the outputs aren't changed

**Review by matthdsm — APPROVED** [review]

**Pull request merged**
