### PR TITLE
Let DESeq2 module be flexible with CSV/ TSV, and use semicolons in blocking field

### PR DESCRIPTION
**Pull request by pinin4fjords**
This PR:

- Adds a basic method for being flexible with input files (CSV or TSV). There's a lot of inconsistency in what's used, and maybe it's better if the module is just flexible. This makes it respond to file extensions.
- Fixes a previous assumption about a comma-separated field in a comma-separated file. I think it's better if the blocking definition is semicolon-separated where multiple values are supplied, so that things don't break when that is stored in a CSV file like [the example](https://github.com/nf-core/test-datasets/blob/modules/data/genomics/mus_musculus/rnaseq_expression/SRP254919.contrasts.csv).

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by Emiller88 — CHANGES_REQUESTED** [review]
Looks good to me. I don't know if there's a more built-in way to do this than defining a function in R, but as long as it works.

Actually, could you add a test for a tsv? Just to make sure this functionality is covered and anything in the future doesn't break it.

**Comment by pinin4fjords** [comment]
> Looks good to me. I don't know if there's a more built-in way to do this than defining a function in R, but as long as it works.

Will be glad to hear of a tidy way that doesn't involve additional libraries! It's a bit hacky I'll admit, but a thin layer around `read.delim()`, so not too naughty I think.

> Actually, could you add a test for a tsv? Just to make sure this functionality is covered and anything in the future doesn't break it.

Good idea. I've added an extra test that converts the matrix to CSV and tries it again. You'll see that the DESeq outputs in the test.yml are identical in their hashes.

**Review by Emiller88 — APPROVED** [review]
Awesome! Great work!

**Comment by pinin4fjords** [comment]
Thanks for the review @Emiller88 !

**Pull request merged**
