### PR TITLE
Bump bases2fastq

### PR DESCRIPTION
**Pull request by edmundmiller**
We're a couple of versions behind 😬 

@blajoie

### CODE REVIEW

**Comment by Emiller88** [comment]
It's throwing an error sadly:
```
    what():  Run manifest file doesn't exist /home/runner/pytest_workflow_3q14yxch/bases2fastq/work/f8/4af9958a781006f17eeb699470581e/sim-data/RunManifest.json```

**Comment by blajoie** [comment]
Andrew A and I will look @Emiller88  !

**Comment by blajoie** [comment]
@Emiller88  - looks like we need to update the test-data being used here:
https://github.com/nf-core/test-datasets/raw/demultiplex/testdata/sim-data/sim-data.tar.gz

Can we be given access?  Or we can provide you a new tar ball and you could PR that in?  Then the test should succeed !

**Comment by blajoie** [comment]
pushed a fix @Emiller88  - have a look!

**Comment by Emiller88** [comment]
Currently waiting on the elembio quay account to be provisioned so we can point the docker image there, using docker hub breaks the linting.

**Comment by maxulysse** [comment]
there's some conflicts to solve I'm afraid

**Comment by SPPearce** [comment]
Is this a Pr that could be helped along with seqera containers to make the image?

**Comment by edmundmiller** [comment]
No sadly, the opposite. I was chatting with @blajoie via slack and they'd prefer to keep everyone using their docker image for various reasons.

https://hub.docker.com/r/elembio/bases2fastq

I'll update the image to use that image and we can wrap this up!

**Review by SPPearce — APPROVED** [review]
Add the versions channel to the nf-test to pass the linting and it is good to go.

**Pull request merged**
