### PR TITLE
Rename spatialomics to imaging in test_data.config

### PR DESCRIPTION
**Pull request by adamjtaylor**
Contributes to https://github.com/nf-core/test-datasets/issues/815 as requested in https://github.com/nf-core/test-datasets/pull/821#pullrequestreview-1360366283.

This PR renames the previous `spatialomics` test dataset directory to `imaging` for more consistency and clarity.

`tiff` and `ometiff` datasets added in  https://github.com/nf-core/test-datasets/pull/821 have also added

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by nvnieuwk** [comment]
Can you also do a search for all modules that used the spatialomics data and change their test `main.nf` files to use `imaging` instead of `spatialomics`?

**Review by nvnieuwk — APPROVED** [review]
LGTM!

**Comment by adamjtaylor** [comment]
the test for `ilastic/pixelclassification docker` (and others!) failed with the following error, which I think is due to a linting or other error in `test_data.config`

```
  /groovy/script/ScriptD95DD3E505ADF1CA47D8FD89E372A038: 578: The LHS of an assignment should be a variable or a field accessing expression @ line 578, column 17.
                     cycif_tonsil-cycle2.ome.tif     = "${params.test_data_base}/data/imaging/ome-tiff/cycif-tonsil-cycle2.ome.tif"    
```

Looking to fix this now

**Comment by adamjtaylor** [comment]
Ah! I had left extensions with `.` in them in the dataset names. Removing them should fix.

**Comment by nvnieuwk** [comment]
Good spot!

**Comment by adamjtaylor** [comment]
Humm same error. Possibly the hyphens are the issue?

**Comment by nvnieuwk** [comment]
Can you also change `ome-tiff` to `ome_tiff`? Just to be sure?

**Comment by adamjtaylor** [comment]
I'm fairly certain `'ome-tiff'` will be fine as they key is quoted. Will let these tests run before changing if needed. If tests pass I think we can merge. As we are planning to restructure this section (again 🤦‍♂️) and moving to purpose rather than file-type nesting per https://github.com/nf-core/test-datasets/issues/822#issuecomment-1486646253, we will ensure we only use underscores in that PR

**Comment by nvnieuwk** [comment]
Awesome! Let's hope it works. Keep up the good work 🥳

**Comment by adamjtaylor** [comment]
Failed. @FloWuenne this looks like it might be on the module side. Could you take a look.

**Comment by nvnieuwk** [comment]
> Failed. @FloWuenne this looks like it might be on the module side. Could you take a look.

`No such file: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/imaging/h5/plant_wga.h5`

**Comment by adamjtaylor** [comment]
Ah! So we need to merge https://github.com/nf-core/test-datasets/pull/821 first! My fault. That is ready to merge so doing so now.

**Comment by nvnieuwk** [comment]
Awesome! Glad it works now 🚀

**Comment by adamjtaylor** [comment]
It looks like the merge queue failed at `check for changes` failed with exit code `128`

```
Searching for merge-base master...gh-readonly-queue/master/pr-3164-1c7be83f545e87656c69e056ff57eb9e1c068576
Error: The process '/usr/bin/git' failed with exit code 128
```

I'm going to resubmit in the hope that this was transient.

**Comment by adamjtaylor** [comment]
Resubmitting was successful!

**Pull request merged**
