### PR TITLE
Update GATK_UG: change from gzip to bgzip

### PR DESCRIPTION
**Pull request by TCLamnidis**
Changes the compression used for the output VCF from gzip to bgzip. The latter is compatible with `bcftools`, which is the standard tool for using VCFs.

### CODE REVIEW

**Comment by TCLamnidis** [comment]
`bgzip` is not included in the environment for `gatk`. I have added it to the conda environment definition, but will need to create a multi-tool-container for it now.

**Comment by TCLamnidis** [comment]
Waiting on https://github.com/BioContainers/multi-package-containers/pull/2992

**Comment by TCLamnidis** [comment]
@jfy133 @ilight1542 
This should be ready now.

**Review by nvnieuwk — APPROVED** [review]
LGTM

**Comment by TCLamnidis** [comment]
tests seemed to pass, but the merge queue did not think so. updated barnch and trying again once i get the green ticks

**Pull request merged**
