### PR TITLE
Minor refactor on attachMultiqcReport function.

### PR DESCRIPTION
**Pull request by robsyme**
The attachMultiqcReport function was renamed as the function does not attach the multiqc report, but rather simply tests if the input object contains zero, one, or more multiqc reports and returns a single report if available and, issues a warning in the zero or >1 case.

The function was also refactored to be more resilient to the type of object passed as input. The function can now not only take a collection of zero, one, or more more multiqc reports, but will also handle the case if the input object is a Path object. Handling a path might be useful just in case somebody uses this workflow and calls .first() instead of .toList() to convert the queue channel into a value channel.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
Feel free to merge

**Review by mirpedrol — APPROVED** [review]

**Comment by mirpedrol** [comment]
Some of the tests are failing complaining about the `switch`: https://github.com/nf-core/modules/actions/runs/12138791850/job/33845006274?pr=7129

**Comment by SPPearce** [comment]
The VSCode plugin is complaining about the switch:
image
Complaining about:
`Unexpected input: '\n'`

**Comment by robsyme** [comment]
Great point Simon. Fixed [here](https://github.com/nf-core/modules/pull/7168)

**Pull request merged**
