### PR TITLE
new module: deepbgc/pipelines

### LINKED ISSUE #1995: new module: DEEPBGC/PIPELINE
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

### PR DESCRIPTION
**Pull request by louperelo**
## PR checklist

Closes #1995  

- [ x] This comment contains a description of changes (with reason).
- [ x] If you've fixed a bug or added code that should be tested, add tests!
- [ x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x ] If necessary, include test data in your PR.
- [ x] Remove all TODO statements.
- [x ] Emit the `versions.yml` file.
- [x ] Follow the naming conventions.
- [x ] Follow the parameters requirements.
- [ x] Follow the input/output options guidelines.
- [ x] Add a resource `label`
- [x ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by louperelo** [comment]
Oh, ok. I asked about that on Wednesday and understood that it should be included ..., deepBGC recognises, when the download already exists and doesn't download again.

**Comment by jfy133** [comment]
> Oh, ok. I asked about that on Wednesday and understood that it should be included ..., deepBGC recognises, when the download already exists and doesn't download again.

Ah maybe I just meant as a module/for the pipeline 😅.... I've been having trouble communicating recently, maybe I should take a holiday...

The point still stands though, is it easy to separate? Can you tell `download` where to save the database?

**Comment by louperelo** [comment]
There is no command option to specify the download directory. The documentation only says this:
`Set DEEPBGC_DOWNLOADS_DIR env variable to specify a different downloads directory.`
No idea yet how to do that.

**Comment by jfy133** [comment]
> There is no command option to specify the download directory. The documentation only says this: `Set DEEPBGC_DOWNLOADS_DIR env variable to specify a different downloads directory.` No idea yet how to do that.

I think we can just go in the first step of the download module

```
export DEEPBGC_DOWNLOADS_DIR='./db'
```

(might possibly have to `mkdir db` beforehand)

and then for the pipeline itself

```
DEEPBGC_DOWNLOADS_DIR=${db_path}
```

where `db_path` is an input channel?

**Comment by louperelo** [comment]
Nice, it works without `mkdir` before. I'll give it a try with the download module then.

**Pull request closed without merging**
