### PR TITLE
feat: remove hacky INDEX

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by maxulysse** [comment]
Still a WIP

**Review by Emiller88 — APPROVED** [review]
I love it! The only thing is how does this look in the work directory? Are all the index files in the root? Just wondering.

**Comment by maxulysse** [comment]
> I love it! The only thing is how does this look in the work directory? Are all the index files in the root? Just wondering.

yes all files in the root folder, it how I use to do it in sarek before

**Comment by FriederikeHanssen** [comment]
How does it work with multiple bwa indices, so like for bwa and bwamem2?

> I love it! The only thing is how does this look in the work directory? Are all the index files in the root? Just wondering.

**Comment by maxulysse** [comment]
> How does it work with multiple bwa indices, so like for bwa and bwamem2?
> 
> > I love it! The only thing is how does this look in the work directory? Are all the index files in the root? Just wondering.

Not sure I understood your question there

**Comment by drpatelh** [comment]
Hi Guys. Let's maybe discuss and vote for this on #modules before merging because this will have implications for other modules requiring a typical alignment index and will also mean we need to update the `igenomes.config` for all pipelines that use it.

Be great if you can summarise the advantages and disadvantages compared to the current method in #modules please @maxulysse ?

**Comment by FriederikeHanssen** [comment]
> > How does it work with multiple bwa indices, so like for bwa and bwamem2?
> > > I love it! The only thing is how does this look in the work directory? Are all the index files in the root? Just wondering.
> 
> Not sure I understood your question there

Nevermind me, I half-way remembered this [thread](https://nfcore.slack.com/archives/CELEMAGC9/p1642406552010600) but didn't open it. Now I see that there is a long dicussion there. Will read through it there and comment

**Comment by maxulysse** [comment]
@mahesh-panchal any idea why the nf-core linting is failing?

**Comment by mahesh-panchal** [comment]
Looks like a parsing issue. I'll have a look.

**Comment by mahesh-panchal** [comment]
These lines need an update it seems:
https://github.com/nf-core/tools/blob/e563811adb292b07ec933a52611e937ce9ef5481/nf_core/modules/lint/main_nf.py#L55-L68
to account for the when. The linter thinks it's still in the output block.

**Comment by mahesh-panchal** [comment]
Updated linter in https://github.com/nf-core/tools/pull/1397, but not sure what to do here.

**Pull request closed without merging**
