### PR TITLE
Add test for initialize breaking the template

### PR DESCRIPTION
**Pull request by edmundmiller**
If we're moving stuff out of the template that can break the template we need to check for changes.

Can include any other files that might break the template as well.

### CODE REVIEW

**Comment by edmundmiller** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow

**Comment by edmundmiller** [comment]
> no way updating a subworkflow or module breaks the template

Love it, that's the goal!

> It's hideously convoluted to test a different repo within another repo.

Yeah it's a bit much to think about. 

How does tools currently install/update fastqc?

**Comment by mashehu** [comment]
> How does tools currently install/update fastqc?

It's a manual step in the release: https://github.com/nf-core/tools/blob/master/.github/RELEASE_CHECKLIST.md?plain=1#L6

**Comment by edmundmiller** [comment]
Via @mashehu -bot https://github.com/nf-core/tools/commit/8d1094ca285c433880f8fd81fa409d064417fb1b

So we'd catch it there, might just go a few months without noticing, or be something that breaks when the dependancies get bumped before release and stales it.

Maybe a cron job that runs the module and subworkflow update and bumps it in modules so it can get fixed ahead of time and not block a release?

**Comment by mashehu** [comment]
> Maybe a cron job that runs the module and subworkflow update and bumps it in modules so it can get fixed ahead of time and not block a release?

couldn't renovate do this?

**Comment by edmundmiller** [comment]
> couldn't renovate do this?

Probably, I think we debated it. But I think that's a whole thing to make a [renovate datasource](https://docs.renovatebot.com/modules/datasource/) for nf-core/modules.

**Comment by mashehu** [comment]
closing this, because we will use https://github.com/nf-core/tools/pull/2733 instead

**Pull request closed without merging**
