### PR TITLE
Add stub and nf-test for malt/run & malt/build

### PR DESCRIPTION
**Pull request by jfy133**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by maxulysse — COMMENTED** [review]
Looking good

**Review by nvnieuwk — APPROVED** [review]
LGTM!! :rocket:

**Comment by nvnieuwk** [comment]
Those tests should be fixed though :grin:

**Comment by jfy133** [comment]
Ah that was the last thing: tests can't run at all currently because the website the reference db file it needs is down (I will put back the URL)... but I'll need to set these tests to just running stub at the moment :(

**Comment by nvnieuwk** [comment]
Cool :p

**Comment by jfy133** [comment]
I'll need to then comment out the tests and leave just stubs (with the ownloaded file just as a `[]`)

**Comment by ahvigil** [comment]
you could consider adding test reference to nf-core modules test datasets: https://nf-co.re/docs/contributing/test_data_guidelines#modules. We want to avoid reaching out to external sources, especially if they aren't reliably available.

**Comment by jfy133** [comment]
> you could consider adding test reference to nf-core modules test datasets: https://nf-co.re/docs/contributing/test_data_guidelines#modules. We want to avoid reaching out to external sources, especially if they aren't reliably available.

~~Agreed, unfortunately the file is too large :(~~

OK given the last maintainers meeting and the plan to possible mirror the test data repo to AWS I've done that with this file, also as I will have to use it for a new pipeline too...

**Pull request merged**
