### PR TITLE
Created a local writable copy of the genome to avoid ltrretriever die

### PR DESCRIPTION
**Pull request by GallVp**
## PR checklist

Closes #XXX 

- [x] Created a local writable copy of the genome to avoid ltrretriever die. This is related to https://github.com/oushujun/LTR_retriever/issues/176 and https://github.com/Plant-Food-Research-Open/assemblyqc/issues/98
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by SPPearce** [comment]
Can you please add a comment as to why this is required.
Actually, if all you need is to be able to modify the input file, you could try staging it as a copy rather than a symlink.

**Comment by GallVp** [comment]
> Can you please add a comment as to why this is required. Actually, if all you need is to be able to modify the input file, you could try staging it as a copy rather than a symlink.

Thank you @SPPearce 

I have added a comment explaining the reason for this PR. I could not figure out how to stage as copy.

**Comment by SPPearce** [comment]
> > Can you please add a comment as to why this is required. Actually, if all you need is to be able to modify the input file, you could try staging it as a copy rather than a symlink.
> 
> Thank you @SPPearce 
> 
> I have added a comment explaining the reason for this PR. I could not figure out how to stage as copy.

https://www.nextflow.io/docs/latest/process.html#stageinmode

I'm on my phone so can't find the button to search the modules repo to find an example, but if you search for stageinmode you should find one.

**Comment by GallVp** [comment]
> > > Can you please add a comment as to why this is required. Actually, if all you need is to be able to modify the input file, you could try staging it as a copy rather than a symlink.
> > 
> > 
> > Thank you @SPPearce
> > I have added a comment explaining the reason for this PR. I could not figure out how to stage as copy.
> 
> https://www.nextflow.io/docs/latest/process.html#stageinmode
> 
> I'm on my phone so can't find the button to search the modules repo to find an example, but if you search for stageinmode you should find one.

Great! That's done now! Thank you!

**Comment by SPPearce** [comment]
Have you checked that the copy has the sufficient permissions to be able to edit it?

**Review by SPPearce — APPROVED** [review]

**Comment by GallVp** [comment]
> Have you checked that the copy has the sufficient permissions to be able to edit it?

Good question. No, not according to this: https://github.com/nextflow-io/nextflow/blob/bc2fb4092f18d046dd82863c494cd669519e0acd/modules/nextflow/src/main/groovy/nextflow/executor/SimpleFileCopyStrategy.groovy#L234C20-L234C28

**Comment by GallVp** [comment]
I have reverted back to the manual `copy+chmod` version

**Pull request merged**
