### PR TITLE
Removed strelka e-mailing ability

### PR DESCRIPTION
**Pull request by ollieeknight**
## PR checklist

see https://github.com/nf-core/sarek/issues/932! 

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
🚀 looks good. Thanks so much for adding this fix

**Review by FriederikeHanssen — APPROVED** [review]

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
Only this issue with Strelka?
Nothing with Manta?

**Comment by ollieeknight** [comment]
yep, currently looking into it now! Is there a way for me to add that to this PR, or do I have to create a new one? Perhaps it would be best to close this and open one with all?

**Comment by maxulysse** [comment]
Too late, it has been merged, so create a new PR please

**Pull request merged**
