### PR TITLE
Add module: ANGSD_GL

### PR DESCRIPTION
**Pull request by apeltzer**
Adds ANGSD Genotype Likelihood calculation

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by TCLamnidis** [comment]
Not sure what is up with the conda test.

**Comment by sateeshperi** [comment]
from the logs
```
fai index file: 'genome.fasta.fai' looks older than corresponding fastafile: 'genome.fasta'.
-> Please reindex fasta file
```

**Comment by TCLamnidis** [comment]
But I am not pulling any index for the fasta I use 😅 And why does it only fail on conda but not singularity and docker? 😅 😅

**Comment by TCLamnidis** [comment]
ANGSD does not exist for my local architecture on bioconda (`osx-64`), so I cannot test locally. I think this is one of the cases where the conda testing is being flaky.

**Review by FriederikeHanssen — APPROVED** [review]
lgtm

**Pull request merged**
