### PR TITLE
Fix output for bcl2fastq & bclconvert

### LINKED ISSUE #3794: `bcl2fastq` and `bclconvert` exclude some `.fastq.gz` files from the output
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

I think there is a misunderstanding on how glob works in the output specification for both the `bcl2fastq` and `bclconvert` modules at [bcl2fastq/main.nf:L11-12](https://github.com/nf-core/modules/blob/868d4c3dc7a3db39d36184173e4fe3484499396e/modules/nf-core/bcl2fastq/main.nf#L11-12) and at [bclconvert/main.nf:L11-12](https://github.com/nf-core/modules/blob/868d4c3dc7a3db39d36184173e4fe3484499396e/modules/nf-core/bclconvert/main.nf#L11-12).

It seems like the meaning of this glob was to exclude the string `Undetermined`, but what the glob actually does is exclude any of the following characters once: `[Udeimnrt]` (see documentation [here](https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob)). In other words, the glob won't match a fastq file if the sample name ends with any of these letters.

Not quite sure about what's the best way to fix this. Maybe it's enough to look at the sample number? That is, Undermined will always be followed by `S0` while other files will have a sample number > 1 without leading zeros, so matching with `S[1-9]*` could work (see [bcl2fastq documentation](https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v2-20-software-guide-15051736-03.pdf), page 17). 

### Command used and terminal output

This can be reproduced through the demultiplex pipeline. The runfolder is too big to be uploaded here, but you can download [the demultiplex test dataset](https://raw.githubusercontent.com/nf-core/test-datasets/demultiplex/samplesheet/1.3.0/flowcell_input.csv) and change the sample names in the SampleSheet to e.g. `Sample1U`.

Then run the pipeline with e.g.
```
 run main.nf -profile docker,test --outdir /tmp/demuxout --input /tmp/testdemux/input_samplesheet.csv --demultiplexer bcl2fastq
```

This will produce the following output:
```console
-[nf-core/demultiplex] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_DEMULTIPLEX:DEMULTIPLEX:BCL_DEMULTIPLEX:BCL2FASTQ (220422_M11111_0222_000000000-K9H97.1)'

Caused by:
  Missing output file(s) `**[!Undetermined]_S*_R?_00?.fastq.gz` expected by process `NFCORE_DEMULTIPLEX:DEMULTIPLEX:BCL_DEMULTIPLEX:BCL2FASTQ (220422_M11111_0222_000000000-K9H97.1)`

Command executed:

  if [ ! -d 220422_M11111_0222_000000000-K9H97 ]; then
      mkdir -p 220422_M11111_0222_000000000-K9H97
  fi
  
  if false; then
      ## Ensures --strip-components only applied when top level of tar contents is a directory
      ## If just files or multiple directories, place all in 220422_M11111_0222_000000000-K9H97
  
      if [[ $(tar -taf 220422_M11111_0222_000000000-K9H97 | grep -o -P "^.*?\/" | uniq | wc -l) -eq 1 ]]; then
          tar \
              -C 220422_M11111_0222_000000000-K9H97 --strip-components 1 \
              -xavf \
               \
              220422_M11111_0222_000000000-K9H97 \
  
      else
          tar \
              -C 220422_M11111_0222_000000000-K9H97 \
              -xavf \
               \
              220422_M11111_0222_000000000-K9H97 \
  
      fi
  fi
  
  bcl2fastq \
      --tiles s_1_1101 \
      --output-dir . \
      --runfolder-dir 220422_M11111_0222_000000000-K9H97 \
      --sample-sheet SampleSheet.csv \
      --processing-threads 2
  
  cp -r 220422_M11111_0222_000000000-K9H97/InterOp .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_DEMULTIPLEX:DEMULTIPLEX:BCL_DEMULTIPLEX:BCL2FASTQ":
      bcl2fastq: $(bcl2fastq -V 2>&1 | grep -m 1 bcl2fastq | sed 's/^.*bcl2fastq v//')
  END_VERSIONS

Command exit status:
  0

Command output:
  (empty)

Command error:
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C77.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C78.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C79.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C80.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C81.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C82.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C83.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C84.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C85.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C86.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C87.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C88.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C89.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C90.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C91.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C92.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C93.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C94.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C95.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C96.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C97.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C98.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C99.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C100.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C101.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C102.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C103.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C104.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C105.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C106.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C107.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C108.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfdef6700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C109.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:01 [7f0bfe6f7700] INFO: Opened BCL file '220422_M11111_0222_000000000-K9H97/Data/Intensities/BaseCalls/L001/C110.1/s_1_1101.bcl' with 673257 clusters
  2023-08-31 12:14:03 [2557880] INFO: Created InterOp file '"220422_M11111_0222_000000000-K9H97/InterOp/IndexMetricsOut.bin"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/all"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/all/all"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/all/all/all"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/all/all/unknown"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/default"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/default/Sample1U"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/default/Sample1U/all"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/default/Sample1U/unknown"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/default/all"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/default/all/all"
  2023-08-31 12:14:03 [2557880] INFO: creating directory "./Reports/html/000000000-K9H97/default/all/unknown"
  2023-08-31 12:14:03 [2557880] Processing completed with 0 errors and 0 warnings.
```

Here the pipeline will fail because of missing output files (even though these can be found in the work directory of the corresponding step), but this could go unnoticed in more complex scenarios were at least some output files are picked up.

### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by Aratz**
In a nutshell, the previous glob would miss files where the sample name ends with one of these letters `[Udeimnrt]`, see issue #3794 for more details.

This PR matches fastq files using their sample number instead, which will be 0 for Undetermined files and >1 for other files (see [bcl2fastq docs](https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v2-20-software-guide-15051736-03.pdf), page 17).

I'm not sure about how to update the tests though... I guess I would need to update the samplesheet at https://github.com/nf-core/test-datasets/blob/modules/data/genomics/homo_sapiens/illumina/bcl/flowcell_samplesheet.csv but that would probably break a cascade of other tests I guess? Or is there a way to edit the samplesheet in place if I create a new test?

## PR checklist

Closes #3794 

- [X] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If necessary, include test data in your PR.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [X] `PROFILE=docker pytest --tag bcl2fastq --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=docker pytest --tag bclconvert --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=singularity pytest --tag bcl2fastq --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=singularity pytest --tag bclconvert --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by Emiller88** [comment]
Awesome, thanks for taking care of this!

What needs to be addressed on the test? It seems that they all pass?

**Comment by Aratz** [comment]
Yes I mean creating new regression tests that would have picked up the issue with `[!Undetermined]`, and also to test this fix a bit more thoroughly. I guess the best would be to have slightly bigger datasets with more samples and different names but idk maybe this is overkill. If you think this is fine we can just go ahead and merge this.

My thinking with the tests breaking was that if I made a new version of the sample sheet in the test-datasets repo it could break tests in other repositories that use this data but as stated in the issue you linked, if these tests use the commit SHA it should be no problem.

**Comment by Emiller88** [comment]
I'm fine if you want to add a test in this PR, or if you'd like to create an issue to follow up, and drop a TODO in the test file linking to the issue. I'd probably vote the second, so we can get the fix out.

I'd also prefer if you wrote it in nf-test, as it's just one less test we'll have to convert eventually 😉

**Comment by Emiller88** [comment]
Awesome, thanks for fixing that!

**Comment by Aratz** [comment]
I think you need to approve the PR, right? Or is there anything else you'd want me to add? @Emiller88

**Review by Emiller88 — APPROVED** [review]
I guess that's how it works 😅

**Pull request merged**
