### PR TITLE
Misc. fixes in pytest_modules.yml

### PR DESCRIPTION
**Pull request by muffato**
When reviewing code I found a few issues in pytest_modules.yml:
 - wrong paths / tool names
 - tools that already exist (as subtools under the tool named "deeptools")
 
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by matthdsm** [comment]
Won't this break A LOT of testing?

**Comment by muffato** [comment]
On the contrary, this will fix testing / CI because those entries currently don't match any files in the repository.

For instance, if you push a change to `tests/modules/nf-core/cooler/zoomify/*`, it won't be picked up because the pattern is `tests/software/cooler/zoomify/**`. If you push a change to the code/tests of `deeptools/plotcorrelation`, pytest won't pick those up at all because the pattern is `modules/plotcorrelation/**`, etc. The ones I've completely removed are already covered elsewhere in the yml file

**Comment by matthdsm** [comment]
I actually meant, will the tests actually pass now that they will run? Won't that cause any issues? Other than that, I can only applaud this effort!

**Review by matthdsm — APPROVED** [review]

**Comment by muffato** [comment]
Ah, I see what you mean. I've checked locally that cooler/zoomify and deeptools/plotcorrelation pass on Singularity

**Comment by matthdsm** [comment]
Great, LGTM then!

**Pull request merged**
