### PR TITLE
add stub for bwa index

### PR DESCRIPTION
**Pull request by ramprasadn**
## PR checklist

This PR adds a stub section for bwa/index

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by ramprasadn** [comment]
Tests are failing because of issues in the fgbio_create_umi_consensus subworkflow. The subworkflow calls fgbio's fastqtobam with two input channels, but the module only takes one. I haven't worked with fgbio so I don't know if I should remove the second channel in the subworkflow or add one to the module. Any ideas @lescai (Tagging you here since the subworkflow seems to have come from you 😄)?

**Review by maxulysse — APPROVED** [review]

**Review by maxulysse — CHANGES_REQUESTED** [review]
actually needs to figure out the issue with the tests...

**Comment by maxulysse** [comment]
@ramprasadn can you sync your branch, that should solve the issue now.
We also added meta map to bwa index, you might need to update the stub part to reflect that as well

**Comment by ramprasadn** [comment]
Awesome! Thanks, @maxulysse!

**Pull request merged**
