### PR TITLE
add module for panaroo, fix pirate tests

### PR DESCRIPTION
**Pull request by rpetit3**
## PR checklist

Closes https://github.com/nf-core/modules/issues/1443

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

 I opted for `panaroo/run` because panaroo has a few other sub-commands that might be added in the future. I also cleaned up some lingering comments in the PIRATE test `main.nf`

### CODE REVIEW

**Comment by rpetit3** [comment]
Pirate conda is failing with this:

```
 - ERROR: extract_feature_sequences.pl failed
```

Going to try pinning a specific build. Haha honestly didn't mean for this to turn into a new module and fix for old module!

**Comment by rpetit3** [comment]
Had to pin bioperl to 1.7.2. The containers are not affected by this due to having 1.7.2

**Comment by rpetit3** [comment]
Pirate issue is addressed here: https://github.com/nf-core/modules/issues/1094

**Review by Emiller88 — APPROVED** [review]
LGTM!

**Pull request merged**
