### PR TITLE
See if ngscheckmate is passing tests 

### PR DESCRIPTION
**Pull request by SPPearce**
This PR is to see if ngscheckmate fails tests on the CI - for some reason it was on #4118.

### CODE REVIEW

**Comment by muffato** [comment]
Hi @SPPearce : the failure comes the _sub-workflow_ https://github.com/nf-core/modules/tree/master/subworkflows/nf-core/bam_ngscheckmate , not the _module_.

PS: It's not the only sub-workflows that uses the module. Check the other ones too

**Comment by SPPearce** [comment]
> Hi @SPPearce : the failure comes the _sub-workflow_ https://github.com/nf-core/modules/tree/master/subworkflows/nf-core/bam_ngscheckmate , not the _module_.
> 
> PS: It's not the only sub-workflows that uses the module. Check the other ones too

Aaah, thank you. I didn't notice that!

**Comment by SPPearce** [comment]
(I made the subworkflow as well as the module, so I should have thought about it)

**Review by muffato — COMMENTED** [review]
I understand removing the md5sums of the _bcftools_ file in the _ngscheckmate_ module: it's the ngscheckmate files that matter.

However, bcftools is an integral part of the sub-workflow and the VCF files are even listed as output channels. Why are you removing their md5sums ?

**Comment by SPPearce** [comment]
I have added a `contains` check for the vcf files now.

**Comment by SPPearce** [comment]
> > I have added a `contains` check for the vcf files now.
> 
> Hi @SPPearce : I don't see this `contains` check. Neither on GitHub nor in my terminal (I'm doing `git diff 51bcd821a..5ca6c5222`, `51bcd821a` being the `master` commit you merged into your branch, `5ca6c5222` being the latest commit on your branch).

🙈 helps if I actually push the changes I made locally...

**Review by muffato — APPROVED** [review]

**Comment by muffato** [comment]
All good, thanks !

**Comment by SPPearce** [comment]
Thanks @muffato !

**Pull request merged**
