### PR TITLE
add mudskipper/index and mudskipper/bulk

### LINKED ISSUE #4344: new module: mudskipper/index and mudskipper/bulk
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

### PR DESCRIPTION
**Pull request by anoronh4**
Adding tools from mudskipper

## PR checklist

Closes #4344 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by Emiller88 — APPROVED** [review]
Looks great!

Two things if you have time:
1. Can you create an `environment.yml` instead of the package in the `conda` line? 
2. Could you rewrite the tests in nf-test?

If you can't do either, no worries, we'll just make an issue to track!

**Comment by anoronh4** [comment]
@Emiller88 how do i get the boiler plate nf-test files? i am using nf-core v2.10, is it in the dev copy? maybe an overall guide on how to add these new conventions. i can do the environment.yml pretty easy i think but that was actually auto-generated by the tools :D

**Comment by Emiller88** [comment]
No I don't think it's out yet 😬 

Here's a guide on how to covert them, it's pretty quick! https://nf-co.re/events/2023/bytesize_converting_pytest_modules_to_nf-test#bytesize-converting-pytest-modules-to-nf-test

**Comment by anoronh4** [comment]
@Emiller88 thanks, i'll have to dig into that some time but to be honest i'm a bit short on time and don't think i'll be able to get to it for a while. i'm 15 minutes in and not sure how i would write the setup block if i have more than one module in it (which is the case for mudskipper/bulk). can you create an issue to track it for now? 

i did update the conda files, however.

**Pull request merged**
