### PR TITLE
Add antismash

### LINKED ISSUE #872: new module: antiSMASH
I think it would be good to have a module for [antiSMASH](https://bioconda.github.io/recipes/antismash/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

### PR DESCRIPTION
**Pull request by jasmezz**
## PR checklist

Closes #872 

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by rpetit3** [comment]
Excited to see this! I wonder if trying different test data would help

```
INFO     10/11 17:30:43   Parsing input sequence 'genome.fna.gz'
INFO     10/11 17:30:45   No genes found, skipping record
INFO     10/11 17:30:45   No genes found, skipping record
```

**Comment by rpetit3** [comment]
If a GenBank file is actually needed for the test, I have a few you can try. If these pass we can work on getting a genbank file into the test-datasets repo.

```
https://github.com/bactopia/bactopia-tests/raw/main/data/species/portiera/genome/GCF_000292685.gbk
https://github.com/bactopia/bactopia-tests/raw/main/data/species/portiera/genome/GCF_000292685.gbk.gz
```

**Review by jfy133 — COMMENTED** [review]
Started but will have to continue later

**Comment by jfy133** [comment]
TODO:

- Update output channels to define which are optional or not (presumably whether input is annotated or not)
- Add second test that runs PROKKA first so we can try on unannotated FASTA input (and get the optional output files)

**Comment by jfy133** [comment]
TODO: re-add the optional output files

**Pull request closed without merging**
