### PR TITLE
Module update `fargene`: add output channel `hmm_genes`

### PR DESCRIPTION
**Pull request by jasmezz**
This add the `hmm_genes` output channel to the fargene module. This is required for being able to select the correct files for parsing ARG hits by hAMRonization (downstream summary tool).

More specifically: We want only files starting with `retrieved-genes-` be selected as input for hAMRonization (see [documentation](https://github.com/pha4ge/hAMRonization?tab=readme-ov-file#usage)):
image

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by sguizard — APPROVED** [review]
LGTM

**Review by jfy133 — CHANGES_REQUESTED** [review]
This looks off to me, firstly no test changes, but you have a whole new channel,

Also here you will duplicate the `out` files in both channels, which I don't think this makes sense. 

There is a glob exclude pattern we can use

**Comment by jfy133** [comment]
OK I see now the tests in the first place were poor...

**Comment by jfy133** [comment]
And GRRRR that you can't exclude with globs properly with :shakesfist:

**Review by jfy133 — APPROVED** [review]

**Pull request merged**
