### PR TITLE
Run prettier on conda envs

### PR DESCRIPTION
**Pull request by Emiller88**
- style: Run prettier
- style: Clean up conda package names

Follow up to https://github.com/nf-core/modules/pull/4079

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Comment by SPPearce** [comment]
Not seen [this error](https://github.com/nf-core/modules/actions/runs/6635360127/job/18030179941?pr=4225) before:
`  java.nio.channels.OverlappingFileLockException`
is that related to the conda environment change?

**Review by i-pletenev — APPROVED** [review]

**Comment by nvnieuwk** [comment]
Let's get this one merged ASAP because it's holding up all other PRs :grin:

**Review by mirpedrol — APPROVED** [review]
changes in this PR LGTM :)

**Comment by Emiller88** [comment]
> Could be that we need to add a name to environment.yml? 

@mirpedrol Ahhhh, great catch. I didn't include them because I couldn't get the naming scheme of the enviroment yamls right because conda doesn't allow `/` in the env name. Making an issue!

**Pull request merged**
