### PR TITLE
module: deeptrio

### PR DESCRIPTION
**Pull request by abhi18av**
## PR checklist

Closes https://github.com/nf-core/modules/issues/568 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `<SOFTWARE>.version.txt` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by abhi18av** [comment]
Hi @grst , aplogies because of lack of activity here.

I'm still waiting for the usage pattern to emerge on the sarek workflow based on https://github.com/nf-core/sarek/pull/394, and as soon as I have more clarity, I'd finalize this and get this merged.

**Comment by grst** [comment]
No worries, I was actually just trying to re-trigger the CI which got stuck
somehow

**Comment by abhi18av** [comment]
Ah, okay. Got it 👍

**Comment by grst** [comment]
Getting your branch up-to-date with the latest master did the trick, the CI ran through finally.

**Comment by matthdsm** [comment]
Hi there!

We've noticed there hasn't been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we'll close your PR in about 2 weeks

Cheers
the nf-core maintainers

**Pull request closed without merging**
