### PR TITLE
New modules added: issues #200 and #310

### LINKED ISSUE #200: new module: gatk4/genotypegvcf
I think it would be good to have module for [gatk4](https://bioconda.github.io/recipes/gatk4/README.html)

### PR DESCRIPTION
**Pull request by santiagorevale**
## PR checklist

Closes #200 and #310.

Added new modules: GATK4 genotypegvcfs (#200) and indexfeaturefile (#310).

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [X] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [X] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by santiagorevale** [comment]
@GCJMackenzie, your changes doesn't work straight away and we would be needing to test that implementation. Currently, the module the way it is is working. So I believe we should go ahead with this PR and then make any required changes.

**Comment by lescai** [comment]
Hi @santiagorevale I understand your concerns, and I'm very grateful for the work you put on this module, which is very important to me. 
I am very much in favour of things "thought through": that is why this module seems half-baked to me. I don't see much sense in submitting a PR, when development is missing a key element that guidelines identify as "the preferred tool", and say the other functionality "is provided only as a backup solution for people who cannot use" it (quoting GATK here). 

The lack of this functionality has been highlighted during the development of this module, well before the PR was submitted, as can be seen in the conversation accompanying the issue: doesn't seem to me  we're "throwing in some changes during the PR". Unfortunately, those proposals weren't really taken into account.

Test data are available, and the the other module you mention is ready too.
The exciting part of this community is that we can help each other, and it's perfectly normal one doesn't have time to address all issues: I'm happy to help, and @GCJMackenzie Ph.D. is 100% on this.
So why don't we work together, and make sure the module adheres to the guidelines?

**Comment by santiagorevale** [comment]
@GCJMackenzie can you find me on the nf-core slack later? i have a few questions we could discuss there.

**Comment by santiagorevale** [comment]
I'm sorry, inexperienced mistake. I believe I did the wrong rebase and now I'm having a lot of commits that are not mine and I don't know how to fix it. I'm closing this PR and I'll be re-forking and re-submitting it.

**Pull request closed without merging**
