### PR TITLE
remove deprecated test tags

### PR DESCRIPTION
**Pull request by KevinMenden**
Remove all the deprecated test tags.

### CODE REVIEW

**Review by JoseEspinosa — APPROVED** [review]
LGTM

**Comment by KevinMenden** [comment]
Seems like I broke some tests though 🤔

**Comment by KevinMenden** [comment]
thanks for the review @JoseEspinosa !

**Comment by JoseEspinosa** [comment]
> thanks for the review @JoseEspinosa !

Was just about to highlight it... Seems that relaunching of in principle working modules always come with surprises :cry:

**Comment by KevinMenden** [comment]
Damnit 😠  well I'll try to fix those then ....

**Comment by KevinMenden** [comment]
Okay I think I fixed most tests.
`star/align` and `kallistobustools/ref` are still failing because they are missing the test data ... I've put them on my list, but @FloWuenne is working on that anyway and already has some test data I think, we just have to switch the paths at some point. Might be something for another PR.
STAR is basically waiting for human data as well.

**Comment by KevinMenden** [comment]
ah I forgot `yara/mapper`

**Comment by KevinMenden** [comment]
okay now unicycler is failing too, no idea what happened there ... :/ aaah I thought I just change the tags! 🤦

**Pull request merged**
