### PR TITLE
add FastQC output validation and md5 checksum hash checks

### PR DESCRIPTION
**Pull request by stevekm**
Added a method to expand unit testing by validating the output of the Nextflow module process

### CODE REVIEW

**Comment by stevekm** [comment]
@ewels @drpatelh here is an updated method for unit testing that I came up with, let me know what you think. If this works well, then maybe we can move the checksum function into a common location so we can use it in the other unit test Nextflow scripts more easily.

**Comment by ewels** [comment]
This is beautiful! ❤️  Exactly the kind of thing that I had in mind..

Generally I've been saying that modules should be kept totally isolated, but for the testing yes - I think that we can have a shared set of functions like this somewhere in the repo root that all test scripts can use ✅

**Comment by ewels** [comment]
Would you mind changing this `*` to a `**` here please:

https://github.com/nf-core/modules/blob/4ee6da3a34f64a81075b11e5c115046377c41a2a/.github/workflows/fastqc.yml#L5

I think that should make the tests trigger properly then we can see this run on GitHub Actions..

**Comment by ewels** [comment]
hah, that didn't work because the `pull_request` event is taken from the head repo.

https://github.com/nf-core/modules/blob/4ee6da3a34f64a81075b11e5c115046377c41a2a/.github/workflows/fastqc.yml#L3-L5

Hopefully this will enable the tests on push properly, which will then run on your fork and show up on this PR:

```diff
- push: {} 
+ push:
+   paths: software/fastqc/**
 pull_request: 
   paths: software/fastqc/**
```

If that doesn't work then we can fix it separately rather than spamming you on this PR with an unrelated issue... 🤔

**Comment by stevekm** [comment]
I can also add some examples for validating the number of lines as well ([examples here](https://github.com/stevekm/nextflow-demos/blob/master/filter-channel/main.nf#L35-L61)), and maybe a few other things I come up with

**Comment by stevekm** [comment]
@ewels where do you see if the GitHub actions thing worked or not?

**Comment by stevekm** [comment]
related to #4

**Comment by ewels** [comment]
@stevekm - I'm looking for actions to be triggered on your fork here: https://github.com/stevekm/nf-core-modules/actions

Any actions triggered on this branch should then show up in this PR as well I think.

At the moment there's nothing there, which I think is because `push: {}` doesn't match any `push` event.

**Comment by ewels** [comment]
🤦 it didn't trigger because it didn't change those files _in that last commit_

Ok I think it's all correct now anyway, should work for future PRs - thank you! 👍

**Comment by ewels** [comment]
Ah interesting, there was a syntax error in the FastQC CI YML file: https://github.com/nf-core/modules/actions/runs/171381302

We need to rewrite this so that we have one workflow file for all modules, not needing to make one for each...

**Pull request merged**
