### PR TITLE
Add params.test_data_base and keep path coherent

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by maxulysse** [comment]
cf https://github.com/nf-core/sarek/pull/909

**Comment by maxulysse** [comment]
Ran:
```
TMPDIR=~ PROFILE=docker pytest --tag cnvkit/batch --symlink --kwdof --git-aware --color=yes
```
Locally without issue

**Review by Emiller88 — APPROVED** [review]
Love it!

**Comment by FriederikeHanssen** [comment]
Sorry, I think I missed some major issues :/ . Why is this better then having the path in the header?

**Comment by maxulysse** [comment]
> Sorry, I think I missed some major issues :/ . Why is this better then having the path in the header?

Just easier to modify.
Let's say you want to run the test locally.
Just download the files you need, and you just need to set the `params.test_data_base` and you're good to go

**Review by matthdsm — APPROVED** [review]
me likey!

**Review by nvnieuwk — APPROVED** [review]

**Comment by FriederikeHanssen** [comment]
> > Sorry, I think I missed some major issues :/ . Why is this better then having the path in the header?
> 
> Just easier to modify. Let's say you want to run the test locally. Just download the files you need, and you just need to set the `params.test_data_base` and you're good to go

alright, makes sense

**Pull request merged**
