### PR TITLE
CNVKit 0.9.10 update

### LINKED ISSUE #3544: CNVkit batch module went through an uncontrolled pandas upgrade which makes it crash
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

When using the module `cnvkit/batch` with conda the following error is raised:
```
ImportError: cannot import name 'Int64Index' from 'pandas'
```

I found that the version 0.9.9 from May 2021 of cnvkit is defined in this line https://github.com/nf-core/modules/blob/master/modules/nf-core/cnvkit/batch/main.nf#L5, but the pandas version in the dependency tree is not controlled, thus as of today latest pandas 2.0.2 gets installed which is incompatible and raises the error above.

An upgrade to cnvkit 0.9.10 seems to fix the issue.

### Command used and terminal output

```console
I used this module programmatically.
```

### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by adamrtalbot**
- upgrade CNVkit to 0.9.10
- homogenise keywords of all CNVkit modules
- Add samtools dependency to bam2seqz module of sequenzautils
- Update cnvkit to 0.9.10

## PR checklist

Fixes #3544
Closes #3545 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by SPPearce** [comment]
Is samtools a required dependency for some parts of cnvkit to work?
If so, why don't we add samtools to the bioconda recipe?

**Comment by SPPearce** [comment]
Actually I don't quite understand what is going on here. The conda requirements for most of the tools are cnvkit and samtools, but docker/singularity are just building off the cnvkit recipe, so why do they need samtools?

**Comment by priesgo** [comment]
I guess we can close this https://github.com/nf-core/modules/pull/3545 as a duplicate of this PR?

**Review by priesgo — APPROVED** [review]
LGTM

**Comment by priesgo** [comment]
I think this is ready to go!

**Pull request merged**
