### PR TITLE
adding log to hifiasm outputs

### PR DESCRIPTION
**Pull request by mbeavitt**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

This change outputs the stderr of hifiasm to a .log file, and adds it to the named emitted files. Log file is compatible with MultiQC, and this module can now be used with it.

### CODE REVIEW

**Review by FriederikeHanssen — APPROVED** [review]

**Review by FriederikeHanssen — CHANGES_REQUESTED** [review]
Can you add the new output to the meta.yml?

**Comment by mbeavitt** [comment]
Of course, will do

**Comment by mbeavitt** [comment]
Should I add myself to the authors..?

**Comment by FriederikeHanssen** [comment]
> Should I add myself to the authors..?

sure why not. You will be pinged as maintainer of the module on reviews then :)

**Comment by mbeavitt** [comment]
@FriederikeHanssen Updated! Thanks again for all your help walking me through this :)

**Review by nvnieuwk — COMMENTED** [review]
Can you also add a stub to this modules while you're at it?

**Comment by mbeavitt** [comment]
Sure!

**Review by nvnieuwk — APPROVED** [review]
LGTM!

**Review by FriederikeHanssen — APPROVED** [review]
Looks 😊 congrats on your first module 🚀

**Pull request merged**
