### PR TITLE
Migrate `gatk4/mutect2` tests to nf-test

### LINKED ISSUE #5242: migrate `gatk4 mutect2` to nf-test
### Is your feature request related to a problem? Please describe

pytest -> nf-test migration

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pawelciurkaardigen**
## PR checklist

Closes #5242 

Migrating gatk4 mutect2 to nf-test

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [x] `nf-core modules test <MODULE> --profile singularity`
    - [x] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by pawelciurkaardigen** [comment]
Some tests are failing in CI. I'm going to try to fix them.

**Comment by pawelciurkaardigen** [comment]
merge stucked in queue:
don't know what to do with that
image

**Review by mauro-saporita — APPROVED** [review]
looks good

**Comment by pawelciurkaardigen** [comment]
Thank you very much @adamrtalbot for taking care of this

**Pull request merged**
