### PR TITLE
chore: update fgbio version

### PR DESCRIPTION
**Pull request by znorgaard**
This PR updates the version of fgbio used in all fgbio modules to version 2.4.0. It also switches from biocontainers to Seqera containers.

Wave containers were created manually, action requires secrets which don't get passed for repo fork PRs.

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [X] Use Seqera Containers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [x] `nf-core modules test <MODULE> --profile singularity`
    - [x] `nf-core modules test <MODULE> --profile conda`

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Review by mashehu — CHANGES_REQUESTED** [review]
you also need to update the snapshots

**Comment by znorgaard** [comment]
> you also need to update the snapshots

Update now.

**Comment by znorgaard** [comment]
Looks like just the wave build actions are failing (expected because secrets aren't passed to forked branches for the actions).

**Comment by mashehu** [comment]
@edmundmiller any ideas?

**Comment by edmundmiller** [comment]
> @edmundmiller any ideas?

Don't bump versions from a fork? 😆 

You'll probably have to close this PR and make a new one if you want the wave CI to run 😞 It's not something we can "fix". It's a feature, not a bug.


It should skip the matrix generation in this case, so I tried updating the branch.

Another rationale for ignoring these is kicking off these version bump PRs, which should be done through #4211 and then modified.

**Comment by edmundmiller** [comment]
> I don't mind the wave build automation not running/passing, but adding a check to make sure those actions don't trigger on PRs from forks seems like a good idea. No one likes an unnecessary ❌.

Completely agree, I was just joking if you want the version to get bumped. I tried my best to get the wave jobs skipped if it was coming from a fork to avoid any confusion and thought we had that ironed out 🫠 
Thanks for taking a look at it! I tried a couple of different `if`'s but I think the `owner == 'nf-core'` should actually catch it.

> Renovate definitely seems like a nice tool to manage these version bumps, but it doesn't look like it's currently detecting conda environment files intentionally or not (which is where fgbio and many other module versions are currently set).

For context it's off the version bumps are off right now because they were overwhelming and not automated. The channels will prevent it getting picked up until #5400 gets merged.

> can someone make me a contributor here

Sent you an invite!

**Comment by znorgaard** [comment]
>Thanks for taking a look at it! I tried a couple of different if's but I think the owner == 'nf-core' should actually catch it.

No luck! You'd think they'd make this easy. I'll close this fork PR and get a regular one opened.

**Pull request closed without merging**
