### PR TITLE
Mega conda environment update: Remove `name` and `defaults`

### PR DESCRIPTION
**Pull request by ewels**
Big PR to remove `defaults` and `name` from conda `environment.yml` files.

Done in discussion with the maintainers team to do in one go, ignore failing tests for now.

Replaces:
* https://github.com/nf-core/modules/pull/5802
* https://github.com/nf-core/modules/pull/5838
* https://github.com/nf-core/modules/pull/5839
* https://github.com/nf-core/modules/pull/5840
* https://github.com/nf-core/modules/pull/5841
* https://github.com/nf-core/modules/pull/5842
* https://github.com/nf-core/modules/pull/5843

This could cause quite a lot of difficulties, apologies for that. However this is needed now to avoid linting failing for everything with the upcoming tools v3 release.

CI is already failing for all modules on the modules repo, because the CI here uses the nf-core/tools dev branch.

Relevant Slack thread: https://nfcore.slack.com/archives/C07BDPBPLG3/p1725557714638149

> [!NOTE]
> The only part I _haven't_ included is this diff from @edmundmiller's PR #5802 in `.github/workflows/test.yml`:
> ```diff
> - profile: [conda, docker, singularity]
> + # BUG conda and pytest-workflow won't be supported
> + # https://github.com/nextflow-io/nextflow/issues/4464#issuecomment-2160348935
> + profile: [docker, singularity]
> ```
> Not sure if this is needed or not, happy to add.

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Review by Joaodemeirelles — APPROVED** [review]

**Review by mahesh-panchal — APPROVED** [review]
Quick check with 
```
find -name "environment.yml" -exec grep name {} +
find -name "environment.yml" -exec grep default {} +
```
found nothing.

**Comment by ewels** [comment]
Ok just repeated and forced push, as realised that I had somehow failed to update to master before doing this and had a bunch of merge conflicts. So totally different but hopefully the same.

**Comment by maxulysse** [comment]
prettier is failing, and I'd like to avoid that :pray: pretty please

**Comment by mahesh-panchal** [comment]
You might need to strip blank lines

**Comment by ewels** [comment]
@maxulysse - Prettier was failing in the specific CI test but not in pre-commit, which I thought was weird. Looks like there was a version mismatch, just pushed a commit to make the CI job match.

**Comment by ewels** [comment]
ok.. pre-commit prettier isn't checking anything? 🤔  Ah probably because I didn't edit any files in _that commit_...?

CleanShot 2024-09-06 at 09 57 40@2x

**Comment by ewels** [comment]
Prettier is now passing ✅

**Review by apeltzer — APPROVED** [review]
Did some bash / grep checks myself too and couldnt find anything - LGTM

**Review by jonasscheid — APPROVED** [review]

**Pull request merged**
