### PR TITLE
Add plasmidid module

### LINKED ISSUE #332: plasmidid
`plasmidid` module is needed for [viralrecon DSL2](https://github.com/nf-core/viralrecon/issues/149) implementation.
Bioconda link to [plasmidid](https://bioconda.github.io/recipes/plasmidid/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [X] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

### PR DESCRIPTION
**Pull request by JoseEspinosa**
Add `plasmidid` module as a [requirement](https://github.com/nf-core/viralrecon/issues/149) of `nfcore/viralrecon` DSL2 implementation.

## PR checklist

Closes #332  

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `<SOFTWARE>.version.txt` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by JoseEspinosa** [comment]
I created the contig file using `minia`, what do you think @drpatelh should we add a `contig` file to the test dataset? I found it kind of dirty since this in fact is an intermediate file...
Also, this PR is just drafted since the container version should be updated when issues with Circus dependencies get solved.

**Comment by JoseEspinosa** [comment]
I have to test for more output files, but there are too many I will try to choose the more relevant ones

**Comment by JoseEspinosa** [comment]
Ping @drpatelh, ready for review!

**Review by drpatelh — APPROVED** [review]
😍

**Comment by drpatelh** [comment]
Nothing to see here.

**Pull request merged**
