### PR TITLE
Update output to use type dir for compatibility with tes.

### LINKED ISSUE #6644: update module: sratools /prefetch
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

### PR DESCRIPTION
**Pull request by vsmalladi**
## PR checklist

Closes #6644 

- [X] This comment contains a description of changes (with reason).

### CODE REVIEW

**Comment by SPPearce** [comment]
Why is this necessary?

**Comment by vsmalladi** [comment]
For Ga4gh_tes plugin it’s necessary to explicitly call out directories

**Review by SPPearce — APPROVED** [review]

**Comment by ewels** [comment]
We should probably try to do this systematically for all modules 🤔 In this case it was already annotated in the meta yaml:

https://github.com/nf-core/modules/blob/a25abe62ccf3fe3767d2449d8322a35ab62844e0/modules/nf-core/sratools/prefetch/meta.yml#L44

**Comment by vsmalladi** [comment]
> We should probably try to do this systematically for all modules 🤔 In this case it was already annotated in the meta yaml:
> 
> https://github.com/nf-core/modules/blob/a25abe62ccf3fe3767d2449d8322a35ab62844e0/modules/nf-core/sratools/prefetch/meta.yml#L44

I agree we should look at doing this systematically. How should we go about doing this?

**Comment by ewels** [comment]
> How should we go about doing this?

I think @mirpedrol might have some magic in nf-core/tools. See recent work about updating the meta map, this is all autogenerated from the Nextflow code. Should be possible to do this as well I guess?

see the above issue to track this specific issue.

**Comment by mirpedrol** [comment]
I didn't take this into account but I can add it. 
The `meta.yml` is generated  from `main.nf` information, so we could detect this `type: 'dir'` in the input channel and add `type: directory` to the meta.
In the opposite situation where we already documented the `meta.yml` but we didn't add the information to `main.nf` I would do it with a separate script for now, we won't need it in the long term if we start using the type in the `main.nf`. Sounds good?

**Pull request merged**
