### PR TITLE
Update CADD to version 1.6.post1 and include Smk environments in containers

### LINKED ISSUE #4345: [FEATURE] Container image for CADD with dependencies included
### Is your feature request related to a problem? Please describe

When using the cadd module, it has to download the environments used by the built-in snakemake pipeline every time the process is run. The dependenices included in the container image are not used for the steps in the internal snakemake pipeline, they are just used to allow cadd-scripts to run and start its pipeline.

There are several problems with this:
* The module can't be used in an offline environment, because CADD relies on online conda repositories to download the requirements for each of its annotation steps
* Not all singularity / apptainer versions seem to support the --writable option, and crash when trying to download the environments to the container filesystem
* It's inefficient use of time and bandwidth to download the environments for every instance of the CADD process

### Describe the solution you'd like

A Dockerfile incorporating Snakemake's --conda-create-envs-only mode can be used to pre-load the environments into the container image

### Describe alternatives you've considered

I didn't find any alternative images for CADD

### Additional context

I've created an alternative Dockerfile for CADD that seems to work: https://github.com/fa2k/raredisease-configs/blob/main/scripts/cadd_Dockerfile. The image is hosted in Docker Hub in my user account: https://hub.docker.com/r/paalmbj/cadd.

The container definitions have to be changed slightly. I've also added `--env XDG_CACHE_HOME=/tmp/.cache` - otherwise it will try to write to the home dir, which may not be available.
https://github.com/fa2k/raredisease/blob/cadd-docker-image/modules/nf-core/cadd/main.nf

I have submitted it as an issue in BioContainers, https://github.com/BioContainers/containers/issues/528, but didn't make a PR there yet.

### PR DESCRIPTION
**Pull request by fa2k**
The commit makes two changes:

* For containers - uses a new container image from BioContainers. The main change is related to the fact that CADD will download conda environments when it's being run. The current container images are straight conversions from conda, and will download the environments into the conda envs path in the container filesystem. The new container in this PR already comes with the environments pre-bundled, which may have advantages for compatibility, efficiency and for running off-line. The new container image is not in Galaxyproject because it's not based on a conda package - so I use the biocontainers name for all container systems.
* It uses a new CADD-scripts version: 1.6.post1. This contains some bugfixes in the code, but uses the same CADD annotation data (https://github.com/kircherlab/CADD-scripts/releases). A new bioconda package is just available for this CADD-scripts version, so both conda and containers use the same version.

## PR checklist

Closes #4345 

- [x] This comment contains a description of changes (with reason).
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
 
All tests skipped successfully.

### CODE REVIEW

**Comment by fa2k** [comment]
Sorry this is not ready yet. The tests are failing, not skipping. Will check it.

**Comment by fa2k** [comment]
The updated conda package isn't in bioconda, so it doesn't work right now. Maybe we can wait until the package is in bioconda. The pull request in bioconda was merged, but maybe it takes a bit of time? https://github.com/bioconda/bioconda-recipes/pull/44775

**Comment by fa2k** [comment]
I changed the environment file so it gets conda from conda-forge instead of anaconda. This was based on trial an error, getting the conda environment to build. I can't test it properly with conda, but the tests do pass.

It's ready for review.

**Comment by fa2k** [comment]
It turns out that I had made a change to the mamba version, and that's why I couldn't use the same conda version as before. I don't remember the reasoning for this, and I've reverted the mamba and conda versions so they are the same as before.

**Comment by fa2k** [comment]
I have merged the latest changes from master. This is ready for review.

**Review by SPPearce — APPROVED** [review]

**Comment by SPPearce** [comment]
Sorry that this has taken so long for anyone to actually review. You can add the "Ready for Review" tag, or even better ask on the nf-core slack request-review channel to get eyeballs on PRs.

**Comment by fa2k** [comment]
Thanks for the review and explanation, I'll make sure to do one of these next time :)

**Pull request merged**
