### PR TITLE
Apply editorconfig and enable CI again

### LINKED ISSUE #77: Add Editor Config lint back in
I commented out the Editor config linting https://github.com/nf-core/modules/pull/76/commits/082c582258fc16c2afc32f94af157ac8faaf12cc but it would be good to fix and add this back in. Possibly in one go to get all of the tests passing again.

### PR DESCRIPTION
**Pull request by Emiller88**
Closes #77

### CODE REVIEW

**Review by grst — APPROVED** [review]
LGTM!

(Obviously, I didn't go through the huge changed chunks line by line - but these should only be formatting, right?)

**Comment by Emiller88** [comment]
This might actually be a better option https://github.com/github/super-linter, it would cover all of our bases then. I think if I can get https://github.com/nf-core/tools/issues/797 approved, then we could unify all of our linting.

**Comment by drpatelh** [comment]
Oops. Did I cause all of these merge conflicts? 🤦🏽 Would it be easier to fix this in another PR @Emiller88 ? Sorry...

**Comment by Emiller88** [comment]
No it's just because it's 70 commits behind master now and no rebase is going to save that without going through it interactively. I actually don't know if 656e64d9dd30221880e5b769367d7eb5918e24ac is still right so I'll just rewrite it and force push. :stuck_out_tongue:

**Comment by Emiller88** [comment]
Alright that was way too difficult to get working for personal reasons (yubikey not signing commits, laptop not syncing to my desktop, lots of force pushing) but it's finished now!

**Comment by drpatelh** [comment]
Amazing! Thank you @Emiller88 😎

**Pull request merged**
