### PR TITLE
bcftools isec input can be bcf or bcf.gz as well as vcf.gz

### PR DESCRIPTION
**Pull request by RuthEberhardt**
bcftools isec input can be bcf or bcf.gz as well as vcf.gz so using ${vcfs} instead of *.vcf.gz allows the user to use any of the three compatilble file types for this function

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by tstoeriko** [comment]
Looks reasonable to me in general. Could you include a test for one of the input types that would be newly allowed after this change? And it would be really nice to add a stub and stub test as well.

**Review by tstoeriko — CHANGES_REQUESTED** [review]
Looks reasonable to me in general. Could you include a test for one of the input types that would be newly allowed after this change? And it would be really nice to add a stub and stub test as well.
The tests aren't passing right now because the snapshot needs an update, this should be easily fixed by running nf-core modules test -u bcftools/isec.

**Comment by SPPearce** [comment]
@RuthEberhardt , are you able to address these comments, do you need a hand?

**Comment by RuthEberhardt** [comment]
@SPPearce  I would certainly appreciate a hand, I am new to nextflow and don't know much about tests.
I see there are some tests under modules/nf-core/bcftools/isec/tests but there are also tests for some bcftools functions under modules/tests/modules/nf-core/bcftools so I am not sure of the correct place to put tests, how to write them and what needs testing. I also don't know what a stub or stub test are - please excuse my ignorance on this! Thank you in advance for any help.

**Comment by SPPearce** [comment]
> @SPPearce I would certainly appreciate a hand, I am new to nextflow and don't know much about tests. I see there are some tests under modules/nf-core/bcftools/isec/tests but there are also tests for some bcftools functions under modules/tests/modules/nf-core/bcftools so I am not sure of the correct place to put tests, how to write them and what needs testing. I also don't know what a stub or stub test are - please excuse my ignorance on this! Thank you in advance for any help.

Ok, I can help.
We are in the midst of a long migration from our previous testing regime (`pytest`) to use a nextflow-specific one (`nf-test`). The pytest files exist under a path like `tests/modules/nf-core/bcftools/isec`, whereas `nf-test `files now live with the other files in `modules/nf-core/bcftools/isec/tests`. If a module has already been migrated it won't have anything under `tests/modules`, which is the case for this module, so you only need to worry about the files in `modules/nf-core/bcftools/isec/tests`.
A `stub` is a bit of code that can be used to check that module is correctly setup in a pipeline, with input/output/container etc, without actually running the tool itself. Generally this means that you use the `touch` command to make empty files with the relevant output filenames.
I have looked at the output of the other test, and made files with the same name as those in the stub.
I've also copied the test, added `options "-stub"` (and changed the name of the test) to make a stub test, to check that is working ok.
I'll then run `nf-core modules test bcftools/isec --update` to update the "snapshots" of the tests, i.e. checking that module is working and generating the same output every time.

**Comment by SPPearce** [comment]
To add a test with a bcf file, I went to [the test data config](https://github.com/nf-core/modules/blob/master/tests/config/test_data.config), and saw that there was a bcf file there, as well as an uncompressed vcf file, so I have added another test using these instead.

**Comment by SPPearce** [comment]
> To add a test with a bcf file, I went to [the test data config](https://github.com/nf-core/modules/blob/master/tests/config/test_data.config), and saw that there was a bcf file there, as well as an uncompressed vcf file, so I have added another test using these instead.

Ok, scratch that, I tried that and got told that uncompressed files aren't supported for this tool.

**Comment by tstoeriko** [comment]
> > To add a test with a bcf file, I went to [the test data config](https://github.com/nf-core/modules/blob/master/tests/config/test_data.config), and saw that there was a bcf file there, as well as an uncompressed vcf file, so I have added another test using these instead.
> 
> Ok, scratch that, I tried that and got told that uncompressed files aren't supported for this tool.

If this is the case, the meta.yml probably should be updated accordingly, right?

**Review by tstoeriko — APPROVED** [review]

**Review by SPPearce — APPROVED** [review]
Thanks for sorting the tbi files @tstoeriko, that'll do fine as a method to exclude them from the md5sums.

**Comment by tstoeriko** [comment]
Considering there's no suitable bcf file in the test data right now, I'd say this PR can be merged. :rocket:

**Comment by SPPearce** [comment]
> Thank you both so much for your help.

No problem. I hope that you understood at least some of what just happened, feel free to ask if there is anything you don't understand.

**Pull request merged**
