### PR TITLE
Add outputs for umitools dedup summary stats

### PR DESCRIPTION
**Pull request by drpatelh**

### CODE REVIEW

**Review by grst — APPROVED** [review]
LGTM!

**Comment by grst** [comment]
hang on... why did pytest workflow not run on this PR? @Emiller88, did you break something :see_no_evil:  :stuck_out_tongue_winking_eye:

**Comment by drpatelh** [comment]
We don't have any tests for this module. QUICK RUNNNNNNNN!

**Comment by Emiller88** [comment]
umitools/dedup was created in the land before tests, cbf8329ffdc0bb4bf4d28d2f522c3d93be7aff2e :laughing:

**Pull request merged**
