### PR TITLE
Samtools version update

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
I assume you'll do bwamem/mem2mem in a separate one?

**Comment by FriederikeHanssen** [comment]
on it already just waiting for: https://github.com/BioContainers/multi-package-containers/pull/2125

**Comment by maxulysse** [comment]
definitively we need to remove the md5sum for the `versions.yml` files.
Why do people do that?

**Comment by maxulysse** [comment]
I'm more concerned about the other files that now have new md5sum

**Comment by FriederikeHanssen** [comment]
> I'm more concerned about the other files that now have new md5sum

I'll inspect them

**Comment by FriederikeHanssen** [comment]
singularity containers are not yet available

**Pull request merged**
