### PR TITLE
untar: need a gnu grep to use -P, also use a consistent tar

### PR DESCRIPTION
**Pull request by pinin4fjords**
## PR checklist

Closes https://github.com/nf-core/modules/issues/2771

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by muffato** [comment]
I'm curious: how did you get an environment where there wasn't `grep` and `tar` in the first place :) ?

**Comment by pinin4fjords** [comment]
> I'm curious: how did you get an environment where there wasn't `grep` and `tar` in the first place :) ?

On my Mac the environment had both. But the '-P' for perl regexes doesn't exist in native Mac `grep`, and the particular module I was fiddling with was passing an option that only applied to the GNU tar, so that was breaking too.

**Review by erikrikarddaniel — APPROVED** [review]
Looks great!

**Comment by pinin4fjords** [comment]
Thanks @erikrikarddaniel !

**Pull request merged**
