### PR TITLE
Update `sourmash` modules to 4.8.4

### PR DESCRIPTION
**Pull request by vmikk**
This PR updates 5 modules related with sourmash (`sourmash/compare`, `sourmash/gather`, `sourmash/index`, `sourmash/sketch`, and `sourmash/taxannotate`)

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by SPPearce — APPROVED** [review]
Why are two of the processes `process_low` and the other three `process_single`?

**Comment by vmikk** [comment]
`Process_single` is used for the steps that does not support multi-threading.

**Comment by SPPearce** [comment]
> `Process_single` is used for the steps that does not support multi-threading.

None of the tools pass the number of cpus as an argument, does the tool just assume it can have all the cores it can see?

**Comment by vmikk** [comment]
Yes, I agree, it would be better to specify number of CPUs explicitly for the tools that support multithreading.
I will update the PR.

**Comment by vmikk** [comment]
Essentially, only `sourmash compare` ([link to manual](https://sourmash.readthedocs.io/en/latest/tutorial-basic.html#compare-many-signatures-and-build-a-tree)) supports multithreading now. For this module, we specify `process_low` resource label and `${task.cpus}`.
For the other modules, `process_single` is used.

**Review by SPPearce — APPROVED** [review]
Yep, that makes sense.

**Pull request merged**
