### PR TITLE
Add default output dir for modules that create indices

### PR DESCRIPTION
**Pull request by drpatelh**
Think I got all of them. This should create a directory e.g. `index/bwa` or `index/bowtie`

### CODE REVIEW

**Comment by drpatelh** [comment]
Ping @aunderwo

**Comment by JoseEspinosa** [comment]
Sorry @drpatelh, I was reviewing it and was going to modify the paths on the PR, should have shout it ... 😢

**Comment by drpatelh** [comment]
No worries! The tests aren't being triggered for some reason 🤔 You fancy creating a separate PR updating these files? Feel free to close this one? I will work on getting the linting passing for the DSL2 pipeline template.

**Comment by JoseEspinosa** [comment]
Sure! Will close this PR when mine is ready.

**Comment by JoseEspinosa** [comment]
After opening the new PR the tests were launched 😠

**Pull request closed without merging**
