### PR TITLE
bump gatk4 version across the board

### PR DESCRIPTION
**Pull request by matthdsm**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by nvnieuwk — APPROVED** [review]

**Comment by matthdsm** [comment]
needs fixin'

- [ ]  applybqsr
- [ ] applybsqrspark
- [ ] calculatecontamination
- [ ] createsomaticpanelofnormals
- [ ] filtermutectcalls
- [ ] genomicsdbimport
- [ ] getpileupsummaries
- [ ] haplotypecaller
- [ ] learnreadorientationmodel
- [ ] markduplicates
- [ ] markduplicatesspark
- [ ] mutect2
- [ ] printsvevidence
- [ ] splitncigerreads

**Review by FriederikeHanssen — APPROVED** [review]

**Comment by matthdsm** [comment]
@nf-core/core, the CI tests keep failing due to GHA being unable to fetch one file or another from the test-data repo.
I'm having the same issues when testing locally.

I did however, check if all inputs are present in the tests (yes) and IMO everything should work.
Do I keep fiddling with the CI until I get it to work? Or should I go ahead and merge?

**Comment by SPPearce** [comment]
> @nf-core/core, the CI tests keep failing due to GHA being unable to fetch one file or another from the test-data repo. I'm having the same issues when testing locally.
> 
> I did however, check if all inputs are present in the tests (yes) and IMO everything should work. Do I keep fiddling with the CI until I get it to work? Or should I go ahead and merge?

Some of the checks are generating output files but have different md5sums (applybqsr, applybqsrspark, markduplicates, markduplicatesspark, splitncigarreads).
HaptolypeCaller seems odd too, giving `AssertionError: `versions.yml` not found in the output directory.` : https://github.com/nf-core/modules/actions/runs/3271044686/jobs/5384544244

**Comment by matthdsm** [comment]
I've no idea, why this happens... I'm regenerating the checksum but get no differences

**Comment by matthdsm** [comment]
CI still failing because of subworkflows
- [ ] gatk_tumor_normal_somatic_variant_calling
- [ ] gatk_create_som_pon
- [ ] gatk_tumor_only_somatic_variant_calling

**Comment by matthdsm** [comment]
The offending subworkflows seem to be legacy case with a bunch of wrong inputs. I've no experience with the tools, so I don't intend to try and fix them here. These should be attended to in another PR IMO.

Opinions?

**Comment by FriederikeHanssen** [comment]
applybqsrsoark has a mismatched checksum, why can that not be fixed?

**Comment by matthdsm** [comment]
ughh.... I already fixed that checksum a couple of times 😞 Seems to be different each time it goes through the CI

**Comment by FriederikeHanssen** [comment]
https://github.com/nf-core/modules/pull/1965#discussion_r999479089 all the version.yml are removed, from here I gather this may not be intentional. might be worth to wait until this is cleared up

**Comment by matthdsm** [comment]
Yep, wanted only to remove the checksum. My regex was ... not so good.

**Comment by matthdsm** [comment]
Tests pass where they need to, checksums seem to be ok this time around. versions.yml were re-added.

Good to merge? (Please say yes)

**Comment by maxulysse** [comment]
@matthdsm Can you list the failed subworkflows in an issue, so we know which one we need to update?

**Comment by matthdsm** [comment]
> @matthdsm Can you list the failed subworkflows in an issue, so we know which one we need to update?

Done!

**Pull request merged**
