### PR TITLE
Add CRAM/index support to NARFMAP

### PR DESCRIPTION
**Pull request by edmundmiller**
- **feat: Add cram/index support to narfmap**
- **chore: Remove singularity image comment**
- **test: Update tests for CRAM**

### CODE REVIEW

**Review by CarsonJM — APPROVED** [review]
I like the regex to automatically detect output format 👌

Just out of curiosity, do you know why this module has a second `.nf.test` file?

**Comment by edmundmiller** [comment]
> I like the regex to automatically detect output format 👌

Thanks, but I can't take credit for it! I think @matthdsm wrote it originally 😬 
 
> Just out of curiosity, do you know why this module has a second `.nf.test` file?

Because I haven't set up proper testing in NARFMAP itself to check for the regression there. 

I personally think it's cleaner than having everything in one test file, there's the basics, and then there are custom regression tests with outside data.

**Comment by poddarharsh15** [comment]
Hi @edmundmiller, Thank you very much for upgrading `dragmap`. I highly appreciate your help.
May I ask if you are planning to integrate this module with `nf-core/sarek` or any other pipeline from nf-core?

**Comment by edmundmiller** [comment]
@poddarharsh15 See https://github.com/nf-core/sarek/pull/1358

However, it looks like it's still segfaulting 😞 How's it going in your tests?

I'm wondering if bioconda turns off the static compilation 🤔

**Comment by maxulysse** [comment]
I add sadness...

**Comment by poddarharsh15** [comment]
> @poddarharsh15 See [nf-core/sarek#1358](https://github.com/nf-core/sarek/pull/1358)
> 
> However, it looks like it's still segfaulting 😞 How's it going in your tests?
> 
> I'm wondering if bioconda turns off the static compilation 🤔

That's sad :(( My tests with the version I mentioned to you on GitHub are working well when I compile it on my workstation. However, when I use it within a conda environment, there is a segmentation fault :((
Based on my observations, it seems the issue might be related to a library within the conda environment, probably the `boost` library versions.

**Comment by edmundmiller** [comment]
Awesome, that's progress then! Makes a lot of sense why I couldn't reproduce it with a locally built binary during development, but the moment I put it in a nf-core pipeline it segfaulted.

**Comment by poddarharsh15** [comment]
Hi @edmundmiller,
If you don't mind, could you please perform a test run using the binary file from the link below? You just need to download it, run `chmod +x dragen-os`, and then execute the command line with `./dragen-os -r $hash/ -1 $L001_R1_001.fastq.gz -2 $L001_R2_001.fastq.gz | samtools view -h -O BAM - > aligned.bam` I want to ensure that the version and file I am using also work on other Ubuntu machines.
Please let me know if you can try it. I hope my request is clear. 🙏 :))
Thank you!

DRAGMAP Release 1.3.1 [https://github.com/gambalab/DRAGMAP/releases/tag/1.3.1](url)

**Comment by poddarharsh15** [comment]
Hi @edmundmiller Sorry to disturb but is there any updates regarding dragmap?? Please let me know thanks :)

**Pull request merged**
