### PR TITLE
Adding back in all input files we had before

### PR DESCRIPTION
**Pull request by FelixKrueger**
This should bring in all the input files we had previously when modules and test-datasets were separate repos.

This discriminates the two folders:

`fasta`
`fastq`

and within the FastQ folder:

`rna`
`dna`
`methylated_dna`

Which we though was a good idea at the time.

### CODE REVIEW

**Comment by ewels** [comment]
We have code linters for everything you know 😉 😆 

Your markdown is BAD AND MUST BE FIXED 💥 

```
modules/tests/data/fastq/methylated_dna/bisulfite-seq_test_data.md:1 MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "### E. coli paired-end test da..."]
modules/tests/data/fastq/methylated_dna/bisulfite-seq_test_data.md:5 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
modules/tests/data/fastq/methylated_dna/bisulfite-seq_test_data.md:20 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
modules/tests/data/fastq/rna/paired_end_RNAseq_test_data.md:1 MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "### Paired-end RNA-seq test da..."]
modules/tests/data/fastq/rna/paired_end_RNAseq_test_data.md:5 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
```

**Comment by drpatelh** [comment]
This is great @FelixKrueger and exactly how we want to organise things! Thanks! What about all the BAM files and stuff you had knocking about too?

**Comment by FelixKrueger** [comment]
The only thing I know (and I've heard this from you) is that **linting** is **meta**

**Comment by FelixKrueger** [comment]
> This is great @FelixKrueger and exactly how we want to organise things! Thanks! What about all the BAM files and stuff you had knocking about too?

I am just working on that.

**Comment by grst** [comment]
Are we ok with the test files, or is it worth reducing the file size futher? Some are >400kb gzipped, and I imagine downsampling them further would still do the job.

**Comment by FelixKrueger** [comment]
> Are we ok with the test files, or is it worth reducing the file size futher? Some are >400kb gzipped, and I imagine downsampling them further would still do the job.

The `SRR*` files are not mine, we could delete them again if no one needs them.

**Comment by grst** [comment]
> The SRR* files are not mine, we could delete them again if no one needs them.

if we have others which fulfil the same purpose, I'd delete them.

**Comment by FelixKrueger** [comment]
Really not sure what to do about all this linting....

**Comment by drpatelh** [comment]
Thanks a bunchly @FelixKrueger ! 😎

**Pull request merged**
