### PR TITLE
Meryl count and meryl histogram migration to nf-test

### PR DESCRIPTION
**Pull request by mahesh-panchal**
## PR checklist

- Adds k-value as mandatory parameter to meryl/count and meryl/histogram
- Migrates pytest to nf-test
- Adds kvalue to genomescope2 nf-test 

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [x] `nf-core modules test <MODULE> --profile singularity`
    - [x] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by rodtheo — APPROVED** [review]
Outstanding! Thanks for updating these modules and corresponding tests.

**Comment by GallVp** [comment]
Hey guys!

Thanks for this module. Is there a reason the `memory=` parameter (https://github.com/marbl/meryl/issues/24#issuecomment-881088631) wasn't added? Should I add it and create a PR?

**Comment by mahesh-panchal** [comment]
Oversight perhaps, but is there a need to limit memory? Is it behaving badly on your systems? If it's not an issue I would just let it use what it can get a hold of, but if you see a need for it, make a PR

**Comment by GallVp** [comment]
It can be an issue because by default it uses all the available system memory.

**Pull request merged**
