### PR TITLE
Update mirtop modules and subworkflow

### PR DESCRIPTION
**Pull request by atrigila**
This PR adds the '`arity`' option in `mirtop/gff` which allows for the use of one or multiple bam files as input. In addition, some minor changes were introduced such as:
- Named outputs using `${prefix}`
- Outputs from process or workflows were renamed to add clarity (e.g. rawdata -> "isomirs", tsv -> "counts", mirtop_gff -> "gff")

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by apeltzer — APPROVED** [review]

**Comment by apeltzer** [comment]
We'll raise this in smrnaseq once this was implemented. Stable Releases are available so shouldn't be a problem 👍🏻

**Comment by apeltzer** [comment]
Thanks @SPPearce !

**Comment by SPPearce** [comment]
Yeah, it is in stable but just wanted to flag it

**Comment by apeltzer** [comment]
opened a PR already for our pipeline, so this gets addressed 👍🏻

**Pull request merged**
