### PR TITLE
Update MQC container

### PR DESCRIPTION
**Pull request by matthdsm**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by nvnieuwk — APPROVED** [review]

**Review by mashehu — APPROVED** [review]

**Comment by matthdsm** [comment]
Thanks both!

**Comment by matthdsm** [comment]
Ugh, come on merge queue!

**Comment by matthdsm** [comment]
@mashehu, could I get another boost here? The merge queue doesn't like me today 😭

**Comment by mashehu** [comment]
snapshots need updates after version bumps...

**Comment by matthdsm** [comment]
I got a bunch of errors wrt temporary files when running MQC in docker. The proposed fix on the MQC website was to edit the TMPDIR  env variable
https://multiqc.info/docs/usage/troubleshooting/#no-space-left-on-device

**Comment by matthdsm** [comment]
It might be a local issue, but I doubt it actually. I haven't had any issues with other images.
I'll revert the change and fix the tests for the new version.

**Review by apeltzer — APPROVED** [review]

**Comment by ewels** [comment]
Thanks @matthdsm 🙏🏻 

Note also that you can set `env.TMPDIR` via a nextflow config too, without editing the process script.

**Comment by matthdsm** [comment]
Thanks for the tip, but as you mentioned, the issues was with my local docker install, not MQC 😓

**Pull request merged**
