### PR TITLE
add bismark/report

### PR DESCRIPTION
**Pull request by phue**
Depends on https://github.com/nf-core/modules/pull/239 to generate the necessary test data

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `<SOFTWARE>.version.txt` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Review by KevinMenden — CHANGES_REQUESTED** [review]
Thanks! The module code looks good to me but the test data has to be restructured. 

I'm guessing we can't use any viral data for this, but in this case we would have to create a folder called "tests/data/genomics/ecoli" with all the data in it.
And they should be named similar (or the same) like the files in "sarscov2", e.g. test_genome.fasta

Also we will need some information about the test data as to where ti came from and/or was generated.

**Comment by phue** [comment]
@KevinMenden thanks for the review.
The module is using simulated bisulfite reads that were added in https://github.com/nf-core/modules/pull/249
They were generated with Sherman as stated in the [README.md](https://github.com/KevinMenden/modules/blob/master/tests/data/README.md)

**Comment by KevinMenden** [comment]
But you're adding a bunch of files to `tests/data/index`, if you need those files then we have to create a `tests/data/genomics/ecoli` directory to store them in. Even better if you could use the `sarscov2` files added in  #249

**Comment by phue** [comment]
Ok now I see the problem :facepalm:
Somehow pushed those files by accident, but the tests don't depend on it. Will delete ASAP (I'm really puzzled how this happened actually)

**Comment by KevinMenden** [comment]
Yep I kinda thought that happened :grin:

**Review by KevinMenden — APPROVED** [review]

**Pull request merged**
