### PR TITLE
add ngmaster module

### PR DESCRIPTION
**Pull request by rpetit3**
## PR checklist

Closes https://github.com/nf-core/modules/issues/1023

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by rpetit3** [comment]
For some reason a Biocontainer is not available, trying to rebuild to see about get one made

https://github.com/bioconda/bioconda-recipes/pull/31376

**Comment by rpetit3** [comment]
singularity image not created yet

**Review by grst — APPROVED** [review]
LGTM!

**Comment by grst** [comment]
Feel free to merge once the singularity test passes

**Comment by rpetit3** [comment]
Still not available, I'll give it a few more days and reach out to Galaxy Project team to see if they can check it out.

**Comment by rpetit3** [comment]
Good to go!

**Pull request merged**
