### PR TITLE
Update seqkit modules to version 2.5.1

### PR DESCRIPTION
**Pull request by heuermh**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by heuermh** [comment]
I have run the failing tests locally, the results look ok but some of the checksums are different.

I didn't author all of these modules; what is the purpose of including `versions.yml` in the test result checksum check?  By design those will change with every version bump of the tool.

**Review by Midnighter — APPROVED** [review]

**Comment by Midnighter** [comment]
> what is the purpose of including versions.yml in the test result checksum check?

They will change between versions, but it is a quick way to ensure that the file doesn't change for the _same_ version. I could imagine that that's the purpose.

**Comment by DLBPointon** [comment]
Are the output data expected to be different for the majority of the modules?

**Comment by heuermh** [comment]
I'm dropping this pull request in favor of #4240, I don't feel comfortable updating the checksums for modules that I did not create.

Then in general, I think checksumming `versions.yml` is a bad idea, and makes simple version bump pull requests (like this was supposed to be) hard to do.

**Pull request closed without merging**
