### PR TITLE
Add type/pattern

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
## PR checklist

See #2914 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Comment by mashehu** [comment]
We have now a minimum of 3 keywords (blame @jfy133 for this 😉)

**Comment by FriederikeHanssen** [comment]
https://media.giphy.com/media/5WXqTFTgO9a7e/giphy.gif

**Comment by FriederikeHanssen** [comment]
@nf-core-bot fix linting

**Comment by matthdsm** [comment]
@FriederikeHanssen , could you check the tests for controlfreec here so we can merge this?

**Review by mashehu — APPROVED** [review]

**Pull request merged**
