### PR TITLE
Macs2 calllpeak

### PR DESCRIPTION
**Pull request by jianhong**
This is a update of MACS2 callpeak module to accept the format parameter from args.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by drpatelh** [comment]
Also tried to add tests and `meta.yml` in https://github.com/nf-core/modules/pull/736. Maybe worth bringing the two together somehow?

**Review by lescai — COMMENTED** [review]
overall LGTM. I would suggest fixing the indents but they were in the previous code so can't add suggestions here. 
conda is failing over the version.yml file: please double check this, and I'm happy to approve.

**Comment by jianhong** [comment]
> overall LGTM. I would suggest fixing the indents but they were in the previous code so can't add suggestions here. conda is failing over the version.yml file: please double check this, and I'm happy to approve.

I tried to fix the issue. However I can not repeat the error in my local machine. Could anybody help?

**Comment by JoseEspinosa** [comment]
I will try to give it a try and come back to you in case I can not reproduce either

**Comment by JoseEspinosa** [comment]
I removed python from the conda environment declaration since it should be resolved by conda automatically, anyway although conda test work locally they do not work on github. Since test are working both with Docker and Singularity I think we are good to go.

**Review by JoseEspinosa — APPROVED** [review]
I removed python from the conda environment declaration since it should be resolved by conda automatically, anyway although conda test work locally they do not work on github. Since test are working both with Docker and Singularity I think we are good to go.

**Pull request merged**
