### PR TITLE
Update container version

### PR DESCRIPTION
**Pull request by rafalstepien**
## PR checklist

This PR bumps the version of container for eido including newest bugfix

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]
Does conda forge build number need to be updated as well? (although it looks here to possibly just container build related)

**Comment by rafalstepien** [comment]
@jfy133 yes, it's just the container build number, so no need for conda-forge update. This depends on https://github.com/nf-core/test-datasets/pull/616

**Comment by jfy133** [comment]
Ok, we also need to wait for them to become avaiable, the tests are failing because it can't find the image (not sure why conda is failing though)

**Comment by rafalstepien** [comment]
I think that they were failing because this build introduced one bugfix and it turned out that the schema was incorrect after this bugfix. That's why also conda failed.

**Pull request merged**
