### PR TITLE
new module humann3

### PR DESCRIPTION
**Pull request by kohjy-ag**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by grst** [comment]
There's already https://github.com/nf-core/modules/pull/1089, but I don't know what state it is in. It still uses the old module syntax, so it might indeed be easier to start from scratch.

**Comment by d4straub** [comment]
Hi there, #1089 is indeed in old syntax because I opened the PR just before the template update hit. Since than, I used HUMAnN3 on several projects and learned. However, I currently do not find the time to update the modules in that PR.
@kohjy-ag if you have soon-ish some time to work on the HUMAnN3 module, than I am discontinuing my PR. If you think it might take you some months than I might be faster in updating my PR. Please let me know so that we are not doing redundant work.

**Comment by kohjy-ag** [comment]
I will work on this asap!

**Comment by kohjy-ag** [comment]
what's the next step? to wait for reviewer, or to correct some of the checks that are not successful?

**Comment by kohjy-ag** [comment]
> Hi @kohjy-ag,
> 
> thanks for working on this! Your PR still uses the old module template. To get it right, it's probably easiest to update `nf-core-tools` and re-create the module from scratch. You can then copy over the relevant parts.
> 
> Unless there are specific problems or questions, we usually review a module as soon as the tests pass.

how do i update nf-core tools?

**Comment by d4straub** [comment]
>  how do i update nf-core tools?

Here is the [nf-core/tools documentation](https://nf-co.re/tools/#installation). It depends whether you used pip or conda.

**Comment by kohjy-ag** [comment]
> 

what do you mean by old module template?

**Comment by kohjy-ag** [comment]
> Hi @kohjy-ag,
> 
> thanks for working on this! Your PR still uses the old module template. To get it right, it's probably easiest to update `nf-core-tools` and re-create the module from scratch. You can then copy over the relevant parts.
> 
> Unless there are specific problems or questions, we usually review a module as soon as the tests pass.

what do u mean by old module template?

**Comment by kohjy-ag** [comment]
> > what do u mean by old module template?
> 
> This means that your pull request is based on an outdated (=old) module template that comes with a previous (=old) version of nf-core tools. The solution is to update nf-core tools (or re-install, or make a new conda environment; see above link for details) and re-do the module.

i got it, thanks all for ur responses! i have already updated my nf-core tools....

may i confirm that the latest version u mentioned is the one i have version 2.2? and what is the new module template like? i would like to check that the version i have has this template... thanks again!

**Comment by d4straub** [comment]
> may i confirm that the latest version u mentioned is the one i have version 2.2?

Yes, 2.2 is the latest release, check out https://nf-co.re/tools/docs/ or more at the source, here https://github.com/nf-core/tools/releases
The template will be fine when using that version. You can always check out the template at https://github.com/nf-core/tools/tree/2.2/nf_core/module-template (remember to choose the correct tag = release, in that case I selected 2.2).

**Comment by kohjy-ag** [comment]
bash: .command.sh: No such file or directory

any idea about this kind of error?

**Comment by kohjy-ag** [comment]
> 

bash: .command.sh: No such file or directory

any idea about this kind of error?

**Comment by kohjy-ag** [comment]
> > may i confirm that the latest version u mentioned is the one i have version 2.2?
> 
> Yes, 2.2 is the latest release, check out https://nf-co.re/tools/docs/ or more at the source, here https://github.com/nf-core/tools/releases The template will be fine when using that version. You can always check out the template at https://github.com/nf-core/tools/tree/2.2/nf_core/module-template (remember to choose the correct tag = release, in that case I selected 2.2).

bash: .command.sh: No such file or directory

any idea about this kind of error?

**Comment by d4straub** [comment]
We are now at nf-core release 2.3.2, so the template is likely again outdated.

> bash: .command.sh: No such file or directory

no idea, that should not happen. `.command.sh` is the file that is created and than executed within each working directory of each process.

**Comment by kohjy-ag** [comment]
> We are now at nf-core release 2.3.2, so the template is likely again outdated.

how often do the new templates come out? i'm about to finish testing the one that i was doing argh.

**Comment by d4straub** [comment]
> how often do the new templates come out?

not predictable for me as well. Looking at https://github.com/nf-core/tools/releases, it seems major releases are only every couple of month. Same happened to my humann3 PR, best to do a module in a couple of days, which is fine if one is used to the tool and has some spar time.

**Pull request closed without merging**
