### PR TITLE
Build tool docker images: first attempt

### PR DESCRIPTION
**Pull request by ewels**
New GitHub Actions to automatically build docker images for tool wrappers.

* Triggered on push to `master`
* Only runs if a `tools/*/environment.yml` or `tools/*/Dockerfile` file is edited.
* Only builds images for tools that have been updated:
  * Looks at the diff of the last commit (should be a merge commit on `master`) and finds any file sin any tools directories that were updated
  * Loops through these directories and builds docker images, pushes them to the GitHub docker package repository

TODO:

- [ ] Figure out how to tag these images nicely
- [ ] Fix all of the edge cases that probably break it!

The first one is important. At the moment I'm just hardcoding the `:latest` tag. I used `$GITHUB_SHA` as a label for a bit, but we don't know that until too late really, and it needs to be specified in the wrapper `main.nf`.

**Any ideas for an elegant resolution for the docker image label?**

This can be merged anyway, paves the way for wrappers that need custom docker images.

### CODE REVIEW

**Comment by ewels** [comment]
Now finally seems to be working! https://github.com/ewels/nf-core-modules/packages

image

**Comment by ewels** [comment]
ok so I don't quite understand how, but this all seems to have been pushed directly at some point so this PR is effectively already merged..

**Comment by ewels** [comment]
> Any ideas for an elegant resolution for the docker image label?

Solution for this I think is to trigger on the `push` event instead of `pull_request`. Then this runs after the PR is merged and we have the git commit hash and can use that for labelling.

**Comment by grst** [comment]
However, in the module file definition, we can only use the `latest` tag in that case, as the commit hash is not known yet. 
And this is an issue, because the pipeline will always download the `latest` docker image, independent of the module version.

**Comment by ewels** [comment]
ah right, that was it - the fact that we need the commit in the code. Tricky 🤔

**Comment by grst** [comment]
How about using the sha256 hash of `Dockerfile` + `environment.yml` to identify an image?

**Comment by ewels** [comment]
Yes - should work, nice idea 👍 

I was thinking that the image has to have the same hash that will be used by `nf-core modules` but I guess it doesn't actually matter what the hash is, as long as it's hardcoded in the process wrapper.

**Comment by grst** [comment]
> I was thinking that the image has to have the same hash that will be used by nf-core modules

I think that's virtually impossible. By coding that hash into the wrapper script the hash would change again...

**Comment by ewels** [comment]
Yeah exactly, catch-22. Your suggestion should be great 👍 I guess we need to build this into some kind of `nf-core/tools` helper function again. Want to make an issue?

**Comment by grst** [comment]
here we go https://github.com/nf-core/tools/issues/674

**Pull request closed without merging**
