### PR TITLE
Launching one-off subworkflows

### PR DESCRIPTION
**Pull request by Emiller88**

### CODE REVIEW

**Comment by Emiller88** [comment]
Anyone have any ideas how we can pass the input channels in?

```log
Workflow `ALIGN_BOWTIE2` declares 2 input channels but 0 were specified
```

**Comment by mahesh-panchal** [comment]
> Anyone have any ideas how we can pass the input channels in?
> 
> ```log
> Workflow `ALIGN_BOWTIE2` declares 2 input channels but 0 were specified
> ```

I've tried several variations and so far nothing works. I came to the conclusion it wasn't possible to pass anything to `take`, except by using another script.

**Comment by mahesh-panchal** [comment]
Can this work though?
Consider if this snippet was at the bottom of `main.nf`:
```
workflow {
    
    ALIGN_BOWTIE2( 
        params.reads // channel: [ val(meta), [ reads ] ]
        params.index // channel: /path/to/bowtie2/index/
    )
}
```
How would one tell Nextflow the string path is actually a `file` path?

**Comment by Emiller88** [comment]
I have a feeling we need something like https://www.nextflow.io/docs/edge/dsl2.html#module-templates
And then we can call a template that handles the file input params, or maybe something that just takes a samplesheet and outputs a meta map like channel, and then we pass in the subworkflow name in the template.

**Comment by mahesh-panchal** [comment]
Doesn't that mean the process has to take care of the file staging Nextflow usually does?
Otherwise what's the difference to writing another anonymous workflow which calls the named workflow?

**Comment by Emiller88** [comment]
That was all that I was imagining the template would be is an anonymous workflow, that might hook it up to a samplesheet module or something. Your snippet might work with `fromfilepairs` and maybe some magic to turn the name into a `meta.id`

**Comment by maxulysse** [comment]
Shall we close this one, as I'm assuming it's no longer relevant.
@Emiller88 @mahesh-panchal

**Comment by mahesh-panchal** [comment]
Fine by me.

**Comment by Emiller88** [comment]
I think it's even more relevant now that we've actually added subworkflows

**Comment by matthdsm** [comment]
Hi there!

We've noticed there hasn't been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we'll close your PR in about 2 weeks

Cheers
the nf-core maintainers

**Comment by Emiller88** [comment]
Closing in favor of https://github.com/nf-wrap

**Pull request closed without merging**
