### PR TITLE
Update resource allocations of cellranger mkref

### PR DESCRIPTION
**Pull request by grst**
The cellranger mkref resource allocations require to specify the number of cpus twice, once to the martian runtim (=10x workflow manager) and via --nthreads to actually make star run on multiple threads. 

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by nictru** [comment]
I don't know what went wrong here, but if all tests are covered in `nf-test`, the `pytest` configuration might not be necessary any more

**Comment by grst** [comment]
cellrangerarc is still using pytest though. I'll just try again in case it was a spurious hiccup, otherwise my best bet is probably to update cellrangerarc to pytest?

**Comment by grst** [comment]
It's actually one pytest and one nf-test failing. I don't think it's related to the testing framework. 

It's really weird - the same job that passed here fails in the merge queue. Same runner, same AWS instance type - except the one in the merge queue seems to hit a timeout while the other one does not. 

PR log: https://github.com/nf-core/modules/actions/runs/10314835332/job/28553916380?pr=6136
Merge queue log: https://github.com/nf-core/modules/actions/runs/10315485198/job/28555769630

**Comment by edmundmiller** [comment]
Maybe the merged code doesn't work? I kicked off the tests again. If it works locally for you still post merge, we can just override it 🤷🏻‍♂️

**Comment by grst** [comment]
If this branch is up-to-date with master, I should have the same state as the merge queue does?

**Pull request merged**
