### PR TITLE
Fasta index bismark bwameth

### PR DESCRIPTION
**Pull request by sateeshperi**

### CODE REVIEW

**Comment by maxulysse** [comment]
should you deprecate the old one?

**Comment by sateeshperi** [comment]
@maxulysse which old one ?

**Comment by maxulysse** [comment]
This is not to replace/update an existing subworklow ?

**Comment by sateeshperi** [comment]
not in nf-core...it was a local subwf in methylseq that I am porting upstream

**Review by edmundmiller — APPROVED** [review]

**Pull request merged**
