### PR TITLE
Updated test data paths batch 8

### PR DESCRIPTION
**Pull request by GallVp**
## PR checklist

Closes #XXX 

- [x] Updated test data paths batch 8
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by GallVp** [comment]
A conda package seems to be broken?

https://github.com/nf-core/modules/actions/runs/10172683953/job/28139842853#step:14:175

**Comment by SPPearce** [comment]
> A conda package seems to be broken?
> 
> https://github.com/nf-core/modules/actions/runs/10172683953/job/28139842853#step:14:175

Strange, [it is listed in the recipe](https://github.com/bioconda/bioconda-recipes/blob/ecc0e875de2469d8629cc3ea07e1887a70c1f829/recipes/fastq-screen/meta.yaml#L26).
It was [passing the tests previously](https://github.com/nf-core/modules/pull/3574), it is a very tricky package to actually use. One option is to make an issue for any failures and leave them out for the moment.

I've just tried explicitly adding the package to the environment.yml, but I'm not able to run the current version in conda on gitpod either.

**Comment by GallVp** [comment]
For now, going to leave fastqscreen out. Issue raised: https://github.com/nf-core/modules/issues/6075

**Comment by GallVp** [comment]
Excluded `bowtie2/build` to avoid nf-test trigger for `fastqscreen_fastqscreen`

**Review by SPPearce — APPROVED** [review]

**Pull request merged**
