### PR TITLE
update samtools/bam2fq: add compression for output fastq file

### PR DESCRIPTION
**Pull request by ljmesi**
Currently when `split==false` the output isn't gzipped. This PR adds `gzip` in between `bam2fq` output and redirection. 

## PR checklist

Closes #1958 

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]
Good catch!

LGTM once tests pass

**Comment by ljmesi** [comment]
Thanks! What mystifies me a little is why the test workflows with Singularity and Docker pass but not with Conda. I'm not fully sure how to debug this problem. In addition, strangely enough, when I run locally `nf-core modules create-test-yml --run-tests --force samtools/bam2fq` with docker all the tests run but produce empty files for the part of the code that I didn't change:
```
(nf-core) (add_compression_to_bam2fq) [11:17]:~/Desktop/cloned/modules$ nf-core modules create-test-yml --run-tests --force samtools/bam2fq

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.3.2 - https://nf-co.re


INFO     Press enter to use default values (shown in brackets) or type your own responses                                                                                                                         test_yml_builder.py:55
Test YAML output path (- for stdout) (tests/modules/samtools/bam2fq/test.yml): 
INFO     Looking for test workflow entry points: 'tests/modules/samtools/bam2fq/main.nf'                                                                                                                         test_yml_builder.py:123
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
INFO     Building test meta for entry point 'test_samtools_bam2fq_nosplit'                                                                                                                                       test_yml_builder.py:157
Test name (samtools bam2fq test_samtools_bam2fq_nosplit): 
Test command (nextflow run tests/modules/samtools/bam2fq -entry test_samtools_bam2fq_nosplit -c tests/config/nextflow.config): 
Test tags (comma separated) (samtools,samtools/bam2fq): 
? Choose software profile Docker
INFO     Running 'samtools/bam2fq' test with command:                                                                                                                                                            test_yml_builder.py:321
         nextflow run tests/modules/samtools/bam2fq -entry test_samtools_bam2fq_nosplit -c tests/config/nextflow.config --outdir /tmp/tmp7ft7f408 -work-dir /tmp/tmpvmore7m6                                                            
INFO     Repeating test ...                                                                                                                                                                                      test_yml_builder.py:324
INFO     Test workflow finished!                                                                                                                                                                                 test_yml_builder.py:337
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
INFO     Building test meta for entry point 'test_samtools_bam2fq_withsplit'                                                                                                                                     test_yml_builder.py:157
Test name (samtools bam2fq test_samtools_bam2fq_withsplit): 
Test command (nextflow run tests/modules/samtools/bam2fq -entry test_samtools_bam2fq_withsplit -c tests/config/nextflow.config): 
Test tags (comma separated) (samtools,samtools/bam2fq): 
INFO     Running 'samtools/bam2fq' test with command:                                                                                                                                                            test_yml_builder.py:321
         nextflow run tests/modules/samtools/bam2fq -entry test_samtools_bam2fq_withsplit -c tests/config/nextflow.config --outdir /tmp/tmpvij6hszv -work-dir /tmp/tmp3qkhdkc8                                                          
INFO     Repeating test ...                                                                                                                                                                                      test_yml_builder.py:324
INFO     Test workflow finished!                                                                                                                                                                                 test_yml_builder.py:337
INFO     Writing to 'tests/modules/samtools/bam2fq/test.yml'                                                                                                                                                     test_yml_builder.py:354
CRITICAL Ran, but found errors:                                                                                                                                                                                          __main__.py:585
          - Empty file found! 'test_singleton.fq.gz'                                                                                                                                                                                    
          - Empty file found! 'test_other.fq.gz'
```

**Comment by ljmesi** [comment]
@jfy133 I'm wondering if you might have time to take a short moment to look at why conda workflow is failing while the others don't and if you might have an idea what might be causing the failing or how to solve this issue? Or perhaps maybe I should lift this issue up in the nf-core help channel instead?

**Comment by jfy133** [comment]
There is slight variability in the gzipped file I guess:

```
Observed md5sum '7290d2d8dbef0fa57c0e2f28b5db1bf8' not equal to expected md5sum '7a57a8ab53dd1d799cca67a85c47ccd9' for file '/home/runner/pytest_workflow_outspqpe/samtools_bam2fq_test_samtools_bam2fq_nosplit/output/samtools/test_interleaved.fq.gz'
```

sometimes this can occur due to inclusion of a timestamp or similar

You can try adding `gzip  --no-name` instead (however IIRC not supported by all versions of gzip)

```
Usage: gzip [OPTION]... [FILE]...
Compress or uncompress FILEs (by default, compress FILES in-place).

Mandatory arguments to long options are mandatory for short options too.

  -c, --stdout      write on standard output, keep original files unchanged
  -d, --decompress  decompress
  -f, --force       force overwrite of output file and compress links
  -h, --help        give this help
  -k, --keep        keep (don't delete) input files
  -l, --list        list compressed file contents
  -L, --license     display software license
  -n, --no-name     do not save or restore the original name and timestamp
  -N, --name        save or restore the original name and timestamp
  -q, --quiet       suppress all warnings
  -r, --recursive   operate recursively on directories
      --rsyncable   make rsync-friendly archive
  -S, --suffix=SUF  use suffix SUF on compressed files
      --synchronous synchronous output (safer if system crashes, but slower)
  -t, --test        test compressed file integrity
  -v, --verbose     verbose mode
  -V, --version     display version number
  -1, --fast        compress faster
  -9, --best        compress better

With no FILE, or when FILE is -, read standard input.

Report bugs to <bug-gzip@gnu.org>.
```

**Comment by ljmesi** [comment]
Thanks for the tip! I will give it a try.

**Comment by ljmesi** [comment]
When I ran locally: `nf-core modules create-test-yml --run-tests --force samtools/bam2fq` with docker using:
```shell
$inputbam | gzip --no-name > ${prefix}_interleaved.fq.gz
```
in the module. The checksum didn't change for `${prefix}_interleaved.fq.gz`.

**Comment by jfy133** [comment]
> When I ran locally: `nf-core modules create-test-yml --run-tests --force samtools/bam2fq` with docker using:
> 
> ```shell
> $inputbam | gzip --no-name > ${prefix}_interleaved.fq.gz
> ```
> 
> in the module. The checksum didn't change for `${prefix}_interleaved.fq.gz`.

When running with conda?

**Comment by ljmesi** [comment]
Ok. I'll try conda.

**Comment by ljmesi** [comment]
Conda doesn't seem to be able to run:
```
(nf-core) (add_compression_to_bam2fq) [15:23]:~/Desktop/cloned/modules$ nf-core modules create-test-yml --run-tests --force samtools/bam2fq

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.3.2 - https://nf-co.re


INFO     Press enter to use default values (shown in brackets) or type your own responses                                                                                                                         test_yml_builder.py:55
Test YAML output path (- for stdout) (tests/modules/samtools/bam2fq/test.yml): 
INFO     Looking for test workflow entry points: 'tests/modules/samtools/bam2fq/main.nf'                                                                                                                         test_yml_builder.py:123
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
INFO     Building test meta for entry point 'test_samtools_bam2fq_nosplit'                                                                                                                                       test_yml_builder.py:157
Test name (samtools bam2fq test_samtools_bam2fq_nosplit): 
Test command (nextflow run tests/modules/samtools/bam2fq -entry test_samtools_bam2fq_nosplit -c tests/config/nextflow.config): 
Test tags (comma separated) (samtools,samtools/bam2fq): 
? Choose software profile Conda
INFO     Setting env var '$PROFILE' to 'conda'                                                                                                                                                                   test_yml_builder.py:313
INFO     Running 'samtools/bam2fq' test with command:                                                                                                                                                            test_yml_builder.py:321
         nextflow run tests/modules/samtools/bam2fq -entry test_samtools_bam2fq_nosplit -c tests/config/nextflow.config --outdir /tmp/tmpkedu_omi -work-dir /tmp/tmpvarqvz8h                                                            
CRITICAL Error running test workflow (exit code 1)                                                                                                                                                                       __main__.py:585
         N E X T F L O W  ~  version 21.10.6                                                                                                                                                                                            
         Launching `tests/modules/samtools/bam2fq/main.nf`  - revision: e6ff7e6112                                                                                                                                                      
         [-        ] process > test_samtools_bam2fq_nosplit:SAMTOOLS_BAM2FQ -                                                                                                                                                           
                                                                                                                                                                                                                                        
         [-        ] process > test_samtools_bam2fq_nosplit:SAMTOOLS_BAM2FQ -                                                                                                                                                           
         Creating env using conda: bioconda::samtools=1.15.1                                                                                                                                                                            
                                                                                                                                                                                                                                        
         [-        ] process > test_samtools_bam2fq_nosplit:SAMTOOLS_BAM2FQ -                                                                                                                                                           
         Creating env using conda: bioconda::samtools=1.15.1                                                                                                                                                                            
         Error executing process > 'test_samtools_bam2fq_nosplit:SAMTOOLS_BAM2FQ (test)'                                                                                                                                                
                                                                                                                                                                                                                                        
         Caused by:                                                                                                                                                                                                                     
           Failed to create Conda environment                                                                                                                                                                                           
           command: conda create --mkdir --yes --quiet --prefix /tmp/tmpvarqvz8h/conda/env-5766dc03c95cac9e561434ae995f6c5a bioconda::samtools=1.15.1                                                                                   
           status : 1                                                                                                                                                                                                                   
           message:                                                                                                                                                                                                                     
             PackagesNotFoundError: The following packages are not available from current channels:                                                                                                                                     
                                                                                                                                                                                                                                        
               - libgcc-ng                                                                                                                                                                                                              
                                                                                                                                                                                                                                        
             Current channels:                                                                                                                                                                                                          
                                                                                                                                                                                                                                        
               - https://repo.anaconda.com/pkgs/main/linux-64                                                                                                                                                                           
               - https://repo.anaconda.com/pkgs/main/noarch                                                                                                                                                                             
               - https://repo.anaconda.com/pkgs/r/linux-64                                                                                                                                                                              
               - https://repo.anaconda.com/pkgs/r/noarch                                                                                                                                                                                
                                                                                                                                                                                                                                        
             To search for alternate channels that may provide the conda package you're                                                                                                                                                 
             looking for, navigate to                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
                 https://anaconda.org                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
             and use the search bar at the top of the page.                                                                                                                                                                             
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
         [-        ] process > test_samtools_bam2fq_nosplit:SAMTOOLS_BAM2FQ -                                                                                                                                                           
         Creating env using conda: bioconda::samtools=1.15.1                                                                                                                                                                            
         Error executing process > 'test_samtools_bam2fq_nosplit:SAMTOOLS_BAM2FQ (test)'                                                                                                                                                
                                                                                                                                                                                                                                        
         Caused by:                                                                                                                                                                                                                     
           Failed to create Conda environment                                                                                                                                                                                           
           command: conda create --mkdir --yes --quiet --prefix /tmp/tmpvarqvz8h/conda/env-5766dc03c95cac9e561434ae995f6c5a bioconda::samtools=1.15.1                                                                                   
           status : 1                                                                                                                                                                                                                   
           message:                                                                                                                                                                                                                     
             PackagesNotFoundError: The following packages are not available from current channels:                                                                                                                                     
                                                                                                                                                                                                                                        
               - libgcc-ng                                                                                                                                                                                                              
                                                                                                                                                                                                                                        
             Current channels:                                                                                                                                                                                                          
                                                                                                                                                                                                                                        
               - https://repo.anaconda.com/pkgs/main/linux-64                                                                                                                                                                           
               - https://repo.anaconda.com/pkgs/main/noarch                                                                                                                                                                             
               - https://repo.anaconda.com/pkgs/r/linux-64                                                                                                                                                                              
               - https://repo.anaconda.com/pkgs/r/noarch                                                                                                                                                                                
                                                                                                                                                                                                                                        
             To search for alternate channels that may provide the conda package you're                                                                                                                                                 
             looking for, navigate to                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
                 https://anaconda.org                                                                                                                                                                                                   
                                                                                                                                                                                                                                        
             and use the search bar at the top of the page.
```

**Comment by jfy133** [comment]
(stupid question) have you already set up the bioconda channel on your
conda install?

https://bioconda.github.io/user/install.html#set-up-channels

**Comment by ljmesi** [comment]
Thanks for the advice! No, actually I hadn't set up globally the channels for bioconda and conda-forge. Now the new run seemed to change the checksum as well so now conda test workflow works. I tried also locally with both singularity and docker and both change the checksum to another from the conda produced one.

**Comment by muffato** [comment]
@ljmesi : I had the same issue in another pull request: for Conda, the MD5 I was getting on the CI here was different than the one I was using locally. The solution was also to add both conda-forge and bioconda to my default channels. And then, I started getting the same MD5 as the CI

**Comment by ljmesi** [comment]
> @ljmesi : I had the same issue in another pull request: for Conda, the MD5 I was getting on the CI here was different than the one I was using locally. The solution was also to add both conda-forge and bioconda to my default channels. And then, I started getting the same MD5 as the CI

Yes. Sadly in this case it looks like when I used `nf-core modules create-test-yml --run-tests --force samtools/bam2fq` with conda I get a different checksum for file '/home/runner/pytest_workflow_607gn0xn/samtools_bam2fq_test_samtools_bam2fq_nosplit/output/samtools/test_interleaved.fq.gz' from when I run `nf-core modules create-test-yml --run-tests --force samtools/bam2fq` with singularity or docker.

**Comment by jfy133** [comment]
OK, in this case just drop the md5sum check on the file that has variable md5sums, I guess there might be some inherant variability in the ordering of the reads for example. Can just cehck that it exists and that is sufficient for now.

**Comment by ljmesi** [comment]
Ok. Thanks for the help @jfy133! Now all the tests pass. I'll merge this PR.

**Pull request merged**
