### PR TITLE
Added contrast limited adaptive histogram equalization module

### PR DESCRIPTION
**Pull request by kbestak**
Based on the Molkart local script with the same functionality.  Scikit-image function; pyramidal output file.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements. // not possible
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [x] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`

### CODE REVIEW

**Comment by kbestak** [comment]
TODO: exclude module from conda testing; understand issue with linting

**Comment by kbestak** [comment]
Thank you @FloWuenne !

**Review by FloWuenne — COMMENTED** [review]
LGTM!

**Review by migueLib — APPROVED** [review]
LGTM!

**Pull request merged**
