### PR TITLE
Add meta information to samtools/faidx

### PR DESCRIPTION
**Pull request by maxibor**
Having the meta information for the `samtools/faidx` has become necessary for pipeline dealing with multiple references (in _de novo_ assembly processing for example)

## PR checklist

- [x] This comment contains a description of changes (with reason).

### CODE REVIEW

**Review by FriederikeHanssen — APPROVED** [review]
lgtm

**Comment by FriederikeHanssen** [comment]
Ah there seem to be a lot of commits for the tiny change...maybe something of with the branch?

**Comment by maxulysse** [comment]
> Ah there seem to be a lot of commits for the tiny change...maybe something of with the branch?

Does it really matter if we squash and merge anyway?

**Comment by maxibor** [comment]
> Ah there seem to be a lot of commits for the tiny change...maybe something of with the branch?

Well, it's the side-effect of merging instead of rebasing when working with a very active remote.
But as @maxulysse mentioned, they're just squashed into a single one.

**Comment by FriederikeHanssen** [comment]
right, forgot that we squash here :)

**Pull request merged**
