### PR TITLE
Seqtk seq

### LINKED ISSUE #1303: new module: seqtk/seq
I think it would be good to have a module for [seqtk seq](https://bioconda.github.io/recipes/seqtk/README.html)

- [X] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [X] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [X] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

### PR DESCRIPTION
**Pull request by hseabolt**
## PR checklist

Closes #1303 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by maxulysse** [comment]
not super sure about the `sequences` input/output keyword, but as it can handle both fasta and fastq files, not sure what to use instead.
Any idea @nf-core/core

**Review by maxulysse — COMMENTED** [review]
looks good, just not sure about the `sequences` keyword for input/output

**Comment by hseabolt** [comment]
My thinking for the sequences variable name is that this module isnt exclusive to reads, I have used `seqtk seq` for generating fasta contig assemblies in the past -- so the variable name is intended to reflect that flexibility vs use cases only for reads.

**Comment by sateeshperi** [comment]
recommendation from @mahesh-panchal 
change `sequences` to `fastx`

**Pull request merged**
