### PR TITLE
Update mapdage2 module

### LINKED ISSUE #3186: Mapdamage2 does not emit the rescaled bam correctly.
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

The emission path contains a typo, so the output file is not picked up.

### Command used and terminal output

_No response_

### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by TCLamnidis**
The current implementation does not emit the rescaled bam due to a typo in the emission path.

## PR checklist

Closes #3186  

- [x] This comment contains a description of changes (with reason).
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by jbv2 — APPROVED** [review]

**Review by jfy133 — APPROVED** [review]
Did you check there was anything else with a mistake in it?

**Comment by TCLamnidis** [comment]
All other output files are created normally. Could not check only the fasta output, as that requires additional options, but the output path for it  looks ok.

**Comment by TCLamnidis** [comment]
not sure why conda is failing. green light?

**Comment by jfy133** [comment]
Yeah looks wierd in that case, like the conda version is broken but that doesn't make sense to me

**Pull request merged**
