### PR TITLE
Update deepvariant/rundeepvariant

### PR DESCRIPTION
**Pull request by maxulysse**
Let's write to current workdir

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Review by abhi18av — APPROVED** [review]
This should work well. Looks good to merge @maxulysse !

**Comment by fellen31** [comment]
This does't work with deepvariant 1.6.1, https://github.com/nf-core/modules/pull/5801/files/5ca87e95e3c9d80b838e5caeb7448b73728aa041#r1637917607 and https://github.com/google/deepvariant/issues/742

**Comment by abhi18av** [comment]
Ah good catch @fellen31!

Te triggered test does fail with the same `ValueError` for this version - perhaps the param should be removed entirely?
 
image

**Comment by fellen31** [comment]
> Ah good catch @fellen31!
> 
> Te triggered test does fail with the same `ValueError` for this version - perhaps the param should be removed entirely?

If removed completely I'm afraid it will write to `/tmp`, this way it should write to a directory `tmp` in the work/scratch directory.

**Comment by maxulysse** [comment]
> > Ah good catch @fellen31!
> > Te triggered test does fail with the same `ValueError` for this version - perhaps the param should be removed entirely?
> 
> If removed completely I'm afraid it will write to `/tmp`, this way it should write to a directory `tmp` in the work/scratch directory.

Ok, then this is the way, let's kill this PR
cc @FriederikeHanssen

**Pull request closed without merging**
