### PR TITLE
Update bwa/index container

### PR DESCRIPTION
**Pull request by MaxUlysse**
Use container from quay.io.

This `biocontainers/bwa:v0.7.17_cv1` is not working for me.

### CODE REVIEW

**Review by KevinMenden — APPROVED** [review]
Make sense 👍

**Comment by drpatelh** [comment]
This module needs to be updated anyway along with the `bwa_mem` one too. It would be better to create and move directories around for indices instead of using globs. I can update in a separate PR but the idea would be make and create a directory with all of the index files like [here](https://github.com/nf-core/modules/blob/4301afb7711bb10851753a6b0fcec9a6373769dd/software/bowtie2/build/main.nf#L31) and then stage them in the `bwa_mem` process like [this](https://github.com/nf-core/modules/blob/4301afb7711bb10851753a6b0fcec9a6373769dd/software/bowtie2/align/main.nf#L37). This also means that pipelines are able to accept tar archives of the indexing directory if required.

**Comment by MaxUlysse** [comment]
The `bwa_mem` has a mulled container, but the conda version for bwa in the conda declaration is the same as specified in this one.

**Comment by MaxUlysse** [comment]
@drpatelh will you be ok, if I don't update the `bwa_mem`, as I'm not sure what to update there? or if there is even something to update...

**Comment by drpatelh** [comment]
Ok. Let me get a PR together now and pull you in to review 👍🏽

**Pull request merged**
