### PR TITLE
update: `gunzip` to include meta input tuple

### PR DESCRIPTION
**Pull request by jfy133**
## PR checklist

Difficult to unzip input data if `meta` isn't there. `meta` can be optional defined with an empty list.

Discussed on: https://nfcore.slack.com/archives/C027CM7P08M/p1637137230024100

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Review by drpatelh — APPROVED** [review]
LGTM!

**Comment by drpatelh** [comment]
This is going to break a bunch of downstream module tests that use this module beforehand.

**Comment by jfy133** [comment]
Suggestion how to deal with that?

**Comment by drpatelh** [comment]
We will need to find which ones use this module in the `tests/` directory and add an empty map as input.

**Comment by drpatelh** [comment]
```
$ find ./ -type f -exec grep -H 'include { GUNZIP' {} \;

./gunzip/main.nf:include { GUNZIP } from '../../../modules/gunzip/main.nf' addParams( options: [:] )
./ultra/pipeline/main.nf:include { GUNZIP         } from '../../../../modules/gunzip/main.nf'         addParams( options: [:] )
```

Only one other it seems!

**Comment by drpatelh** [comment]
I will fix it in #1081

**Pull request merged**
