### PR TITLE
.nf-test -> nf-test

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by Emiller88** [comment]
Did we mean to add `NXF_TEST_DIR` as an environment variable and forgot? I think the `TMPDIR=~` is for singularity 🤔

**Comment by Emiller88** [comment]
Ah, you said that in Slack
> also we don't set up NXF_TEST_DIR in the GHA, should we set it up to ~ as we used to do with TMPDIR?

I think we should do this, not change that, because it changes how the local tests are ran then.

**Comment by maxulysse** [comment]
> Ah, you said that in Slack
> 
> > also we don't set up NXF_TEST_DIR in the GHA, should we set it up to ~ as we used to do with TMPDIR?
> 
> I think we should do this, not change that, because it changes how the local tests are ran then.

main issue is that if we run with `.nf-test` the tests fails locally unless we set up the `NXF_TEST_DIR` locally too

**Comment by maxulysse** [comment]
I'd rather we have that in `/tmp` or whatever is equivalent as I had set it up at the beginning

**Review by sateeshperi — APPROVED** [review]

**Comment by Emiller88** [comment]
> I'd rather we have that in `/tmp` or whatever is equivalent as I had set it up at the beginning

Looks like it was @adamrtalbot so we'll have to wait for an answer.

**Comment by maxulysse** [comment]
`NXF_TEST_DIR=~` is good enough for me, that works on GHA, and whoever can set up the env to work how they like locally.
But I'm wondering if we should have used `TMP_DIR` instead actually

**Pull request merged**
