### PR TITLE
Added optional flow field output and increase version number for cellpose

### PR DESCRIPTION
**Pull request by FloWuenne**
## PR checklist

This PR adds flow fields as an optional output file to cellpose. This optional output file will be used in a future version of [nf-core/molkart](https://github.com/nf-core/molkart) in combination with spot based segmentation methods. An additional test with theadditional output file has been added and tested.

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by SPPearce — APPROVED** [review]
Looks fine if the tests pass

**Review by SPPearce — APPROVED** [review]

**Review by josenimo — APPROVED** [review]

**Review by josenimo — APPROVED** [review]

**Review by josenimo — APPROVED** [review]

**Comment by mashehu** [comment]
everything is back to normal runners again. Do you have an older PR where this module ran on singularity? https://github.com/nf-core/modules/actions/runs/6499993760/job/17654471334#step:12:221 this line looks like it wants to write outside of the work directory ☝🏻

**Comment by FloWuenne** [comment]
The link you posted refers to an old Runner action where Docker even failed due to md5sum mismatches (which is corrected now). Here is a screenshot of the line that I think is breaking the tests. However this doesn't break the singularity tests within my own local environment. The singularity runners in the past for this module definitely passed, since the module was merged a while ago... 

image

**Review by josenimo — APPROVED** [review]

**Comment by nvnieuwk** [comment]
It seems to me that either a dependency has been lost in the conversion to a singularity image or the tools needs to cache something somewhere where it can't write? I don't think converting to nf-test will fix these issues :/

**Review by josenimo — APPROVED** [review]

**Comment by FloWuenne** [comment]
@nvnieuwk I think it's trying to cache something and can't do it where it wants to using the runners. I believe this is related to this issue in Numba:
https://github.com/numba/numba/issues/4908

I thought that simply setting `NUMBA_CACHE_DIR` in the module script should solve this problem, but attempts to do this (https://github.com/nf-core/modules/pull/3975/commits/411e333d8afa2e18128b0e865c61e060d3fd7afc) didn't seem to fix the issue and just create new problems with file path permissions...

I really don't know at this point how to solve this. The singularity tests all pass without issue when running tests manually. 

Do you think we can merge this with the singularity runner action failing? It does work in singularity tests, so the module should be functional...

**Comment by nvnieuwk** [comment]
I think this should be fixed, because on HPC clusters for example you also won't have permission to write everywhere (which is where singularity will be used the most). 

Did you still have the same error when trying to use `NUMBA_CACHE_DIR`?

**Review by josenimo — COMMENTED** [review]
nice

**Comment by SPPearce** [comment]
Good work getting this actually in!

**Pull request merged**
