### PR TITLE
Add in path to all files in index directory to copy on Azure correctly.

### LINKED ISSUE #627: [BUG] bwa index not work correctly
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/module documentation](https://github.com/nf-core/modules/blob/master/README.md)

## Description of the bug

bwa index create indexes at working folder but not bwa subfolder as before under conda environment. (previous it works)

## System

- Hardware: MAC book
- Executor: local
- OS: macOS Big Sur
- Version: 11.4

## Nextflow Installation

- Version: 21.05.0-edge.5563

## Container engine

- Engine: Conda
- version: 4.9.2
- Image tag: nf-core/tools version 2.0.1.dev0

## Additional context

It can be fixed by change bwa/index/main.nf line 32
```
bwa index $options.args $fasta -p bwa/${fasta.baseName}
```
to 
```
bwa index $options.args -p bwa/${fasta.baseName} $fasta
```

### PR DESCRIPTION
**Pull request by vsmalladi**
## PR checklist

Closes #627 

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by drpatelh** [comment]
Yo! Why doesn't the current behaviour of copying a directory work here? This would have been tested already on Azure?

**Comment by vsmalladi** [comment]
Never tested making the bwa index. I had just upload the index files already.

**Comment by drpatelh** [comment]
Merging this in will need some thought because this will change the way we are dealing with indices in pipelines quite a bit and how they are defined by users. What error do you see when using the current behaviour on Azure?

**Comment by vsmalladi** [comment]
The error is that nextflow can't find the file to copy over.

**Comment by drpatelh** [comment]
But it should just be a directory no? This should then affect any directory defined as output on Azure?

**Comment by vsmalladi** [comment]
That would be my assumption, but i wonder if its just the way the directory contents are referred to. If you add directory/*
vs just directory. I think this will require some more investigation.

**Review by JakobBerg — APPROVED** [review]
Looks good to me

**Comment by vsmalladi** [comment]
@adamrtalbot can you take a look?

**Comment by vsmalladi** [comment]
@adamrtalbot  might not be an issue anymore. Maybe we can hold off until it becomes an issue again.

**Comment by SPPearce** [comment]
Closing this until someone flags it as an issue again.

**Comment by famosab** [comment]
I think indices are tackled in https://github.com/nf-core/modules/pull/9997

**Pull request closed without merging**
