### PR TITLE
Bump MultiQC version to 1.19

### PR DESCRIPTION
**Pull request by adamrtalbot**
Bumps multiqc module to v1.19

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by mashehu — APPROVED** [review]

**Review by maxulysse — APPROVED** [review]

**Comment by mashehu** [comment]
what-about-me-alexis-rose-gif

**Comment by maxulysse** [comment]
@adamrtalbot you need to update the snapshot because you updated the versions

**Comment by maxulysse** [comment]
> what-about-me-alexis-rose-gif [ what-about-me-alexis-rose-gif ](https://private-user-images.githubusercontent.com/6169021/295520167-7a19d6f3-5f16-446b-86fc-0954506f037a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODAwOTcsIm5iZiI6MTcwNDg3OTc5NywicGF0aCI6Ii82MTY5MDIxLzI5NTUyMDE2Ny03YTE5ZDZmMy01ZjE2LTQ0NmItODZmYy0wOTU0NTA2ZjAzN2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDk0MzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M1MTUwMDcyNGZlYmNiZjRlZGIwZjQ4NzJmNTMyYzE5NzlhNDBhNTdkZWNjNjg1ZTBiZGZhNzMxMWIwOWM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dzy8FAr77mUdtTuJyLtS7gfZE27-VBLL7xVhGuItXVY) [ ](https://private-user-images.githubusercontent.com/6169021/295520167-7a19d6f3-5f16-446b-86fc-0954506f037a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODAwOTcsIm5iZiI6MTcwNDg3OTc5NywicGF0aCI6Ii82MTY5MDIxLzI5NTUyMDE2Ny03YTE5ZDZmMy01ZjE2LTQ0NmItODZmYy0wOTU0NTA2ZjAzN2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDk0MzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M1MTUwMDcyNGZlYmNiZjRlZGIwZjQ4NzJmNTMyYzE5NzlhNDBhNTdkZWNjNjg1ZTBiZGZhNzMxMWIwOWM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dzy8FAr77mUdtTuJyLtS7gfZE27-VBLL7xVhGuItXVY)

I was on zoom with him ;-)

**Comment by maxulysse** [comment]
@adamrtalbot same for custom/sumpsoftwareversions

**Comment by maxulysse** [comment]
but can't we get rid of it already for fetchngs?

**Pull request merged**
