### PR TITLE
Moved the bed input of mosdepth

### PR DESCRIPTION
**Pull request by nvnieuwk**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by matthdsm** [comment]
I wouldn't do this.
More than often, the bed file is part of the genome reference data and not sample related

**Comment by nvnieuwk** [comment]
> I wouldn't do this. More than often, the bed file is part of the genome reference data and not sample related

True but this enables both possibilities while the way it was doesn't

**Review by matthdsm — APPROVED** [review]
Reluctantly agree

**Comment by scorreard** [comment]
Hi! @nvnieuwk , how should I use it in my pipeline now?

```
   MOSDEPTH ( BWA_MEM.out.bam
                        .join(SAMTOOLS_INDEX.out.bai)
                        .join ([])
                ,[[:],[]])
```

gives me

```
Invalid operator `join` argument [java.util.ArrayList] -- it must be a channel type
```

**Comment by matthdsm** [comment]
Hi @scorreard, 
You can't `join` non channel items. I think you'll need to 
1. create a channel
2. `combine` both

```  
MOSDEPTH ( BWA_MEM.out.bam
                        .join(SAMTOOLS_INDEX.out.bai)
                        .combine (channel.value([]))
                ,[[:],[]])
```

**Comment by nvnieuwk** [comment]
Or you could use `.map` if you don't want to use a bed file like this:
```
MOSDEPTH( 
    BWA_MEM.out.bam.map { it + [[]] },
    [[], []]
)
```

**Comment by scorreard** [comment]
Thanks a lot both, I'll try that today!! :)

**Comment by priyanka-surana** [comment]
@nvnieuwk @matthdsm Am I understanding wrong or does the [`meta.yml`](https://github.com/nf-core/modules/blob/master/modules/nf-core/mosdepth/meta.yml) need an edit too? There is a `meta3` in `meta.yml` but not in `main.nf`.

**Pull request merged**
