### PR TITLE
flye: fix nf-test, update module

### LINKED ISSUE #6606: Flye CI failure: `versions not found in snapshot file`
Uncovered in #6604

```
╭─ [✗] 1 Module Test Failed ───────────────────────────────────────────────────╮
│              ╷                              ╷                                │
│ Module name  │ File path                    │ Test message                   │
│╶─────────────┼──────────────────────────────┼───────────────────────────────╴│
│ flye         │ modules/nf-core/flye/tests/… │ versions not found in snapshot │
│              │                              │ file                           │
│              ╵                              ╵                                │
╰──────────────────────────────────────────────────────────────────────────────╯
```

### LINKED ISSUE #6609: nf-test failure: flye
Uncovered in #6604

### Command used and terminal output

```console
🚀 nf-test 0.9.0
https://www.nf-test.com
(c) 2021 - 2024 Lukas Forer and Sebastian Schoenherr

Load .nf-test/plugins/nft-bam/0.3.0/nft-bam-0.3.0.jar
Load .nf-test/plugins/nft-vcf/1.0.7/nft-vcf-1.0.7.jar
Warning: Module /opt/actions-runner/_work/modules/modules/modules/nf-core/ltrfinder/tests/main.nf.test: Dependency '/opt/actions-runner/_work/modules/modules/modules/nf-core/ltrfinder/tests/../../gunzip/main' not found.
Warning: Module /opt/actions-runner/_work/modules/modules/modules/nf-core/ltrretriever/ltrretriever/tests/main.nf.test: Dependency '/opt/actions-runner/_work/modules/modules/modules/nf-core/ltrretriever/ltrretriever/tests/../../../gunzip/main' not found.

Test Process FLYE

  Test [1f13cf66] 'flye_pacbio_raw' 
    > N E X T F L O W  ~  version 24.04.4
    > Launching `/opt/actions-runner/_work/modules/modules/.nf-test-1f13cf667b8540e41097df6db39270da.nf` [crazy_bardeen] DSL2 - revision: e07257eb1e
    > [be/bff14d] Submitted process > FLYE (test)
    > ERROR ~ Error executing process > 'FLYE (test)'
    > 
    > Caused by:
    >   Process `FLYE (test)` terminated with an error exit status (1)
    > 
    > 
    > Command executed:
    > 
    >   flye \
    >       --pacbio-raw \
    >       test_hifi.fastq.gz \
    >       --out-dir . \
    >       --threads \
    >       2 \
    >   
    >   
    >   gzip -c assembly.fasta > test.assembly.fasta.gz
    >   gzip -c assembly_graph.gfa > test.assembly_graph.gfa.gz
    >   gzip -c assembly_graph.gv > test.assembly_graph.gv.gz
    >   mv assembly_info.txt test.assembly_info.txt
    >   mv flye.log test.flye.log
    >   mv params.json test.params.json
    >   
    >   cat <<-END_VERSIONS > versions.yml
    >   "FLYE":
    >       flye: $( flye --version )
    >   END_VERSIONS
    > 
    > Command exit status:
    >   1
    > 
    > Command output:
    >   (empty)
    > 
    > Command error:
    >   Unable to find image 'quay.io/biocontainers/flye:2.9--py39h6935b12_1' locally
    >   2.9--py39h6935b12_1: Pulling from biocontainers/flye
    >   c1a16a04cedd: Pulling fs layer
    >   4ca545ee6d5d: Pulling fs layer
    >   5589b407763f: Pulling fs layer
    >   4ca545ee6d5d: Verifying Checksum
    >   4ca545ee6d5d: Download complete
    >   c1a16a04cedd: Verifying Checksum
    >   c1a16a04cedd: Download complete
    >   c1a16a04cedd: Pull complete
    >   4ca545ee6d5d: Pull complete
    >   5589b407763f: Verifying Checksum
    >   5589b407763f: Download complete
    >   5589b407763f: Pull complete
    >   Digest: sha256:5220c8fda54fef61da79b98a7407b57fd0fdd7968f57e57efffdf498d2c601c0
    >   Status: Downloaded newer image for quay.io/biocontainers/flye:2.9--py39h6935b12_1
    >   WARNING: Your kernel does not support CPU shares or the cgroup is not mounted. Shares discarded.
    >   [2024-09-06 14:42:04] INFO: Starting Flye 2.9-b1768
    >   [2024-09-06 14:42:04] INFO: >>>STAGE: configure
    >   [2024-09-06 14:42:04] INFO: Configuring run
    >   [2024-09-06 14:42:04] INFO: Total read length: 3763116
    >   [2024-09-06 14:42:04] INFO: Reads N50/N90: 18494 / 16030
    >   [2024-09-06 14:42:04] INFO: Minimum overlap set to 10000
    >   [2024-09-06 14:42:04] INFO: >>>STAGE: assembly
    >   [2024-09-06 14:42:04] INFO: Assembling disjointigs
    >   [2024-09-06 14:42:04] INFO: Reading sequences
    >   [2024-09-06 14:42:04] ERROR: Caught unhandled exception: std::bad_alloc
    >   [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x40453) [0x55f1ca5af453]
    >   [2024-09-06 14:42:04] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(+0xaf56c) [0x7f801217856c]
    >   [2024-09-06 14:42:04] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(+0xaf5be) [0x7f80121785be]
    >   [2024-09-06 14:42:04] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(__cxa_rethrow+0) [0x7f80121787b3]
    >   [2024-09-06 14:42:04] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(_Znwm+0x59) [0x7f8012178be7]
    >   [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x6ff05) [0x55f1ca5def05]
    >   [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x3d060) [0x55f1ca5ac060]
    >   [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x18ab2) [0x55f1ca587ab2]
    >   [2024-09-06 14:42:04] ERROR: 	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f8011d7209b]
    >   [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x18c59) [0x55f1ca587c59]
    >   [2024-09-06 14:42:04] ERROR: Command '['flye-modules', 'assemble', '--reads', 'test_hifi.fastq.gz', '--out-asm', '00-assembly/draft_assembly.fasta', '--config', '/usr/local/lib/python3.9/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', 'flye.log', '--threads', '2', '--min-ovlp', '10000']' died with <Signals.SIGABRT: 6>.
    >   [2024-09-06 14:42:04] ERROR: Pipeline aborted
    > 
    > Work dir:
    >   /home/ubuntu/tests/1f13cf667b8540e41097df6db39270da/work/be/bff14d28dea692576da0fe9f8a85e0
    > 
    > Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
    > 
    >  -- Check '/home/ubuntu/tests/1f13cf667b8540e41097df6db39270da/meta/nextflow.log' file for details
    > WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
Assertion failed: 

assert process.success
       |       |
       FLYE    false

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.RuntimeException: Different Snapshot:
--- /tmp/expected115778554975486823json                     +++ /tmp/found121445440743980993json                       
@@ -1,10 @@                                                 @@ +1,5 @@                                                 
   1 [                                                        1 [                                                      
   2     [                                                    2     [                                                  
!  3         [                                              ! 3                                                        
-  4             {                                                                                                     
-  5                 "id": "test"                                                                                      
-  6             },                                                                                                    
-  7             "test.params.json:md5,54b576cb6d4d27656878                                                            
a7fd3657bde9"                                                                                                          
-  8         ]                                                                                                         
   9     ]                                                    4     ]                                                  
  10 ]                                                        5 ]                                                      

    FAILED (36.641s)

  Assertion failed: 
  
  9 of 9 assertions failed
  
  Nextflow stdout:
  
  N E X T F L O W  ~  version 24.04.4
  Launching `/opt/actions-runner/_work/modules/modules/.nf-test-1f13cf667b8540e41097df6db39270da.nf` [crazy_bardeen] DSL2 - revision: e07257eb1e
  [be/bff14d] Submitted process > FLYE (test)
  ERROR ~ Error executing process > 'FLYE (test)'
  
  Caused by:
    Process `FLYE (test)` terminated with an error exit status (1)
  
  
  Command executed:
  
    flye \
        --pacbio-raw \
        test_hifi.fastq.gz \
        --out-dir . \
        --threads \
        2 \
    
    
    gzip -c assembly.fasta > test.assembly.fasta.gz
    gzip -c assembly_graph.gfa > test.assembly_graph.gfa.gz
    gzip -c assembly_graph.gv > test.assembly_graph.gv.gz
    mv assembly_info.txt test.assembly_info.txt
    mv flye.log test.flye.log
    mv params.json test.params.json
    
    cat <<-END_VERSIONS > versions.yml
    "FLYE":
        flye: $( flye --version )
    END_VERSIONS
  
  Command exit status:
    1
  
  Command output:
    (empty)
  
  Command error:
    Unable to find image 'quay.io/biocontainers/flye:2.9--py39h6935b12_1' locally
    2.9--py39h6935b12_1: Pulling from biocontainers/flye
    c1a16a04cedd: Pulling fs layer
    4ca545ee6d5d: Pulling fs layer
    5589b407763f: Pulling fs layer
    4ca545ee6d5d: Verifying Checksum
    4ca545ee6d5d: Download complete
    c1a16a04cedd: Verifying Checksum
    c1a16a04cedd: Download complete
    c1a16a04cedd: Pull complete
    4ca545ee6d5d: Pull complete
    5589b407763f: Verifying Checksum
    5589b407763f: Download complete
    5589b407763f: Pull complete
    Digest: sha256:5220c8fda54fef61da79b98a7407b57fd0fdd7968f57e57efffdf498d2c601c0
    Status: Downloaded newer image for quay.io/biocontainers/flye:2.9--py39h6935b12_1
    WARNING: Your kernel does not support CPU shares or the cgroup is not mounted. Shares discarded.
    [2024-09-06 14:42:04] INFO: Starting Flye 2.9-b1768
    [2024-09-06 14:42:04] INFO: >>>STAGE: configure
    [2024-09-06 14:42:04] INFO: Configuring run
    [2024-09-06 14:42:04] INFO: Total read length: 3763116
    [2024-09-06 14:42:04] INFO: Reads N50/N90: 18494 / 16030
    [2024-09-06 14:42:04] INFO: Minimum overlap set to 10000
    [2024-09-06 14:42:04] INFO: >>>STAGE: assembly
    [2024-09-06 14:42:04] INFO: Assembling disjointigs
    [2024-09-06 14:42:04] INFO: Reading sequences
    [2024-09-06 14:42:04] ERROR: Caught unhandled exception: std::bad_alloc
    [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x40453) [0x55f1ca5af453]
    [2024-09-06 14:42:04] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(+0xaf56c) [0x7f801217856c]
    [2024-09-06 14:42:04] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(+0xaf5be) [0x7f80121785be]
    [2024-09-06 14:42:04] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(__cxa_rethrow+0) [0x7f80121787b3]
    [2024-09-06 14:42:04] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(_Znwm+0x59) [0x7f8012178be7]
    [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x6ff05) [0x55f1ca5def05]
    [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x3d060) [0x55f1ca5ac060]
    [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x18ab2) [0x55f1ca587ab2]
    [2024-09-06 14:42:04] ERROR: 	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f8011d7209b]
    [2024-09-06 14:42:04] ERROR: 	flye-modules(+0x18c59) [0x55f1ca587c59]
    [2024-09-06 14:42:04] ERROR: Command '['flye-modules', 'assemble', '--reads', 'test_hifi.fastq.gz', '--out-asm', '00-assembly/draft_assembly.fasta', '--config', '/usr/local/lib/python3.9/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', 'flye.log', '--threads', '2', '--min-ovlp', '10000']' died with <Signals.SIGABRT: 6>.
    [2024-09-06 14:42:04] ERROR: Pipeline aborted
  
  Work dir:
    /home/ubuntu/tests/1f13cf667b8540e41097df6db39270da/work/be/bff14d28dea692576da0fe9f8a85e0
  
  Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
  
   -- Check '/home/ubuntu/tests/1f13cf667b8540e41097df6db39270da/meta/nextflow.log' file for details
  WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
  Nextflow stderr:
  
  

  Test [10c69ffd] 'flye_pacbio_corr' 
    > N E X T F L O W  ~  version 24.04.4
    > Launching `/opt/actions-runner/_work/modules/modules/.nf-test-10c69ffdf4344c468aec0a2fe7afef39.nf` [pedantic_jepsen] DSL2 - revision: 35e49e01ae
    > [6b/57a880] Submitted process > FLYE (test)
    PASSED (305.71s)
  Test [9e8f6efe] 'flye_pacbio_hifi' 
    > N E X T F L O W  ~  version 24.04.4
    > Launching `/opt/actions-runner/_work/modules/modules/.nf-test-9e8f6efeade9c8e04b50d9bfcc1fb487.nf` [angry_murdock] DSL2 - revision: 80b7980d0e
    > [1f/a94979] Submitted process > FLYE (test)
    PASSED (165.521s)
  Test [19c459c2] 'flye_nano_raw' 
    > N E X T F L O W  ~  version 24.04.4
    > Launching `/opt/actions-runner/_work/modules/modules/.nf-test-19c459c23bc427825ad1b63d502f911d.nf` [deadly_mestorf] DSL2 - revision: c9007375eb
    > [4f/ab877c] Submitted process > FLYE (test)
    > ERROR ~ Error executing process > 'FLYE (test)'
    > 
    > Caused by:
    >   Process `FLYE (test)` terminated with an error exit status (1)
    > 
    > 
    > Command executed:
    > 
    >   flye \
    >       --nano-raw \
    >       test_hifi.fastq.gz \
    >       --out-dir . \
    >       --threads \
    >       2 \
    >   
    >   
    >   gzip -c assembly.fasta > test.assembly.fasta.gz
    >   gzip -c assembly_graph.gfa > test.assembly_graph.gfa.gz
    >   gzip -c assembly_graph.gv > test.assembly_graph.gv.gz
    >   mv assembly_info.txt test.assembly_info.txt
    >   mv flye.log test.flye.log
    >   mv params.json test.params.json
    >   
    >   cat <<-END_VERSIONS > versions.yml
    >   "FLYE":
    >       flye: $( flye --version )
    >   END_VERSIONS
    > 
    > Command exit status:
    >   1
    > 
    > Command output:
    >   (empty)
    > 
    > Command error:
    >   WARNING: Your kernel does not support CPU shares or the cgroup is not mounted. Shares discarded.
    >   [2024-09-06 14:50:12] INFO: Starting Flye 2.9-b1768
    >   [2024-09-06 14:50:12] INFO: >>>STAGE: configure
    >   [2024-09-06 14:50:12] INFO: Configuring run
    >   [2024-09-06 14:50:12] INFO: Total read length: 3763116
    >   [2024-09-06 14:50:12] INFO: Reads N50/N90: 18494 / 16030
    >   [2024-09-06 14:50:12] INFO: Minimum overlap set to 10000
    >   [2024-09-06 14:50:12] INFO: >>>STAGE: assembly
    >   [2024-09-06 14:50:12] INFO: Assembling disjointigs
    >   [2024-09-06 14:50:12] INFO: Reading sequences
    >   [2024-09-06 14:50:12] ERROR: Caught unhandled exception: std::bad_alloc
    >   [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x40453) [0x557964c72453]
    >   [2024-09-06 14:50:12] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(+0xaf56c) [0x7efebe9f856c]
    >   [2024-09-06 14:50:12] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(+0xaf5be) [0x7efebe9f85be]
    >   [2024-09-06 14:50:12] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(__cxa_rethrow+0) [0x7efebe9f87b3]
    >   [2024-09-06 14:50:12] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(_Znwm+0x59) [0x7efebe9f8be7]
    >   [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x6ff05) [0x557964ca1f05]
    >   [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x3d060) [0x557964c6f060]
    >   [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x18ab2) [0x557964c4aab2]
    >   [2024-09-06 14:50:12] ERROR: 	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7efebe5f209b]
    >   [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x18c59) [0x557964c4ac59]
    >   [2024-09-06 14:50:12] ERROR: Command '['flye-modules', 'assemble', '--reads', 'test_hifi.fastq.gz', '--out-asm', '00-assembly/draft_assembly.fasta', '--config', '/usr/local/lib/python3.9/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', 'flye.log', '--threads', '2', '--min-ovlp', '10000']' died with <Signals.SIGABRT: 6>.
    >   [2024-09-06 14:50:12] ERROR: Pipeline aborted
    > 
    > Work dir:
    >   /home/ubuntu/tests/19c459c23bc427825ad1b63d502f911d/work/4f/ab877cae561c949d86bc468cf62d8b
    > 
    > Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
    > 
    >  -- Check '/home/ubuntu/tests/19c459c23bc427825ad1b63d502f911d/meta/nextflow.log' file for details
    > WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
Assertion failed: 

assert process.success
       |       |
       FLYE    false

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.RuntimeException: Different Snapshot:
--- /tmp/expected12645586874537621628json                   +++ /tmp/found12177145911578711214json                     
@@ -1,10 @@                                                 @@ +1,5 @@                                                 
   1 [                                                        1 [                                                      
   2     [                                                    2     [                                                  
!  3         [                                              ! 3                                                        
-  4             {                                                                                                     
-  5                 "id": "test"                                                                                      
-  6             },                                                                                                    
-  7             "test.params.json:md5,54b576cb6d4d27656878                                                            
a7fd3657bde9"                                                                                                          
-  8         ]                                                                                                         
   9     ]                                                    4     ]                                                  
  10 ]                                                        5 ]                                                      

    FAILED (16.652s)

  Assertion failed: 
  
  9 of 9 assertions failed
  
  Nextflow stdout:
  
  N E X T F L O W  ~  version 24.04.4
  Launching `/opt/actions-runner/_work/modules/modules/.nf-test-19c459c23bc427825ad1b63d502f911d.nf` [deadly_mestorf] DSL2 - revision: c9007375eb
  [4f/ab877c] Submitted process > FLYE (test)
  ERROR ~ Error executing process > 'FLYE (test)'
  
  Caused by:
    Process `FLYE (test)` terminated with an error exit status (1)
  
  
  Command executed:
  
    flye \
        --nano-raw \
        test_hifi.fastq.gz \
        --out-dir . \
        --threads \
        2 \
    
    
    gzip -c assembly.fasta > test.assembly.fasta.gz
    gzip -c assembly_graph.gfa > test.assembly_graph.gfa.gz
    gzip -c assembly_graph.gv > test.assembly_graph.gv.gz
    mv assembly_info.txt test.assembly_info.txt
    mv flye.log test.flye.log
    mv params.json test.params.json
    
    cat <<-END_VERSIONS > versions.yml
    "FLYE":
        flye: $( flye --version )
    END_VERSIONS
  
  Command exit status:
    1
  
  Command output:
    (empty)
  
  Command error:
    WARNING: Your kernel does not support CPU shares or the cgroup is not mounted. Shares discarded.
    [2024-09-06 14:50:12] INFO: Starting Flye 2.9-b1768
    [2024-09-06 14:50:12] INFO: >>>STAGE: configure
    [2024-09-06 14:50:12] INFO: Configuring run
    [2024-09-06 14:50:12] INFO: Total read length: 3763116
    [2024-09-06 14:50:12] INFO: Reads N50/N90: 18494 / 16030
    [2024-09-06 14:50:12] INFO: Minimum overlap set to 10000
    [2024-09-06 14:50:12] INFO: >>>STAGE: assembly
    [2024-09-06 14:50:12] INFO: Assembling disjointigs
    [2024-09-06 14:50:12] INFO: Reading sequences
    [2024-09-06 14:50:12] ERROR: Caught unhandled exception: std::bad_alloc
    [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x40453) [0x557964c72453]
    [2024-09-06 14:50:12] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(+0xaf56c) [0x7efebe9f856c]
    [2024-09-06 14:50:12] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(+0xaf5be) [0x7efebe9f85be]
    [2024-09-06 14:50:12] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(__cxa_rethrow+0) [0x7efebe9f87b3]
    [2024-09-06 14:50:12] ERROR: 	/usr/local/bin/../lib/libstdc++.so.6(_Znwm+0x59) [0x7efebe9f8be7]
    [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x6ff05) [0x557964ca1f05]
    [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x3d060) [0x557964c6f060]
    [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x18ab2) [0x557964c4aab2]
    [2024-09-06 14:50:12] ERROR: 	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7efebe5f209b]
    [2024-09-06 14:50:12] ERROR: 	flye-modules(+0x18c59) [0x557964c4ac59]
    [2024-09-06 14:50:12] ERROR: Command '['flye-modules', 'assemble', '--reads', 'test_hifi.fastq.gz', '--out-asm', '00-assembly/draft_assembly.fasta', '--config', '/usr/local/lib/python3.9/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', 'flye.log', '--threads', '2', '--min-ovlp', '10000']' died with <Signals.SIGABRT: 6>.
    [2024-09-06 14:50:12] ERROR: Pipeline aborted
  
  Work dir:
    /home/ubuntu/tests/19c459c23bc427825ad1b63d502f911d/work/4f/ab877cae561c949d86bc468cf62d8b
  
  Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
  
   -- Check '/home/ubuntu/tests/19c459c23bc427825ad1b63d502f911d/meta/nextflow.log' file for details
  WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
  Nextflow stderr:
  
  

  Test [89baea7b] 'flye_nano_corr' 
    > N E X T F L O W  ~  version 24.04.4
    > Launching `/opt/actions-runner/_work/modules/modules/.nf-test-89baea7bdfe2bdad6c2fab8ce541cf88.nf` [voluminous_meitner] DSL2 - revision: 53c43a1c11
    > [12/3443b4] Submitted process > FLYE (test)
    PASSED (281.365s)
  Test [b1e1b060] 'flye_nano_hq' 
    > N E X T F L O W  ~  version 24.04.4
    > Launching `/opt/actions-runner/_work/modules/modules/.nf-test-b1e1b060415e4698a2da2746d0b1c8c1.nf` [drunk_banach] DSL2 - revision: a681e08d95
    > [95/06924e] Submitted process > FLYE (test)
    PASSED (266.28s)
    Obsolete snapshots can only be checked if all tests of a file are executed successful.


FAILURE: Executed 6 tests in 1072.202s (2 failed)

Wrote TAP report to file test.tap

Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by famosab**
## PR checklist

Closes #6609 
Closes #6606

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [x] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

**Comment by famosab** [comment]
The tests fail since there is not enough RAM which can be allocated. Locally I needed 8GB but 7.5 GB seems to be the max in the CI so I changed it to 7GB which seems to not be enough.

**Comment by SPPearce** [comment]
> The tests fail since there is not enough RAM which can be allocated. Locally I needed 8GB but 7.5 GB seems to be the max in the CI so I changed it to 7GB which seems to not be enough.

What happens if we reduce the size of the input file a bit?

**Comment by famosab** [comment]
> Now the input data type (hifi) doesn't match with the mode, e.g. `--nano-raw`, which would probably increase the RAM usage. You could probably fix this by changing the test data as suggested by @SPPearce, for example from human to sarscov2.

I saw that aswell and was confused already. Would you just use a sarscov2 fasta then?

> But would it not be reasonable to remove mode as an input completely, and let that be supplied with ext.args? And just run one test with one input data type and the matching mode in a config?

I just took the implementation as is but I also was confused by that. If @mirpedrol agrees I can change it to ext.args.

**Comment by famosab** [comment]
I am going to try with virus hifi read data provided by pacbio.

**Comment by mirpedrol** [comment]
Hi! Regarding the `mode` variable, it is an exception in this module because it is a positional argument used to provide the reads file.

**Comment by famosab** [comment]
Even with the small datasets the tests are still failing. :(

**Comment by fellen31** [comment]
> Even with the small datasets the tests are still failing. :(

I think for Flye to run you would need the correct data type supplied with the correct parameter, i.e. you can't usually use hifi-data with --nano-raw, you would need old nanopore data. Either because Flye uses too much RAM with nanopore, or because it will fail in the middle because it was not the datatype it expected. 

Looks to me like `flye_pacbio_hifi` is passing though, so in this case maybe it's ok to only test one of the modes?

**Comment by SPPearce** [comment]
> > Even with the small datasets the tests are still failing. :(
> 
> I think for Flye to run you would need the correct data type supplied with the correct parameter, i.e. you can't usually use hifi-data with --nano-raw, you would need old nanopore data. Either because Flye uses too much RAM with nanopore, or because it will fail in the middle because it was not the datatype it expected.
> 
> Looks to me like `flye_pacbio_hifi` is passing though, so in this case maybe it's ok to only test one of the modes?

I'm happy to only test one mode if we can't test multiple.

**Review by sateeshperi — APPROVED** [review]
lgtm

**Pull request merged**
