### PR TITLE
add spatyper

### PR DESCRIPTION
**Pull request by rpetit3**
## PR checklist

Closes https://github.com/nf-core/modules/issues/703

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `<SOFTWARE>.version.txt` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

__NOTE:__ I think there is an issue with the Docker/Singularity containers. It passes with Conda.

Singularity
```
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  FATAL:   container creation failed: mount /tmp/pytest_workflow_5psgjkj7/spatyper_test_spatyper_enrich/work->/tmp/pytest_workflow_5psgjkj7/spatyper_test_spatyper_enrich/work error: while mounting /tmp/pytest_workflow_5psgjkj7/spatyper_test_spatyper_enrich/work: destination /tmp/pytest_workflow_5psgjkj7/spatyper_test_spatyper_enrich/work doesn't exist in container
```

Docker
```

Command output:
  Start the identification of repeats in Spa protein:
  + Check or download repeats fasta file in folder:  /usr/local/bin

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Traceback (most recent call last):
    File "/usr/local/bin/spaTyper", line 92, in <module>
      args.repeat_file = spaTyper.utils.download_file_repeats(args.folder, args.debug)
    File "/usr/local/lib/python3.9/site-packages/spaTyper/utils.py", line 134, in download_file_repeats
      print_time_stamp(filename_stamp)
    File "/usr/local/lib/python3.9/site-packages/spaTyper/utils.py", line 192, in print_time_stamp
      timefile = open(out, 'w')
  PermissionError: [Errno 13] Permission denied: '/usr/local/bin/.success'
```

### CODE REVIEW

**Comment by pontus** [comment]
Singularity has the same issue as docker (the quoted error for singularity is a red herring, it shows the same further down).

After a (very) quick look, it seems the correct would be to use the `-d`/`--folder`.

Conda would work because it is installed as the user running - that would not work for having a centrally managed environment, though.

**Comment by rpetit3** [comment]
I have a proposed solution, please let me know your thoughts.

The spatyper database doesn't change very often, so I'm going to rebuild the conda recipe to include a default database. Then I'll make the REPEAT_FILE (`-r`) and REPEAT_ORDER_FILE (`-o`) additional inputs incase the use wants to provide their database, which I'm guessing will be very rare.

**Comment by pontus** [comment]
I'm not sure I follow your thoughts correctly but for clarity,  the problem seems to be how the program creates flag files in the directory of the database (?). So using files supplied in the container requires some additional work (I haven't checked but a first approach would be to make a link in the work area or `$TMPDIR` and reference that).

**Comment by rpetit3** [comment]
_the problem seems to be how the program creates flag files in the directory of the database (?)._

That's totally it, I've worked with the spatyper dev, so I'm going to get his thoughts on this. Thank you very much @pontus!

**Comment by rpetit3** [comment]
Update on this.

I'm rebuilding the Bioconda recipe to include a `download-spatypes.sh` script.  Will revisit once I get that cleared up

**Comment by rpetit3** [comment]
Update on this, I have a PR (https://github.com/bioconda/bioconda-recipes/pull/30622) that should help solve this for us.

Either the user can use the included database files (a csv and a fasta file) or they can use `download-spatypes.sh` to download the files locally.

I think this means there should be two modules for spaTyper: `spatyper/download` and `spatyper/spatyper`

**Comment by rpetit3** [comment]
Example of how this works is here: https://github.com/bioconda/bioconda-recipes/pull/30622#issuecomment-925099026

I think an important change is It provides a method within the spatyper container to download the required inputs to your local `work` directory and pass them to next module. This also saves the user from having to figure out where to download the files from. 

There is also the option for users to skip the download and just use the files already included in the container.

**Comment by pontus** [comment]
I don't object to those changes, but AFAICT the nextflow module still needs changes (only slightly different due to these changes), so I'm uncertain about the overall benefits of that PR (but I don't know the use case here).

The files supplied in the container will still not be usable without a link/similar as I understand it.

**Comment by rpetit3** [comment]
I goofed and reforked, and lost this branch. Reopened PR https://github.com/nf-core/modules/pull/784 to go forward.

I have a solution, just awaiting PR to be merged into Bioconda

**Pull request closed without merging**
