### PR TITLE
update tests for new config

### PR DESCRIPTION
**Pull request by rpetit3**
- [X] blastn
- [X] flash
- [X] makeblastdb
- [X] methyldackel/extract
- [X] methyldackel/mbias
- [X] mosdepth
- [X] optitype
- [X] pangolin
- [X] quast
- [X] qualimap/bamqc
- [ ] seacr/callpeak
- [ ] shovill 
- [x] spades
- [ ] star/align
- [ ] star/genomegenerate
- [X] tabix/bgzip
- [X] tabix/tabix
- [X] tiddit/sv
- [ ] unicycler

### Shovill
I used external test data from nf-core/test-dataset (https://github.com/nf-core/modules/blob/master/tests/software/shovill/main.nf#L12-L13) because the included did not produce contigs which Shovill does not like.

I think its worth discussing how to handle these cases.

### Uses "Generic" inputs
The following use "generic" inputs that are no longer available

- [ ] seacr/callpeak
- [ ] spades
- [ ] star/align
- [ ] star/genomegenerate

## PR checklist

Related to https://github.com/nf-core/modules/issues/363

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `<SOFTWARE>.version.txt` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by rpetit3** [comment]
Going to leave it for the day, and start digging into these red X's tomorrow

**Comment by rpetit3** [comment]
I manually tested each locally, most should be fixed. 

SPAdes/Unicycler does not like the SARS-CoV-2 test FASTQs. These tests were originally using FASTQs under `generic`

**Comment by drpatelh** [comment]
This is awesome, thanks @rpetit3 ! Yup, I noticed those two assemblers were using test data from `generic`. Maybe we wait for the human data to be added and we can just change the paths in the `main.nf` for those particular tests?

`flash` tests are passing on Docker and failing on Singularity and Conda for some reason?

Current changes look 👌🏽 Only a few left to add? Ping me letting me know when you are done.

**Comment by rpetit3** [comment]
Noticed that on flash as well. I tested locally on 20-11-0-edge, using Docker and Sincularity (`TMPDIR=~ PROFILE=singularity pytest --symlink --keep-workflow-wd --tag flash`) and they each pass.

I'm not sure what might be causing the differing MD5s on the CI, but not locally.

SPAdes and Unicycler, I'll look out for the incoming test data.

**Comment by drpatelh** [comment]
SPAdes tests have been fixed here https://github.com/nf-core/modules/pull/396 @rpetit3 . Maybe we get this PR in for now but be great if you are able to fix the rest in a separate PR when the appropriate test data is added.

I have also updated the main issue https://github.com/nf-core/modules/issues/363 to reflect the modules that still need to be fixed/added properly.

**Review by drpatelh — APPROVED** [review]

**Pull request merged**
