### PR TITLE
Feat/cat_fastq nf-test

### PR DESCRIPTION
**Pull request by Joon-Klaps**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Review by sateeshperi — APPROVED** [review]

**Comment by Joon-Klaps** [comment]
Conda and docker images aren't the same which causes distinct md5sum for versions.yml
```nextflow
    conda "conda-forge::sed=4.7"
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/ubuntu:20.04' :
        'nf-core/ubuntu:20.04' }"
```

**Comment by FriederikeHanssen** [comment]
Is this ready?

**Comment by sateeshperi** [comment]
this module doesn't create a consistent snap for the versions......and im guessing there will be modules like this....just need to document this

**Review by Emiller88 — APPROVED** [review]
LGTM!

**Comment by maxulysse** [comment]
How is this one not making consistent versions?
Did we investigate more?

**Pull request merged**
