### PR TITLE
update sentieon/modules to use quay.io

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by maxulysse** [comment]
Singularity issues will be fixed by https://github.com/nf-core/modules/pull/3499 on the modules side.
They're already fixed in the pipeline by `singularity.registry = quay.io`

**Comment by maxulysse** [comment]
> LGTM! But tests are failing cry

Yeah, I know, I need other PRs to be merged for the tests to work on singularity as well, but at least, the docker tests are working.

**Comment by asp8200** [comment]
> > LGTM! But tests are failing cry
> 
> Yeah, I know, I need other PRs to be merged for the tests to work on singularity as well, but at least, the docker tests are working.

I can run some singularity-based of the modules over in Sarek

**Comment by maxulysse** [comment]
> > > LGTM! But tests are failing cry
> > 
> > 
> > Yeah, I know, I need other PRs to be merged for the tests to work on singularity as well, but at least, the docker tests are working.
> 
> I can run some singularity-based of the modules over in Sarek

It should work in sarek, but it'll be good to test anyway

**Comment by asp8200** [comment]
I've updated the sentieon-modules in Sarek locally. This singularity-based pytest worked fine:

`TMPDIR=/home/ubuntu/nf_tmp PROFILE=singularity pytest --tag sentieon/bwamem --symlink --kwdof --color=yes`

I'll continue to run them all.

**Comment by maxulysse** [comment]
Then we should be good on the pipeline side.
Thanks @asp8200

**Pull request merged**
