### PR TITLE
Update container build number

### PR DESCRIPTION
**Pull request by mahesh-panchal**
Updates the purge dups container build to use the more recent build. The most recent build includes missing tools.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by sateeshperi — APPROVED** [review]

**Comment by mahesh-panchal** [comment]
What's the procedure now with the failing tests?

**Comment by SPPearce** [comment]
It's giving a segfault on the CI, does it still work locally?

**Comment by mahesh-panchal** [comment]
Yes, at least in Gitpod. 

```console
$ nf-core modules test purgedups/purgedups 

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.10 - https://nf-co.re


INFO     Press enter to use default values (shown in brackets) or type your own responses                                                                                                      
? Choose software profile Conda
INFO     Setting environment variable '$PROFILE' to 'conda'                                                                                                                                    
───────────────────────────────────────────────────────────────────────────────────── purgedups/purgedups ─────────────────────────────────────────────────────────────────────────────────────
INFO     Running pytest for module 'purgedups/purgedups'                                                                                                                                       
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /workspace/modules
configfile: pytest.ini
plugins: workflow-2.0.1
collecting ... 
collected 1856 items                                                                                                                                                                          

purgedups purgedups test_purgedups_purgedups:
        command:   nextflow run ./tests/modules/nf-core/purgedups/purgedups -entry test_purgedups_purgedups -c ./tests/config/nextflow.config -c ./tests/modules/nf-core/purgedups/purgedups/nextflow.config
        directory: /tmp/pytest_workflow_cvv10_pr/purgedups_purgedups_test_purgedups_purgedups
        stdout:    /tmp/pytest_workflow_cvv10_pr/purgedups_purgedups_test_purgedups_purgedups/log.out
        stderr:    /tmp/pytest_workflow_cvv10_pr/purgedups_purgedups_test_purgedups_purgedups/log.err
'purgedups purgedups test_purgedups_purgedups' done.

tests/test_versions_yml.py ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [  8%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 18%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 28%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 37%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 47%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 57%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 67%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 77%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 87%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 97%]
ssssssssssssssssssssssssssssssssssssssssssssssss                                                                                                                                        [ 99%]
tests/modules/nf-core/purgedups/purgedups/test.yml .....                                                                                                                                [100%] Keeping temporary directories and logs. Use '--kwd' or '--keep-workflow-wd' to disable this behaviour.


========================================================================= 6 passed, 1850 skipped in 96.81s (0:01:36) ==========================================================================

```

**Comment by mahesh-panchal** [comment]
Actually, the other one segfaults.
```console
$ nf-core modules test purgedups/getseqs

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.10 - https://nf-co.re


INFO     Press enter to use default values (shown in brackets) or type your own responses                                                                                                      
? Choose software profile Conda
INFO     Setting environment variable '$PROFILE' to 'conda'                                                                                                                                    
────────────────────────────────────────────────────────────────────────────────────── purgedups/getseqs ──────────────────────────────────────────────────────────────────────────────────────
INFO     Running pytest for module 'purgedups/getseqs'                                                                                                                                         
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /workspace/modules
configfile: pytest.ini
plugins: workflow-2.0.1
collecting ... 
collected 1856 items                                                                                                                                                                          

purgedups getseqs test_purgedups_getseqs:
        command:   nextflow run ./tests/modules/nf-core/purgedups/getseqs -entry test_purgedups_getseqs -c ./tests/config/nextflow.config -c ./tests/modules/nf-core/purgedups/getseqs/nextflow.config
        directory: /tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs
        stdout:    /tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs/log.out
        stderr:    /tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs/log.err
'purgedups getseqs test_purgedups_getseqs' done.

tests/test_versions_yml.py ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [  8%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 18%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 28%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 37%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 47%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 57%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 67%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssFsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 77%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 87%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 97%]
ssssssssssssssssssssssssssssssssssssssssssssssss                                                                                                                                        [ 99%]
tests/modules/nf-core/purgedups/getseqs/test.yml Fssss                                                                                                                                  [100%] Keeping temporary directories and logs. Use '--kwd' or '--keep-workflow-wd' to disable this behaviour.


========================================================================================== FAILURES ===========================================================================================
___________________________________________________________ test_ensure_valid_version_yml[purgedups getseqs test_purgedups_getseqs] ___________________________________________________________

workflow_dir = PosixPath('/tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs')

    @pytest.mark.workflow(*_get_workflow_names())
    def test_ensure_valid_version_yml(workflow_dir):
        workflow_dir = Path(workflow_dir)
        software_name = workflow_dir.name.split("_")[0].lower()
        try:
            versions_yml_file = workflow_dir / f"output/{software_name}/versions.yml"
>           versions_yml = versions_yml_file.read_text()

tests/test_versions_yml.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/opt/conda/lib/python3.11/pathlib.py:1058: in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = PosixPath('/tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs/output/purgedups/versions.yml'), mode = 'r', buffering = -1, encoding = 'locale', errors = None
newline = None

    def open(self, mode='r', buffering=-1, encoding=None,
             errors=None, newline=None):
        """
        Open the file pointed by this path and return a file object, as
        the built-in open() function does.
        """
        if "b" not in mode:
            encoding = io.text_encoding(encoding)
>       return io.open(self, mode, buffering, encoding, errors, newline)
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs/output/purgedups/versions.yml'

/opt/conda/lib/python3.11/pathlib.py:1044: FileNotFoundError

During handling of the above exception, another exception occurred:

workflow_dir = PosixPath('/tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs')

    @pytest.mark.workflow(*_get_workflow_names())
    def test_ensure_valid_version_yml(workflow_dir):
        workflow_dir = Path(workflow_dir)
        software_name = workflow_dir.name.split("_")[0].lower()
        try:
            versions_yml_file = workflow_dir / f"output/{software_name}/versions.yml"
            versions_yml = versions_yml_file.read_text()
        except FileNotFoundError:
>           raise AssertionError(
                dedent(
                    f"""\
                    `versions.yml` not found in the output directory.
                    Expected path: `{versions_yml_file}`
    
                    This can have multiple reasons:
                    * The test-workflow failed before a `versions.yml` could be generated.
                    * The workflow name in `test.yml` does not start with the tool name.
                    """
                )
            )
E           AssertionError: `versions.yml` not found in the output directory.
E           Expected path: `/tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs/output/purgedups/versions.yml`
E           
E           This can have multiple reasons:
E           * The test-workflow failed before a `versions.yml` could be generated.
E           * The workflow name in `test.yml` does not start with the tool name.

tests/test_versions_yml.py:33: AssertionError
________________________________________________________________________________________ test session _________________________________________________________________________________________
'purgedups getseqs test_purgedups_getseqs' exited with exit code '1' instead of '0'.
stderr: 
stdout: s > test_purgedups_getseqs:PURGEDUPS_GETSEQS (test) [100%] 1 of 1, failed: 1 ✘
ERROR ~ Error executing process > 'test_purgedups_getseqs:PURGEDUPS_GETSEQS (test)'

Caused by:
  Process `test_purgedups_getseqs:PURGEDUPS_GETSEQS (test)` terminated with an error exit status (139)

Command executed:

  get_seqs \
       \
      -e test.bed \
      -p test \
      genome.fasta
  
  cat <<-END_VERSIONS > versions.yml
  "test_purgedups_getseqs:PURGEDUPS_GETSEQS":
      purgedups: $( purge_dups -h |& sed '3!d; s/.*: //' )
  END_VERSIONS

Command exit status:
  139

Command output:
  (empty)

Command error:
  .command.sh: line 6: 13259 Segmentation fault      get_seqs -e test.bed -p test genome.fasta

Work dir:
  /tmp/pytest_workflow_1qxz12_6/purgedups_getseqs_test_purgedups_getseqs/work/29/f5e3617be5813a504712dbce55d96c

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
=================================================================================== short test summary info ===================================================================================
FAILED tests/test_versions_yml.py::test_ensure_valid_version_yml[purgedups getseqs test_purgedups_getseqs] - AssertionError: `versions.yml` not found in the output directory.
FAILED tests/modules/nf-core/purgedups/getseqs/test.yml::purgedups getseqs test_purgedups_getseqs::exit code should be 0
========================================================================= 2 failed, 1854 skipped in 71.52s (0:01:11) ==========================================================================
```

**Comment by mahesh-panchal** [comment]
Purgedups/getseqs is fixed. There was a typo in the input. No idea why it wasn't flagged earlier. 

I can't replicate the purgedups/purgedups issue on Gitpod. The tests are passing with mamba which is the resolver the CI tests are using.

**Comment by mahesh-panchal** [comment]
This may still be an issue with the conda resolver picking up the wrong build.
Waiting for the next release of conda may fix this.

**Comment by mahesh-panchal** [comment]
Closing. Can be updated when the nf-tests are written.

**Pull request closed without merging**
