### PR TITLE
Update MULTIQC for an additional custom config

### PR DESCRIPTION
**Pull request by jfy133**
Adds ability to have one(!) other custom config to the MultiQC module.

This allows nf-core pipelines to have the default pipeline one, and then a user to modify sections by supplying their second config file, the contents of which [overrides anything common](https://multiqc.info/docs/#configuring-multiqc) with the pipeline base config file. 

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by ewels — APPROVED** [review]
Wonder if we should stick to `custom_` instead of `extra_` to match the params names that we have in pipelines?

Otherwise looks good 👍🏻

**Comment by jfy133** [comment]
> Wonder if we should stick to `custom_` instead of `extra_` to match the params names that we have in pipelines?
> 
> Otherwise looks good 👍🏻

I put it as `extra` because if someone was to use the module outside an nf-core pipeline they might not have a 'default'

**Comment by ggabernet** [comment]
I'm late to the party @jfy133 and @ewels , but is there a reason why not mixing the default config + custom config channels does not work, as it was used until now?
I've just experienced a problem with the current implementation, if the user does not want to provide a custom config, the the channel is empty and the process is not executed

**Comment by ggabernet** [comment]
maybe I missed your discussion in Slack, tried to find something about it but didn't

**Comment by jfy133** [comment]
We weren't even sure if just mixing them straight in worked in the first place. According to the MultiQC docs, each file needs to have `-c` or `--config` at the beginning so they get loaded in sequence.

However your problem shouldn't happen :-1: , can you point to the pipeline code with the new implementation? (Note I am about to make a template update how it should work in theorey...)

**Comment by ggabernet** [comment]
ok great, then I will just look at your implementation ;)

**Comment by ggabernet** [comment]
Ah NVM, forgot to add `.ifEmpty([])`, it works for me now! Thanks for the update!

**Pull request merged**
