### PR TITLE
Remove jinja tags from workflow

### PR DESCRIPTION
**Pull request by ewels**
Workflow was copied from the pipeline template but the jinja2 template tags were still there

### CODE REVIEW

**Comment by nvnieuwk** [comment]
Test comment :p

**Review by nvnieuwk — APPROVED** [review]

**Comment by ewels** [comment]
Follows on from https://github.com/nf-core/modules/pull/2109

Test comments / usage won't work until the PR is merged 👍🏻

**Comment by nvnieuwk** [comment]
It worked though :p

**Comment by ewels** [comment]
> It worked though :p

Weird! Ok I stand corrected 🙇🏻

**Pull request merged**
