### PR TITLE
add stub and the option to compress output for vep

### PR DESCRIPTION
**Pull request by ramprasadn**
## PR checklist

This PR adds a stub section, the option to get compress output, and relevant tests

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]
LGTM.

I'm thinking the only plus about not doing compress output from VEP, is that when we do it with TABIX we also get indexes as well

**Comment by ramprasadn** [comment]
Thanks for taking a look at this @maxulysse I agree with you on tabix. Wish vep had the option to create index for the outputs. That would make things a lot easier 😄

**Comment by maxulysse** [comment]
we can still have a simple tabix process to produce the index, I'll look into it for a subworkflow, I'll ping you on the PR

**Comment by ramprasadn** [comment]
That would be fantastic! 👍🏻

**Pull request merged**
