### PR TITLE
PR for sequenzautils/bam2seqz

### PR DESCRIPTION
**Pull request by kaurravneet4123**
## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `<SOFTWARE>.version.txt` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by kaurravneet4123** [comment]
Hi @drpatelh and @KevinMenden, this module (sequenzautils/bam2seqz) has passed all the tests. Waiting for review!

**Review by KevinMenden — COMMENTED** [review]
hi @kaurravneet4123 , thank you, this looks good to me!

However, since you added test data, could you add an entry in the README.md describing how you createed that?

**Comment by kaurravneet4123** [comment]
Hi @KevinMenden, should I add an entry at the bottom of the README.md? The new test data is an output from another module- sequenzautils/bcwiggle- (which uses sarscov2 genome fasta file as an input).

**Comment by KevinMenden** [comment]
Ah perfect! Yes currently just mention somewhere, I have to rewrite the README.md anyway. So just make sure this information is somewhere on there otherwise I forget :-) thanks!

**Comment by kaurravneet4123** [comment]
> Ah perfect! Yes currently just mention somewhere, I have to rewrite the README.md anyway. So just make sure this information is somewhere on there otherwise I forget :-) thanks!

it's done! @KevinMenden :-)

**Review by KevinMenden — APPROVED** [review]
Perfect, looks good to me, thanks!

**Comment by kaurravneet4123** [comment]
> Perfect, looks good to me, thanks!

thanks for reviewing and merging @KevinMenden  :-)

**Pull request merged**
