### PR TITLE
Added Seqera containers to module spotiflow

### PR DESCRIPTION
**Pull request by FloWuenne**
I exchanged the manually build docker container with docker and singularity containers using the wave community host. I also had to modify the output parameter from `-o` to `--out-dir`. Finally, had to update the nf-test snapshots.

Both docker and singularity worked on my testing in Gitpod!

### CODE REVIEW

**Comment by migueLib** [comment]
I checked the changes and they look good! 
I have a question tho , how does the wave community host differs from the manually build one?  Does it take the pip version of spotiflow?

**Review by migueLib — COMMENTED** [review]
Oppsy I send this message as a comment but I'll type it here again.

I checked the changes and they look good!
I have a question tho , how does the wave community host differs from the manually build one? Does it take the pip version of spotiflow? This is important because the manually built Docker container has the most up to date version of the tool.

**Comment by FloWuenne** [comment]
@migueLib Basically with Wave you can build containers from just an env.yml or a list of packages and you don't need to worry about building, deploying and hosting the container. So all you need to generate any arbitrary wave container is to simply do `wave --conda-file ./env.yml --freeze` and it will build and deploy the container. To get singularity, simply add `--singularity` to the command I wrote. The `env.yml` file here contained the following:
```
name: spotiflow
channels:
  - pytorch
  - conda-forge
dependencies:
  - "python=3.9"
  - "pytorch"
  - "torchvision"
  - "cpuonly"
  - pip:
      - "spotiflow"
```

**Comment by migueLib** [comment]
@FloWuenne  Fantastic! can't wait to try it myself!  On the mean time, is it possible to just use spotiflow directly from the GitHub repo?   

```
name: spotiflow
channels:
  - pytorch
  - conda-forge
dependencies:
  - "python=3.9"
  - "pytorch"
  - "torchvision"
  - "cpuonly"
  - pip:
      - "git+https://github.com/migueLib/spotiflow"
```

**Comment by edmundmiller** [comment]
@migueLib pretty sure you can, but you'll want to add a hash or a version to lock that down.

**Comment by FloWuenne** [comment]
I just tried and run into the following issue when trying to use the github version: https://wave.seqera.io/view/builds/6e20394df519471e_1
It seems that the container building the wave image from conda packages doesn't have git?!

**Comment by edmundmiller** [comment]
Hmm weird it made an image for singularity at least for me 🤷🏻

**Comment by edmundmiller** [comment]
Adding git to the environment worked?

**Comment by FloWuenne** [comment]
Awesome, great fix @edmundmiller!

**Comment by FloWuenne** [comment]
Need to recalculate the nf-test snapshots now for tests to pass @migueLib !

**Comment by edmundmiller** [comment]
Except for the singularity, image doesn't exist? But I used `--await`

**Comment by FloWuenne** [comment]
@edmundmiller Did you build these updated images using wave-cli locally? I am trying to run docker and it's giving me manifest errors suggesting the build is not done yet, but you added these long ago so should exist...

**Comment by FloWuenne** [comment]
Ahh I just tried to rebuild and these github based images seem to fail building?
https://wave.seqera.io/view/builds/d353247491abfe49_2

**Comment by edmundmiller** [comment]
Interesting, but it didn't throw an error at the CLI...
```
#9 168.0       building 'spotiflow.lib.spotflow2d' extension
#9 168.0       Warning: Can't read registry to find the necessary compiler setting
#9 168.0       Make sure that Python modules winreg, win32api or win32con are installed.
```

**Comment by FloWuenne** [comment]
> Interesting, but it didn't throw an error at the CLI...
> 
> ```
> #9 168.0       building 'spotiflow.lib.spotflow2d' extension
> #9 168.0       Warning: Can't read registry to find the necessary compiler setting
> #9 168.0       Make sure that Python modules winreg, win32api or win32con are installed.
> ```

So but the container IDs you put don't work because of that @edmundmiller right? The failing tests seem to suggest the same thing:

```
Unable to find image 'community.wave.seqera.io/library/spotiflow:d353247491abfe49' locally
    docker: Error response from daemon: manifest for community.wave.seqera.io/library/spotiflow:d353247491abfe49 not found: manifest unknown: manifest unknown.
```

**Comment by FloWuenne** [comment]
@edmundmiller Just wanted a quick guidance here. Reverse containers to the pip version of spotiflow which worked? Or do you have a fix for using the github version? I can ping the github failed builds to our Wave team if this seems to be bug!

**Comment by FloWuenne** [comment]
@migueLib For now, I will revert back to using the spotiflow pip package, as the git installation doesn't build the container correctly. Is there a particular reason you need to use the git version? Any features not yet in the pip release?

**Comment by edmundmiller** [comment]
@FloWuenne Yep agreed!

Let's add the environment.yml back though and I'll bypass the branch protections, I'd rather not have to hunt it down later 😬

**Review by edmundmiller — APPROVED** [review]

**Comment by maxulysse** [comment]
> @FloWuenne Yep agreed!
> 
> Let's add the environment.yml back though and I'll bypass the branch protections, I'd rather not have to hunt it down later 😬

Next time, can you create an issue to document that?

**Comment by migueLib** [comment]
@maxulysse & @FloWuenne  I'll work on this module again beginning of next week. 

I was working together with the Spotiflow developers to push adding the tool to Conda and Docker. And now there's official support for both!  😄

**Pull request merged**
