### PR TITLE
DRAFT: Extend output from snpeff

### PR DESCRIPTION
**Pull request by asp8200**
In the Sarek-pipeline, we need the snpEff-module to also output the genes-txt-file and the summary-html-file.

Concerning the test `/home/aspe/dev/fork_modules/tests/modules/snpeff/test.yml`, the test-vcf-file `test.ann.vcf` does contain some variants, but `test.genes.txt` doesn't contain any genes:

```
$ cat test.genes.txt
# The following table is formatted as tab separated values.
#GeneName	GeneId	TranscriptId	BioType
```

The `summary.html`-file indicate there there were 9 errors (and the vcf contains 9 variants):

image
Should those errors give raise to concern?

 

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
can you see what those errors are? Because in the past we had errors with human reads vs c elegans container. Just wondering if it is related to that or something else...

**Comment by asp8200** [comment]
> can you see what those errors are? Because in the past we had errors with human reads vs c elegans container. Just wondering if it is related to that or something else...

The test.csv-file contains a time-stamp, so I get different md5 each time the test is run. Probably something similar for the summary-html-file. I'll remove the md5-check of those two files.

**Comment by FriederikeHanssen** [comment]
With errors I actually meant the 9 errors reported by snpeff :)

**Comment by asp8200** [comment]
> With errors I actually meant the 9 errors reported by snpeff :)

The summary-html-file wasn't very informative concerning those 9 reported errors, so I went ahead and tried running the snpEff-command manually in verbose-mode:

`snpEff -Xmx3g -v WBcel235.105 -csvStats test.csv test.vcf`

From the `stdout`:
```
...
# WARNING!                   : Mitochondrion chromosome 'MtDNA' does not have a mitochondrion codon table (codon table = 'Standard'). You should update the config file.
#-----------------------------------------------
# Number of chromosomes      : 7
# Chromosomes                : Format 'chromo_name size codon_table'
#		'V'	20924180	Standard
#		'X'	17718942	Standard
#		'IV'	17493829	Standard
#		'II'	15279421	Standard
#		'I'	15072434	Standard
#		'III'	13783801	Standard
#		'MtDNA'	13794	Standard
#-----------------------------------------------

00:00:07 Predicting variants

ERRORS: Some errors were detected
Error type	Number of errors
ERROR_CHROMOSOME_NOT_FOUND	9
...
```
I'll investigate further later, but if you know what is wrong here and how it should be fixed, let me know. Cheers :-)

**Comment by FriederikeHanssen** [comment]
https://pcingola.github.io/SnpEff/se_faq/ sounds like it might be the things we already saw in sarek, which makes sense in the test there are files from sarscov used, but the snpeff container is Wcel.

**Review by FriederikeHanssen — APPROVED** [review]

**Pull request merged**
