### PR TITLE
module: bwa/samse

### LINKED ISSUE #589: new module: BWA/ALN
I think it would be good to have a module for [BWA/ALN](https://bioconda.github.io/recipes/bwa/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

### LINKED ISSUE #623: new module: BWA/SAMSE
I think it would be good to have a module for [SAMSE](https://bioconda.github.io/recipes/bwa/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

### PR DESCRIPTION
**Pull request by jfy133**
Adds `bwa samse` requiring #624

## PR checklist

Closes #623 and Closes #589 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `<SOFTWARE>.version.txt` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by grst** [comment]
Would it make sense to make a single module with samse/sampe that decides based on the `meta.single_end` which command to use? Would make it easier for pipelines which allow mixed single and paired end samples via the samplesheet.

**Comment by jfy133** [comment]
> Would it make sense to make a single module with samse/sampe that decides based on the `meta.single_end` which command to use? Would make it easier for pipelines which allow mixed single and paired end samples via the samplesheet.

Naja, I also originally started to do this but then it violates the aim of 'one module = one subcommand/tool, and I also didn't know what to call the module that would make it descriptive enough for a user to know what to call it.

I don't think it would be too difficult for a pipeline dev to use a branch to separate out single/paired end and merge again after. But it's a fair point

Maybe @nf-core/modules-team can pitch in to say whether it's OK in this case to 'violate' the 'one module = one tool' thing, and if anyone has suggestions for a name?

**Comment by grst** [comment]
sam**ps**e :see_no_evil:

**Comment by drpatelh** [comment]
Are the optional arguments different for both tools? If so, I think we will need to have separate modules because you may want to use different optional args with SE/PE data. Agree this would warrant having a single module otherwise.

**Comment by drpatelh** [comment]
Actually, I guess you could use `args` and `args2` for SE/PE data, respectively.

**Comment by jfy133** [comment]
@grst @drpatelh unfortunately they do take different arguments (well at least `sampe` accepts more, that samse does not), so for consistency I think it makes more sense to keep it separate. I also don't think `args` and `args2` is a optimal solution here because then that doesn't follow the standard of each `argsN` corresponding to the step in a pipe chain (at least from what I understand from the guidelines).

Personally, I think it makes more sense is to make the `bwa aln | ( bwa sampe | bwa samse)` procedure in a nf-core sub-workflow (once that's live), as you always have to run them together anyway. That way you can already have within the sub-workflow a branching procedure based on the metadata, so a pipeline dev doesn't need to worry.

Thoughts?

**Comment by grst** [comment]
Keeping them separate + the subworkflow sounds like a good solution.

**Comment by jfy133** [comment]
Awesome, thanks @grst . I'll do one more pass of the code after my meeting and re-request review

**Review by grst — APPROVED** [review]
LGTM!

**Pull request merged**
