### PR TITLE
Update seqwish to version 0.7.2

### LINKED ISSUE #1143: [FEATURE] Update seqwish to version 0.7.2

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #1143 

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

### CODE REVIEW

**Comment by heuermh** [comment]
Ping @subwaystation for additional review

**Comment by subwaystation** [comment]
Please wait for https://github.com/heuermh/nf-core-modules/pull/1. I didn't understand how to update this PR directly....

**Comment by subwaystation** [comment]
As just discussed with @heuermh the PAFs interface will come in with a different PR.
This looks good to me!

**Review by subwaystation — APPROVED** [review]
Looks good to me. I also tested locally :)

**Comment by heuermh** [comment]
Thank you @subwaystation

**Pull request merged**
