### PR TITLE
Add renovate config check

### PR DESCRIPTION
**Pull request by Emiller88**
- ci(renovate): Add pre-commit hook
- ci: Add a pre-commit GitHub action workflow

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by mirpedrol** [comment]
I saw in the action repo that they recommend using [pre-commit.ci](https://pre-commit.ci/), I'm not familiar with either of them, but should we consider this instead?

**Comment by maxulysse** [comment]
pre-commit test are failing

**Comment by Emiller88** [comment]
> I saw in the action repo that they recommend using [pre-commit.ci](https://pre-commit.ci/), I'm not familiar with either of them, but should we consider this instead?

Up to y'all, they recommend it because it's their product 😁 I'd rather keep it all unified and not find out whether their ci is free or not.

**Comment by Emiller88** [comment]
> pre-commit test are failing

Yeah I'll see if I can get around to fixing them. Mainly our fault for not checking it and therefore not enforcing it 😬

**Comment by Emiller88** [comment]
Forced the merge because bwa/mem fails with conda for now.

**Pull request merged**
